import QStab.QHL.Source.Examples.SurfaceExactDistance
import QStab.QHL.Source.Examples.SurfaceRecursiveAST
import QStab.QHL.Source.ParametricDistance

/-! # Canonical parametric Surface/NZ proof package

This module is the compact entry point for the current parametric QStab proof:

* Surface code data is generated by `mkSurfaceNZSurfaceSpec d hd3 hodd`.
* The QStab program is the fixed row-major stabilizer-measurement schedule.
* Faults are nondeterministic transition branches, proved by the five
  branch-specific Hoare derivation families from `Surface.lean`.
* The lower bound is an invariant proof over the fixed program.
* The upper bound is a concrete `d`-fault Type-0 execution.
-/

namespace QHL.Source.Examples.SurfaceParametricProof

open QStab QStab.Examples.SurfaceParametric QStab.Examples.SurfaceGeneral
     QHL.AssertionLang QHL.Source.Branch
     QHL.Source.Parametric QHL.Source.ParametricDistance
     QHL.Source.Examples.Surface
     QHL.Source.Examples.SurfaceExactDistance
     QHL.Source.Examples.SurfaceRecursiveAST

/-- Canonical generated odd-distance Surface/NZ code. -/
abbrev canonicalSurfaceSpec (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    NZSurfaceSpec d :=
  exactSurfaceSpec d hd3 hodd

/-- Canonical functional recursive AST for the odd-distance Surface code family.

The AST itself is distance-parametric: it has type `Nat -> Nat -> Stabilizer`,
so `d` is an argument of the interpreted program rather than a field baked into
the syntax. -/
abbrev canonicalSurfaceAST : SurfaceCodeAST.CodeFn :=
  SurfaceCodeAST.canonical

theorem canonicalSurfaceAST_body :
    canonicalSurfaceAST.body = SurfaceCodeAST.surfaceBody := rfl

/-- Fixed QStab program: measure the scheduled stabilizer at the current
    coordinate. This is not an injected-error trace. -/
noncomputable def canonicalSurfaceProgram
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    QStabProgram (canonicalSurfaceSpec d hd3 hodd).params :=
  surfaceProgram d (canonicalSurfaceSpec d hd3 hodd)

/-- Assertion-language logical-error predicate for the generated code. -/
noncomputable def canonicalSurfaceLogicalF
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    Formula (canonicalSurfaceSpec d hd3 hodd).params [] :=
  surface_logical_formula d (canonicalSurfaceSpec d hd3 hodd)

/-- Assertion-language invariant used by the lower-bound proof. -/
noncomputable def canonicalSurfaceInvariantF
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    Formula (canonicalSurfaceSpec d hd3 hodd).params [] :=
  surface_inv_formula d (canonicalSurfaceSpec d hd3 hodd)

/-- Five-branch nondeterministic Hoare proof for one QStab step. -/
noncomputable def canonicalSurfaceHavocDerivation
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    HavocProofDerivation
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceInvariantF d hd3 hodd)
      (canonicalSurfaceInvariantF d hd3 hodd) :=
  surface_havoc_derivation d (canonicalSurfaceSpec d hd3 hodd)

/-- Complete invariant derivation: initial assertion plus all-branch
    preservation. -/
noncomputable def canonicalSurfaceInvariantDerivation
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    InvariantDerivation
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceInvariantF d hd3 hodd) :=
  surface_invariant_derivation d (canonicalSurfaceSpec d hd3 hodd)

/-- Parametric lower bound, stated only in the fixed assertion language. -/
theorem canonicalSurfaceOperationalLower
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    OperationalLowerBound
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceLogicalF d hd3 hodd) d :=
  surface_operational_lower d hd3 hodd

/-- Concrete `d`-fault upper attack in QStab semantics. -/
theorem canonicalSurfaceOperationalUpper
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    OperationalUpperBound
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceLogicalF d hd3 hodd) d :=
  surface_operational_upper d hd3 hodd

/-- Exact operational circuit-level distance for every odd `d ≥ 3`. -/
theorem canonicalSurfaceOperationalExactDistance
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    OperationalExactDistance
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceLogicalF d hd3 hodd) d :=
  surface_operational_exact_distance d hd3 hodd

/-! ## Family-level exact-distance theorem

The following definitions expose the current theorem through the parametric
QStab layer.  The executable family is still the fixed row-major measurement
program:

```
fun coord => Prop(coord.x)
```

The `params` field uses the exact-distance budget retargeting from
`SurfaceExactDistance`, so the lower-bound proof and the `d`-fault upper attack
talk about the same generated QStab program at each legal distance.
-/

/-- Legal distances for the exact-distance Surface/NZ family. -/
abbrev canonicalSurfaceExactValid (d : Nat) : Prop :=
  3 ≤ d ∧ d % 2 = 1

/-- The exact-budget parametric QStab program AST for Surface/NZ. -/
noncomputable def canonicalSurfaceExactProgramAST : ParamQStabProgramAST where
  name := "surface.ast.nz.rowMajor.exactBudget"
  codeName := "surface.ast.code"
  scheduleName := "surface.ast.nz"
  Valid := canonicalSurfaceExactValid
  params := fun d hd => (canonicalSurfaceSpec d hd.1 hd.2).params
  body := .prop .coordX

/-- Denotation of the exact-budget Surface/NZ program family. -/
noncomputable def canonicalSurfaceExactParamQStab : ParamQStabProgram :=
  canonicalSurfaceExactProgramAST.toProgram

theorem canonicalSurfaceExact_instructionAt
    (d : Nat) (hd : canonicalSurfaceExactProgramAST.Valid d)
    (c : QECParams.Coord (canonicalSurfaceExactProgramAST.params d hd)) :
    canonicalSurfaceExactProgramAST.instructionAt d hd c = QStabInstruction.prop c.x :=
  rfl

theorem canonicalSurfaceExact_elaborates_rowMajor
    (d : Nat) (hd : canonicalSurfaceExactParamQStab.Valid d) :
    canonicalSurfaceExactParamQStab.elaborate d hd =
      canonicalSurfaceProgram d hd.1 hd.2 :=
  rfl

/-- Parametric logical-error formula for the exact-budget Surface/NZ family. -/
noncomputable def canonicalSurfaceExactLogicalF :
    ParamFormula canonicalSurfaceExactParamQStab :=
  fun d hd => canonicalSurfaceLogicalF d hd.1 hd.2

/-- The family distance expression: the distance parameter itself. -/
def canonicalSurfaceDistance :
    ParamDistance canonicalSurfaceExactParamQStab :=
  fun d _hd => d

theorem canonicalSurfaceParamOperationalLower :
    ParamOperationalLowerBound
      canonicalSurfaceExactParamQStab
      canonicalSurfaceExactLogicalF
      canonicalSurfaceDistance := by
  intro d hd
  simpa [canonicalSurfaceExact_elaborates_rowMajor, canonicalSurfaceExactLogicalF,
    canonicalSurfaceDistance] using
      canonicalSurfaceOperationalLower d hd.1 hd.2

theorem canonicalSurfaceParamOperationalUpper :
    ParamOperationalUpperBound
      canonicalSurfaceExactParamQStab
      canonicalSurfaceExactLogicalF
      canonicalSurfaceDistance := by
  intro d hd
  simpa [canonicalSurfaceExact_elaborates_rowMajor, canonicalSurfaceExactLogicalF,
    canonicalSurfaceDistance] using
      canonicalSurfaceOperationalUpper d hd.1 hd.2

/-- Family-level exact operational circuit distance for every odd `d ≥ 3`. -/
theorem canonicalSurfaceParamOperationalExactDistance :
    ParamOperationalExactDistance
      canonicalSurfaceExactParamQStab
      canonicalSurfaceExactLogicalF
      canonicalSurfaceDistance where
  lower := canonicalSurfaceParamOperationalLower
  upper := canonicalSurfaceParamOperationalUpper

theorem canonicalSurfaceParamExact_schemaSize :
    canonicalSurfaceParamOperationalExactDistance.schemaSize = 1 :=
  rfl

theorem canonicalSurfaceParamExact_instantiates
    (d : Nat) (hd : canonicalSurfaceExactParamQStab.Valid d) :
    canonicalSurfaceParamOperationalExactDistance.instantiate d hd =
      canonicalSurfaceOperationalExactDistance d hd.1 hd.2 :=
  rfl

/-- The branch proof shape is constant in `d`; each concrete branch derivation
    is a consequence step into a WP plus one primitive branch rule. -/
theorem canonicalSurfaceErr0Derivation_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1)
    (i : Fin (canonicalSurfaceSpec d hd3 hodd).params.n)
    (p : Pauli) (hp : p ≠ Pauli.I) :
    (surface_err0_derivation d (canonicalSurfaceSpec d hd3 hodd) i p hp).size = 2 :=
  rfl

theorem canonicalSurfaceErrIDerivation_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1)
    (i : Fin (canonicalSurfaceSpec d hd3 hodd).params.n)
    (p : Pauli) (hp : p ≠ Pauli.I) (mf : Bool) :
    (surface_errI_derivation d (canonicalSurfaceSpec d hd3 hodd) i p hp mf).size = 2 :=
  rfl

theorem canonicalSurfaceErrIIDerivation_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1)
    (e : ErrorVec (canonicalSurfaceSpec d hd3 hodd).params.n) (mf : Bool) :
    (surface_errII_derivation d (canonicalSurfaceSpec d hd3 hodd) e mf).size = 2 :=
  rfl

theorem canonicalSurfaceErrIIIDerivation_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    (surface_errIII_derivation d (canonicalSurfaceSpec d hd3 hodd)).size = 2 :=
  rfl

theorem canonicalSurfaceMeasDerivation_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    (surface_meas_derivation d (canonicalSurfaceSpec d hd3 hodd)).size = 2 :=
  rfl

theorem canonicalSurfaceHavocDerivation_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    (canonicalSurfaceHavocDerivation d hd3 hodd).size = 1 :=
  rfl

theorem canonicalSurfaceBarrierContract_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    (surface_barrier_contract_certificate d (canonicalSurfaceSpec d hd3 hodd)).size = 5 :=
  surface_barrier_contract_certificate_size d (canonicalSurfaceSpec d hd3 hodd)

theorem canonicalSurfaceFormulaProof_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    (surface_barrier_contract_certificate d
      (canonicalSurfaceSpec d hd3 hodd)).formulaCertificate.size = 7 :=
  SyntacticBarrierContractCertificate.formulaCertificate_size_eq_seven
    (surface_barrier_contract_certificate d (canonicalSurfaceSpec d hd3 hodd))

/-- The single build-gated artifact reviewers should inspect.

It contains exactly the fixed measurement program, assertion-language logical
predicate, assertion-language invariant, the five nondeterministic branch proof
families, the demonic one-step derivation, the full invariant derivation, and
the parametric lower/upper/exact operational distance theorems.  No sequencing
command or fixed injected-error QStab program appears in this object. -/
structure CanonicalSurfaceHoarePackage
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) where
  codeAST : SurfaceCodeAST.CodeFn
  codeAST_body : codeAST.body = SurfaceCodeAST.surfaceBody
  err0 :
    ∀ (i : Fin (canonicalSurfaceSpec d hd3 hodd).params.n) (p : Pauli),
      p ≠ Pauli.I →
      ProofDerivation
        (canonicalSurfaceProgram d hd3 hodd)
        (canonicalSurfaceInvariantF d hd3 hodd)
        (.err0 i p)
        (canonicalSurfaceInvariantF d hd3 hodd)
  errI :
    ∀ (i : Fin (canonicalSurfaceSpec d hd3 hodd).params.n) (p : Pauli),
      p ≠ Pauli.I → ∀ mf : Bool,
      ProofDerivation
        (canonicalSurfaceProgram d hd3 hodd)
        (canonicalSurfaceInvariantF d hd3 hodd)
        (.errI i p mf)
        (canonicalSurfaceInvariantF d hd3 hodd)
  errII :
    ∀ (e : ErrorVec (canonicalSurfaceSpec d hd3 hodd).params.n) (mf : Bool),
      ProofDerivation
        (canonicalSurfaceProgram d hd3 hodd)
        (canonicalSurfaceInvariantF d hd3 hodd)
        (.errII e mf)
        (canonicalSurfaceInvariantF d hd3 hodd)
  errIII :
    ProofDerivation
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceInvariantF d hd3 hodd)
      .errIII
      (canonicalSurfaceInvariantF d hd3 hodd)
  meas :
    ProofDerivation
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceInvariantF d hd3 hodd)
      .meas
      (canonicalSurfaceInvariantF d hd3 hodd)
  havoc :
    HavocProofDerivation
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceInvariantF d hd3 hodd)
      (canonicalSurfaceInvariantF d hd3 hodd)
  invariant :
    InvariantDerivation
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceInvariantF d hd3 hodd)
  lower :
    OperationalLowerBound
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceLogicalF d hd3 hodd) d
  upper :
    OperationalUpperBound
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceLogicalF d hd3 hodd) d
  exactDistance :
    OperationalExactDistance
      (canonicalSurfaceProgram d hd3 hodd)
      (canonicalSurfaceLogicalF d hd3 hodd) d

/-- The canonical parametric Surface/NZ theorem as one explicit Hoare package. -/
noncomputable def canonicalSurfaceHoarePackage
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    CanonicalSurfaceHoarePackage d hd3 hodd where
  codeAST := canonicalSurfaceAST
  codeAST_body := canonicalSurfaceAST_body
  err0 := fun i p hp => surface_err0_derivation d (canonicalSurfaceSpec d hd3 hodd) i p hp
  errI := fun i p hp mf => surface_errI_derivation d (canonicalSurfaceSpec d hd3 hodd) i p hp mf
  errII := fun e mf => surface_errII_derivation d (canonicalSurfaceSpec d hd3 hodd) e mf
  errIII := surface_errIII_derivation d (canonicalSurfaceSpec d hd3 hodd)
  meas := surface_meas_derivation d (canonicalSurfaceSpec d hd3 hodd)
  havoc := canonicalSurfaceHavocDerivation d hd3 hodd
  invariant := canonicalSurfaceInvariantDerivation d hd3 hodd
  lower := canonicalSurfaceOperationalLower d hd3 hodd
  upper := canonicalSurfaceOperationalUpper d hd3 hodd
  exactDistance := canonicalSurfaceOperationalExactDistance d hd3 hodd

theorem canonicalSurfaceHoarePackage_exact
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    (canonicalSurfaceHoarePackage d hd3 hodd).exactDistance =
      canonicalSurfaceOperationalExactDistance d hd3 hodd := rfl

theorem canonicalSurfaceHoarePackage_havoc_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1) :
    (canonicalSurfaceHoarePackage d hd3 hodd).havoc.size = 1 := rfl

theorem canonicalSurfaceHoarePackage_err0_size
    (d : Nat) (hd3 : 3 ≤ d) (hodd : d % 2 = 1)
    (i : Fin (canonicalSurfaceSpec d hd3 hodd).params.n)
    (p : Pauli) (hp : p ≠ Pauli.I) :
    ((canonicalSurfaceHoarePackage d hd3 hodd).err0 i p hp).size = 2 := rfl

#print axioms canonicalSurfaceOperationalLower
#print axioms canonicalSurfaceOperationalUpper
#print axioms canonicalSurfaceOperationalExactDistance
#print axioms canonicalSurfaceParamOperationalExactDistance
#print axioms canonicalSurfaceHoarePackage

end QHL.Source.Examples.SurfaceParametricProof
