name = "LeanQEC"
version = "0.1.0"
defaultTargets = ["leanqec"]

[[lean_lib]]
name = "LeanQEC"

[[lean_lib]]
name = "QStab"

[[lean_exe]]
name = "leanqec"
root = "Main"


[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"