import QStab.QHL.Assertion.Distance
import QStab.QHL.Source.Parametric

/-! # Parametric operational distance judgments

This module is the family-level wrapper around the concrete QStab distance
judgments from `QHL.Assertion.Distance`.

The concrete QStab layer still talks about one fixed `QStabProgram P`.  A
parametric program family `F : ParamQStabProgram` elaborates to such a concrete
program at every legal distance.  The definitions below lift lower, upper, and
exact circuit-distance judgments pointwise over all legal distances while
counting the proof object as one family-level schema.
-/

namespace QHL.Source.ParametricDistance

open QStab QHL.AssertionLang QHL.Source.Branch QHL.Source.Parametric

/-- A distance expression for a parametric QStab family.  For Surface/NZ this is
    normally `fun d _ => d`, but keeping it as syntax makes retargeted budgets
    and future families explicit. -/
abbrev ParamDistance (F : ParamQStabProgram) :=
  (d : Nat) -> F.Valid d -> Nat

/-- Pointwise operational lower bound for every legal member of a parametric
    QStab program family. -/
def ParamOperationalLowerBound (F : ParamQStabProgram)
    (logicalError : ParamFormula F) (distance : ParamDistance F) : Prop :=
  forall d hd,
    OperationalLowerBound (F.elaborate d hd) (logicalError d hd) (distance d hd)

/-- Pointwise operational upper bound for every legal member of a parametric
    QStab program family. -/
def ParamOperationalUpperBound (F : ParamQStabProgram)
    (logicalError : ParamFormula F) (distance : ParamDistance F) : Prop :=
  forall d hd,
    OperationalUpperBound (F.elaborate d hd) (logicalError d hd) (distance d hd)

/-- Matching operational lower and upper bounds for a whole parametric family. -/
structure ParamOperationalExactDistance (F : ParamQStabProgram)
    (logicalError : ParamFormula F) (distance : ParamDistance F) : Prop where
  lower : ParamOperationalLowerBound F logicalError distance
  upper : ParamOperationalUpperBound F logicalError distance

namespace ParamOperationalExactDistance

/-- Instantiate a family-level exact-distance theorem at one legal distance. -/
def instantiate {F : ParamQStabProgram} {logicalError : ParamFormula F}
    {distance : ParamDistance F}
    (D : ParamOperationalExactDistance F logicalError distance)
    (d : Nat) (hd : F.Valid d) :
    OperationalExactDistance
      (F.elaborate d hd) (logicalError d hd) (distance d hd) where
  lower := D.lower d hd
  upper := D.upper d hd

/-- The family proof schema is one node, independent of the generated program
    length at distance `d`. -/
def schemaSize {F : ParamQStabProgram} {logicalError : ParamFormula F}
    {distance : ParamDistance F}
    (_D : ParamOperationalExactDistance F logicalError distance) : Nat :=
  1

@[simp] theorem schemaSize_eq_one {F : ParamQStabProgram}
    {logicalError : ParamFormula F} {distance : ParamDistance F}
    (D : ParamOperationalExactDistance F logicalError distance) :
    D.schemaSize = 1 :=
  rfl

end ParamOperationalExactDistance

namespace ParamBarrierPackage

/-- The logical-error formula generated by a parametric barrier package. -/
def logicalErrorF {F : ParamQStabProgram} (B : ParamBarrierPackage F) :
    ParamFormula F :=
  fun d hd => .logicalMember (B.logical d hd) .error

/-- The family distance named by a parametric barrier package. -/
def distance {F : ParamQStabProgram} (B : ParamBarrierPackage F) :
    ParamDistance F :=
  fun d hd => (B.logical d hd).distance

/-- A checked parametric barrier package gives the operational lower bound for
    every elaborated concrete QStab program in the family. -/
theorem operationalLower {F : ParamQStabProgram} (B : ParamBarrierPackage F) :
    ParamOperationalLowerBound F (logicalErrorF B) (distance B) := by
  intro d hd s hreach
  have hdist := B.circuitDistance_active d hd s hreach
  simpa [logicalErrorF, distance, distanceLowerF, circuitDistanceF,
    distanceLowerBoundF] using hdist

end ParamBarrierPackage

end QHL.Source.ParametricDistance
