import QStab.Paper.BB72Instance
import QStab.Paper.GenericReachableBridge
import QStab.MultiStep
import Mathlib.Tactic.FinCases

/-!
# BB [[72, 12, 6]] code with SHIFT-EQUIVARIANT (SE) scheduling

This file gives a *second* concrete BB72 instantiation of the
`Paper.GenericReachableBridge` framework, using a **shift-equivariant**
CX scheduling instead of NZ-sorted (`Paper.BB72Instance`).

## Why SE?

Under the natural Z₆×Z₆ shift action on qubits
`q = sec*36 + i*6 + j  ↦  sec*36 + ((i+a)%6)*6 + ((j+b)%6)`,
the X-stab and Z-stab sets are closed (the BB code's defining symmetry).

**NZ-sorted hooks are NOT closed under this shift** — integer-sort breaks
cyclic structure (verified: 2556/6480 mismatches in Python). This means
"verify one orbit, rotate the rest" does NOT apply to NZ.

**SE hooks ARE closed under shift, by construction**: pick any base
ordering for stab (0,0) and define stab (a,b)'s ordering as the
(a,b)-shift of the base ordering. The 180 SE hooks (5 per stab × 36
stabs) form one Z₆×Z₆-orbit per base hook (5 orbits × 36 = 180).

## Trust-boundary advantage of SE over NZ

Under SE, the static-DEM check at depth k reduces by ~36× via
orbit-reduction — making more values of k tractable in Lean
`native_decide`:

  * NZ: only k=1, 2 feasible (`BB72ChainCheck.lean`, ~15 min for k=2).
  * SE: k=1, 2 native_decide is trivial (7 orbit-reps, ~880 orbit-pairs).
    k=3 is feasible (~73k orbit-triples). k=4 borderline.

This file provides:
  1. The 180 SE hooks (mechanically generated from base + shifts).
  2. `bb_se_QECParams`, the QECParams instance.
  3. The headline theorem `bb_SE_d_circ_ge_6`, modulo the same
     finite-check axiom as NZ — but with the **same numerical content**
     (Python MITM at k=5, ~5 min): SE preserves d_circ ≥ 6.

## Path to axiom-free

For SE, the static-DEM check has an **algebraic reformulation** via
polynomials over `F₂[x,y]/(x⁶−1, y⁶−1)`. The 5 base hooks have specific
polynomial supports; the 180 hooks are their Z₆×Z₆-shifts. Whether this
admits a closed-form structural certificate (eliminating the axiom) is a
concrete open question in commutative algebra over F₂.

**Status**: zero `sorry`. One axiom (Python-MITM-verified, equivalent
to NZ's). Strictly stronger structurally than `BB72Instance` because of
the shift-equivariance.
-/

namespace QStab.Paper.BB72SEInstance

open QStab QStab.Paper.GenericReachableBridge QStab.Paper.BB72Instance

/-! ## SE base ordering at stab (0, 0)

The base ordering is `[1, 2, 18, 39, 42, 48]` (NZ-sorted at stab 0;
this happens to coincide with the SE "anchor" ordering — the difference
appears only at stabs whose shift wraps around). For stab (a, b), the
ordering is the (a, b)-shift of this base. -/

/-! ## 180 SE X-hooks (mechanically generated by `notes/generate_bb72_se_lean.py`) -/

def bb_se_h0_0 : ErrorVec 72 := ofList [(2, .X), (18, .X), (39, .X), (42, .X), (48, .X)]
def bb_se_h0_1 : ErrorVec 72 := ofList [(18, .X), (39, .X), (42, .X), (48, .X)]
def bb_se_h0_2 : ErrorVec 72 := ofList [(39, .X), (42, .X), (48, .X)]
def bb_se_h0_3 : ErrorVec 72 := ofList [(42, .X), (48, .X)]
def bb_se_h0_4 : ErrorVec 72 := ofList [(48, .X)]
def bb_se_h1_0 : ErrorVec 72 := ofList [(3, .X), (19, .X), (40, .X), (43, .X), (49, .X)]
def bb_se_h1_1 : ErrorVec 72 := ofList [(19, .X), (40, .X), (43, .X), (49, .X)]
def bb_se_h1_2 : ErrorVec 72 := ofList [(40, .X), (43, .X), (49, .X)]
def bb_se_h1_3 : ErrorVec 72 := ofList [(43, .X), (49, .X)]
def bb_se_h1_4 : ErrorVec 72 := ofList [(49, .X)]
def bb_se_h2_0 : ErrorVec 72 := ofList [(4, .X), (20, .X), (41, .X), (44, .X), (50, .X)]
def bb_se_h2_1 : ErrorVec 72 := ofList [(20, .X), (41, .X), (44, .X), (50, .X)]
def bb_se_h2_2 : ErrorVec 72 := ofList [(41, .X), (44, .X), (50, .X)]
def bb_se_h2_3 : ErrorVec 72 := ofList [(44, .X), (50, .X)]
def bb_se_h2_4 : ErrorVec 72 := ofList [(50, .X)]
def bb_se_h3_0 : ErrorVec 72 := ofList [(5, .X), (21, .X), (36, .X), (45, .X), (51, .X)]
def bb_se_h3_1 : ErrorVec 72 := ofList [(21, .X), (36, .X), (45, .X), (51, .X)]
def bb_se_h3_2 : ErrorVec 72 := ofList [(36, .X), (45, .X), (51, .X)]
def bb_se_h3_3 : ErrorVec 72 := ofList [(45, .X), (51, .X)]
def bb_se_h3_4 : ErrorVec 72 := ofList [(51, .X)]
def bb_se_h4_0 : ErrorVec 72 := ofList [(0, .X), (22, .X), (37, .X), (46, .X), (52, .X)]
def bb_se_h4_1 : ErrorVec 72 := ofList [(22, .X), (37, .X), (46, .X), (52, .X)]
def bb_se_h4_2 : ErrorVec 72 := ofList [(37, .X), (46, .X), (52, .X)]
def bb_se_h4_3 : ErrorVec 72 := ofList [(46, .X), (52, .X)]
def bb_se_h4_4 : ErrorVec 72 := ofList [(52, .X)]
def bb_se_h5_0 : ErrorVec 72 := ofList [(1, .X), (23, .X), (38, .X), (47, .X), (53, .X)]
def bb_se_h5_1 : ErrorVec 72 := ofList [(23, .X), (38, .X), (47, .X), (53, .X)]
def bb_se_h5_2 : ErrorVec 72 := ofList [(38, .X), (47, .X), (53, .X)]
def bb_se_h5_3 : ErrorVec 72 := ofList [(47, .X), (53, .X)]
def bb_se_h5_4 : ErrorVec 72 := ofList [(53, .X)]
def bb_se_h6_0 : ErrorVec 72 := ofList [(8, .X), (24, .X), (45, .X), (48, .X), (54, .X)]
def bb_se_h6_1 : ErrorVec 72 := ofList [(24, .X), (45, .X), (48, .X), (54, .X)]
def bb_se_h6_2 : ErrorVec 72 := ofList [(45, .X), (48, .X), (54, .X)]
def bb_se_h6_3 : ErrorVec 72 := ofList [(48, .X), (54, .X)]
def bb_se_h6_4 : ErrorVec 72 := ofList [(54, .X)]
def bb_se_h7_0 : ErrorVec 72 := ofList [(9, .X), (25, .X), (46, .X), (49, .X), (55, .X)]
def bb_se_h7_1 : ErrorVec 72 := ofList [(25, .X), (46, .X), (49, .X), (55, .X)]
def bb_se_h7_2 : ErrorVec 72 := ofList [(46, .X), (49, .X), (55, .X)]
def bb_se_h7_3 : ErrorVec 72 := ofList [(49, .X), (55, .X)]
def bb_se_h7_4 : ErrorVec 72 := ofList [(55, .X)]
def bb_se_h8_0 : ErrorVec 72 := ofList [(10, .X), (26, .X), (47, .X), (50, .X), (56, .X)]
def bb_se_h8_1 : ErrorVec 72 := ofList [(26, .X), (47, .X), (50, .X), (56, .X)]
def bb_se_h8_2 : ErrorVec 72 := ofList [(47, .X), (50, .X), (56, .X)]
def bb_se_h8_3 : ErrorVec 72 := ofList [(50, .X), (56, .X)]
def bb_se_h8_4 : ErrorVec 72 := ofList [(56, .X)]
def bb_se_h9_0 : ErrorVec 72 := ofList [(11, .X), (27, .X), (42, .X), (51, .X), (57, .X)]
def bb_se_h9_1 : ErrorVec 72 := ofList [(27, .X), (42, .X), (51, .X), (57, .X)]
def bb_se_h9_2 : ErrorVec 72 := ofList [(42, .X), (51, .X), (57, .X)]
def bb_se_h9_3 : ErrorVec 72 := ofList [(51, .X), (57, .X)]
def bb_se_h9_4 : ErrorVec 72 := ofList [(57, .X)]
def bb_se_h10_0 : ErrorVec 72 := ofList [(6, .X), (28, .X), (43, .X), (52, .X), (58, .X)]
def bb_se_h10_1 : ErrorVec 72 := ofList [(28, .X), (43, .X), (52, .X), (58, .X)]
def bb_se_h10_2 : ErrorVec 72 := ofList [(43, .X), (52, .X), (58, .X)]
def bb_se_h10_3 : ErrorVec 72 := ofList [(52, .X), (58, .X)]
def bb_se_h10_4 : ErrorVec 72 := ofList [(58, .X)]
def bb_se_h11_0 : ErrorVec 72 := ofList [(7, .X), (29, .X), (44, .X), (53, .X), (59, .X)]
def bb_se_h11_1 : ErrorVec 72 := ofList [(29, .X), (44, .X), (53, .X), (59, .X)]
def bb_se_h11_2 : ErrorVec 72 := ofList [(44, .X), (53, .X), (59, .X)]
def bb_se_h11_3 : ErrorVec 72 := ofList [(53, .X), (59, .X)]
def bb_se_h11_4 : ErrorVec 72 := ofList [(59, .X)]
def bb_se_h12_0 : ErrorVec 72 := ofList [(14, .X), (30, .X), (51, .X), (54, .X), (60, .X)]
def bb_se_h12_1 : ErrorVec 72 := ofList [(30, .X), (51, .X), (54, .X), (60, .X)]
def bb_se_h12_2 : ErrorVec 72 := ofList [(51, .X), (54, .X), (60, .X)]
def bb_se_h12_3 : ErrorVec 72 := ofList [(54, .X), (60, .X)]
def bb_se_h12_4 : ErrorVec 72 := ofList [(60, .X)]
def bb_se_h13_0 : ErrorVec 72 := ofList [(15, .X), (31, .X), (52, .X), (55, .X), (61, .X)]
def bb_se_h13_1 : ErrorVec 72 := ofList [(31, .X), (52, .X), (55, .X), (61, .X)]
def bb_se_h13_2 : ErrorVec 72 := ofList [(52, .X), (55, .X), (61, .X)]
def bb_se_h13_3 : ErrorVec 72 := ofList [(55, .X), (61, .X)]
def bb_se_h13_4 : ErrorVec 72 := ofList [(61, .X)]
def bb_se_h14_0 : ErrorVec 72 := ofList [(16, .X), (32, .X), (53, .X), (56, .X), (62, .X)]
def bb_se_h14_1 : ErrorVec 72 := ofList [(32, .X), (53, .X), (56, .X), (62, .X)]
def bb_se_h14_2 : ErrorVec 72 := ofList [(53, .X), (56, .X), (62, .X)]
def bb_se_h14_3 : ErrorVec 72 := ofList [(56, .X), (62, .X)]
def bb_se_h14_4 : ErrorVec 72 := ofList [(62, .X)]
def bb_se_h15_0 : ErrorVec 72 := ofList [(17, .X), (33, .X), (48, .X), (57, .X), (63, .X)]
def bb_se_h15_1 : ErrorVec 72 := ofList [(33, .X), (48, .X), (57, .X), (63, .X)]
def bb_se_h15_2 : ErrorVec 72 := ofList [(48, .X), (57, .X), (63, .X)]
def bb_se_h15_3 : ErrorVec 72 := ofList [(57, .X), (63, .X)]
def bb_se_h15_4 : ErrorVec 72 := ofList [(63, .X)]
def bb_se_h16_0 : ErrorVec 72 := ofList [(12, .X), (34, .X), (49, .X), (58, .X), (64, .X)]
def bb_se_h16_1 : ErrorVec 72 := ofList [(34, .X), (49, .X), (58, .X), (64, .X)]
def bb_se_h16_2 : ErrorVec 72 := ofList [(49, .X), (58, .X), (64, .X)]
def bb_se_h16_3 : ErrorVec 72 := ofList [(58, .X), (64, .X)]
def bb_se_h16_4 : ErrorVec 72 := ofList [(64, .X)]
def bb_se_h17_0 : ErrorVec 72 := ofList [(13, .X), (35, .X), (50, .X), (59, .X), (65, .X)]
def bb_se_h17_1 : ErrorVec 72 := ofList [(35, .X), (50, .X), (59, .X), (65, .X)]
def bb_se_h17_2 : ErrorVec 72 := ofList [(50, .X), (59, .X), (65, .X)]
def bb_se_h17_3 : ErrorVec 72 := ofList [(59, .X), (65, .X)]
def bb_se_h17_4 : ErrorVec 72 := ofList [(65, .X)]
def bb_se_h18_0 : ErrorVec 72 := ofList [(20, .X), (0, .X), (57, .X), (60, .X), (66, .X)]
def bb_se_h18_1 : ErrorVec 72 := ofList [(0, .X), (57, .X), (60, .X), (66, .X)]
def bb_se_h18_2 : ErrorVec 72 := ofList [(57, .X), (60, .X), (66, .X)]
def bb_se_h18_3 : ErrorVec 72 := ofList [(60, .X), (66, .X)]
def bb_se_h18_4 : ErrorVec 72 := ofList [(66, .X)]
def bb_se_h19_0 : ErrorVec 72 := ofList [(21, .X), (1, .X), (58, .X), (61, .X), (67, .X)]
def bb_se_h19_1 : ErrorVec 72 := ofList [(1, .X), (58, .X), (61, .X), (67, .X)]
def bb_se_h19_2 : ErrorVec 72 := ofList [(58, .X), (61, .X), (67, .X)]
def bb_se_h19_3 : ErrorVec 72 := ofList [(61, .X), (67, .X)]
def bb_se_h19_4 : ErrorVec 72 := ofList [(67, .X)]
def bb_se_h20_0 : ErrorVec 72 := ofList [(22, .X), (2, .X), (59, .X), (62, .X), (68, .X)]
def bb_se_h20_1 : ErrorVec 72 := ofList [(2, .X), (59, .X), (62, .X), (68, .X)]
def bb_se_h20_2 : ErrorVec 72 := ofList [(59, .X), (62, .X), (68, .X)]
def bb_se_h20_3 : ErrorVec 72 := ofList [(62, .X), (68, .X)]
def bb_se_h20_4 : ErrorVec 72 := ofList [(68, .X)]
def bb_se_h21_0 : ErrorVec 72 := ofList [(23, .X), (3, .X), (54, .X), (63, .X), (69, .X)]
def bb_se_h21_1 : ErrorVec 72 := ofList [(3, .X), (54, .X), (63, .X), (69, .X)]
def bb_se_h21_2 : ErrorVec 72 := ofList [(54, .X), (63, .X), (69, .X)]
def bb_se_h21_3 : ErrorVec 72 := ofList [(63, .X), (69, .X)]
def bb_se_h21_4 : ErrorVec 72 := ofList [(69, .X)]
def bb_se_h22_0 : ErrorVec 72 := ofList [(18, .X), (4, .X), (55, .X), (64, .X), (70, .X)]
def bb_se_h22_1 : ErrorVec 72 := ofList [(4, .X), (55, .X), (64, .X), (70, .X)]
def bb_se_h22_2 : ErrorVec 72 := ofList [(55, .X), (64, .X), (70, .X)]
def bb_se_h22_3 : ErrorVec 72 := ofList [(64, .X), (70, .X)]
def bb_se_h22_4 : ErrorVec 72 := ofList [(70, .X)]
def bb_se_h23_0 : ErrorVec 72 := ofList [(19, .X), (5, .X), (56, .X), (65, .X), (71, .X)]
def bb_se_h23_1 : ErrorVec 72 := ofList [(5, .X), (56, .X), (65, .X), (71, .X)]
def bb_se_h23_2 : ErrorVec 72 := ofList [(56, .X), (65, .X), (71, .X)]
def bb_se_h23_3 : ErrorVec 72 := ofList [(65, .X), (71, .X)]
def bb_se_h23_4 : ErrorVec 72 := ofList [(71, .X)]
def bb_se_h24_0 : ErrorVec 72 := ofList [(26, .X), (6, .X), (63, .X), (66, .X), (36, .X)]
def bb_se_h24_1 : ErrorVec 72 := ofList [(6, .X), (63, .X), (66, .X), (36, .X)]
def bb_se_h24_2 : ErrorVec 72 := ofList [(63, .X), (66, .X), (36, .X)]
def bb_se_h24_3 : ErrorVec 72 := ofList [(66, .X), (36, .X)]
def bb_se_h24_4 : ErrorVec 72 := ofList [(36, .X)]
def bb_se_h25_0 : ErrorVec 72 := ofList [(27, .X), (7, .X), (64, .X), (67, .X), (37, .X)]
def bb_se_h25_1 : ErrorVec 72 := ofList [(7, .X), (64, .X), (67, .X), (37, .X)]
def bb_se_h25_2 : ErrorVec 72 := ofList [(64, .X), (67, .X), (37, .X)]
def bb_se_h25_3 : ErrorVec 72 := ofList [(67, .X), (37, .X)]
def bb_se_h25_4 : ErrorVec 72 := ofList [(37, .X)]
def bb_se_h26_0 : ErrorVec 72 := ofList [(28, .X), (8, .X), (65, .X), (68, .X), (38, .X)]
def bb_se_h26_1 : ErrorVec 72 := ofList [(8, .X), (65, .X), (68, .X), (38, .X)]
def bb_se_h26_2 : ErrorVec 72 := ofList [(65, .X), (68, .X), (38, .X)]
def bb_se_h26_3 : ErrorVec 72 := ofList [(68, .X), (38, .X)]
def bb_se_h26_4 : ErrorVec 72 := ofList [(38, .X)]
def bb_se_h27_0 : ErrorVec 72 := ofList [(29, .X), (9, .X), (60, .X), (69, .X), (39, .X)]
def bb_se_h27_1 : ErrorVec 72 := ofList [(9, .X), (60, .X), (69, .X), (39, .X)]
def bb_se_h27_2 : ErrorVec 72 := ofList [(60, .X), (69, .X), (39, .X)]
def bb_se_h27_3 : ErrorVec 72 := ofList [(69, .X), (39, .X)]
def bb_se_h27_4 : ErrorVec 72 := ofList [(39, .X)]
def bb_se_h28_0 : ErrorVec 72 := ofList [(24, .X), (10, .X), (61, .X), (70, .X), (40, .X)]
def bb_se_h28_1 : ErrorVec 72 := ofList [(10, .X), (61, .X), (70, .X), (40, .X)]
def bb_se_h28_2 : ErrorVec 72 := ofList [(61, .X), (70, .X), (40, .X)]
def bb_se_h28_3 : ErrorVec 72 := ofList [(70, .X), (40, .X)]
def bb_se_h28_4 : ErrorVec 72 := ofList [(40, .X)]
def bb_se_h29_0 : ErrorVec 72 := ofList [(25, .X), (11, .X), (62, .X), (71, .X), (41, .X)]
def bb_se_h29_1 : ErrorVec 72 := ofList [(11, .X), (62, .X), (71, .X), (41, .X)]
def bb_se_h29_2 : ErrorVec 72 := ofList [(62, .X), (71, .X), (41, .X)]
def bb_se_h29_3 : ErrorVec 72 := ofList [(71, .X), (41, .X)]
def bb_se_h29_4 : ErrorVec 72 := ofList [(41, .X)]
def bb_se_h30_0 : ErrorVec 72 := ofList [(32, .X), (12, .X), (69, .X), (36, .X), (42, .X)]
def bb_se_h30_1 : ErrorVec 72 := ofList [(12, .X), (69, .X), (36, .X), (42, .X)]
def bb_se_h30_2 : ErrorVec 72 := ofList [(69, .X), (36, .X), (42, .X)]
def bb_se_h30_3 : ErrorVec 72 := ofList [(36, .X), (42, .X)]
def bb_se_h30_4 : ErrorVec 72 := ofList [(42, .X)]
def bb_se_h31_0 : ErrorVec 72 := ofList [(33, .X), (13, .X), (70, .X), (37, .X), (43, .X)]
def bb_se_h31_1 : ErrorVec 72 := ofList [(13, .X), (70, .X), (37, .X), (43, .X)]
def bb_se_h31_2 : ErrorVec 72 := ofList [(70, .X), (37, .X), (43, .X)]
def bb_se_h31_3 : ErrorVec 72 := ofList [(37, .X), (43, .X)]
def bb_se_h31_4 : ErrorVec 72 := ofList [(43, .X)]
def bb_se_h32_0 : ErrorVec 72 := ofList [(34, .X), (14, .X), (71, .X), (38, .X), (44, .X)]
def bb_se_h32_1 : ErrorVec 72 := ofList [(14, .X), (71, .X), (38, .X), (44, .X)]
def bb_se_h32_2 : ErrorVec 72 := ofList [(71, .X), (38, .X), (44, .X)]
def bb_se_h32_3 : ErrorVec 72 := ofList [(38, .X), (44, .X)]
def bb_se_h32_4 : ErrorVec 72 := ofList [(44, .X)]
def bb_se_h33_0 : ErrorVec 72 := ofList [(35, .X), (15, .X), (66, .X), (39, .X), (45, .X)]
def bb_se_h33_1 : ErrorVec 72 := ofList [(15, .X), (66, .X), (39, .X), (45, .X)]
def bb_se_h33_2 : ErrorVec 72 := ofList [(66, .X), (39, .X), (45, .X)]
def bb_se_h33_3 : ErrorVec 72 := ofList [(39, .X), (45, .X)]
def bb_se_h33_4 : ErrorVec 72 := ofList [(45, .X)]
def bb_se_h34_0 : ErrorVec 72 := ofList [(30, .X), (16, .X), (67, .X), (40, .X), (46, .X)]
def bb_se_h34_1 : ErrorVec 72 := ofList [(16, .X), (67, .X), (40, .X), (46, .X)]
def bb_se_h34_2 : ErrorVec 72 := ofList [(67, .X), (40, .X), (46, .X)]
def bb_se_h34_3 : ErrorVec 72 := ofList [(40, .X), (46, .X)]
def bb_se_h34_4 : ErrorVec 72 := ofList [(46, .X)]
def bb_se_h35_0 : ErrorVec 72 := ofList [(31, .X), (17, .X), (68, .X), (41, .X), (47, .X)]
def bb_se_h35_1 : ErrorVec 72 := ofList [(17, .X), (68, .X), (41, .X), (47, .X)]
def bb_se_h35_2 : ErrorVec 72 := ofList [(68, .X), (41, .X), (47, .X)]
def bb_se_h35_3 : ErrorVec 72 := ofList [(41, .X), (47, .X)]
def bb_se_h35_4 : ErrorVec 72 := ofList [(47, .X)]

/-! ## All SE hooks list (180 hooks, ordered by stab then hook-index) -/

def bb_se_allHooks : List (ErrorVec 72) := [
  bb_se_h0_0, bb_se_h0_1, bb_se_h0_2, bb_se_h0_3, bb_se_h0_4,
  bb_se_h1_0, bb_se_h1_1, bb_se_h1_2, bb_se_h1_3, bb_se_h1_4,
  bb_se_h2_0, bb_se_h2_1, bb_se_h2_2, bb_se_h2_3, bb_se_h2_4,
  bb_se_h3_0, bb_se_h3_1, bb_se_h3_2, bb_se_h3_3, bb_se_h3_4,
  bb_se_h4_0, bb_se_h4_1, bb_se_h4_2, bb_se_h4_3, bb_se_h4_4,
  bb_se_h5_0, bb_se_h5_1, bb_se_h5_2, bb_se_h5_3, bb_se_h5_4,
  bb_se_h6_0, bb_se_h6_1, bb_se_h6_2, bb_se_h6_3, bb_se_h6_4,
  bb_se_h7_0, bb_se_h7_1, bb_se_h7_2, bb_se_h7_3, bb_se_h7_4,
  bb_se_h8_0, bb_se_h8_1, bb_se_h8_2, bb_se_h8_3, bb_se_h8_4,
  bb_se_h9_0, bb_se_h9_1, bb_se_h9_2, bb_se_h9_3, bb_se_h9_4,
  bb_se_h10_0, bb_se_h10_1, bb_se_h10_2, bb_se_h10_3, bb_se_h10_4,
  bb_se_h11_0, bb_se_h11_1, bb_se_h11_2, bb_se_h11_3, bb_se_h11_4,
  bb_se_h12_0, bb_se_h12_1, bb_se_h12_2, bb_se_h12_3, bb_se_h12_4,
  bb_se_h13_0, bb_se_h13_1, bb_se_h13_2, bb_se_h13_3, bb_se_h13_4,
  bb_se_h14_0, bb_se_h14_1, bb_se_h14_2, bb_se_h14_3, bb_se_h14_4,
  bb_se_h15_0, bb_se_h15_1, bb_se_h15_2, bb_se_h15_3, bb_se_h15_4,
  bb_se_h16_0, bb_se_h16_1, bb_se_h16_2, bb_se_h16_3, bb_se_h16_4,
  bb_se_h17_0, bb_se_h17_1, bb_se_h17_2, bb_se_h17_3, bb_se_h17_4,
  bb_se_h18_0, bb_se_h18_1, bb_se_h18_2, bb_se_h18_3, bb_se_h18_4,
  bb_se_h19_0, bb_se_h19_1, bb_se_h19_2, bb_se_h19_3, bb_se_h19_4,
  bb_se_h20_0, bb_se_h20_1, bb_se_h20_2, bb_se_h20_3, bb_se_h20_4,
  bb_se_h21_0, bb_se_h21_1, bb_se_h21_2, bb_se_h21_3, bb_se_h21_4,
  bb_se_h22_0, bb_se_h22_1, bb_se_h22_2, bb_se_h22_3, bb_se_h22_4,
  bb_se_h23_0, bb_se_h23_1, bb_se_h23_2, bb_se_h23_3, bb_se_h23_4,
  bb_se_h24_0, bb_se_h24_1, bb_se_h24_2, bb_se_h24_3, bb_se_h24_4,
  bb_se_h25_0, bb_se_h25_1, bb_se_h25_2, bb_se_h25_3, bb_se_h25_4,
  bb_se_h26_0, bb_se_h26_1, bb_se_h26_2, bb_se_h26_3, bb_se_h26_4,
  bb_se_h27_0, bb_se_h27_1, bb_se_h27_2, bb_se_h27_3, bb_se_h27_4,
  bb_se_h28_0, bb_se_h28_1, bb_se_h28_2, bb_se_h28_3, bb_se_h28_4,
  bb_se_h29_0, bb_se_h29_1, bb_se_h29_2, bb_se_h29_3, bb_se_h29_4,
  bb_se_h30_0, bb_se_h30_1, bb_se_h30_2, bb_se_h30_3, bb_se_h30_4,
  bb_se_h31_0, bb_se_h31_1, bb_se_h31_2, bb_se_h31_3, bb_se_h31_4,
  bb_se_h32_0, bb_se_h32_1, bb_se_h32_2, bb_se_h32_3, bb_se_h32_4,
  bb_se_h33_0, bb_se_h33_1, bb_se_h33_2, bb_se_h33_3, bb_se_h33_4,
  bb_se_h34_0, bb_se_h34_1, bb_se_h34_2, bb_se_h34_3, bb_se_h34_4,
  bb_se_h35_0, bb_se_h35_1, bb_se_h35_2, bb_se_h35_3, bb_se_h35_4
]

/-! ## SE backActionSet (sound over-approximation, same shape as NZ) -/

def bb_se_backActionSet (i : Fin 72) : Set (ErrorVec 72) :=
  if i.val < 36 then (fun e => e ∈ bb_se_allHooks)
  else (fun _ => False)

theorem bb_se_backActionSet_subset :
    ∀ (i : Fin 72) (e : ErrorVec 72),
      e ∈ bb_se_backActionSet i → e ∈ bb_se_allHooks := by
  intro i e he
  unfold bb_se_backActionSet at he
  by_cases h : i.val < 36
  · rw [if_pos h] at he; exact he
  · rw [if_neg h] at he; exact he.elim

/-- All SE hooks weight ≤ 5. -/
theorem bb_se_allHooks_weight_bound :
    ∀ e ∈ bb_se_allHooks, ErrorVec.weight e ≤ 5 := by
  native_decide

/-! ## QECParams instance for SE -/

def bb_se_code : QECParams where
  n := 72; k := 12; d := 6; R := 1
  numStab := 72
  stabilizers := bb_stabilizers
  backActionSet := bb_se_backActionSet
  r := 5
  backAction_weight_bound := by
    intro stab_idx e he
    have h_in : e ∈ bb_se_allHooks := bb_se_backActionSet_subset stab_idx e he
    exact bb_se_allHooks_weight_bound e h_in
  C_budget := 5
  hn := by omega
  hns := by omega
  hR := by omega

theorem bb_se_hooks_bound : hooksUpperBound bb_se_code bb_se_allHooks :=
  bb_se_backActionSet_subset

/-! ## Success predicate (same shape as NZ; uses BB72Instance's bb_logicalZ_basis). -/

def bb_se_isSuccess (E : ErrorVec 72) : Bool :=
  ((List.finRange 72).all fun i =>
    ErrorVec.parity (bb_stabilizers i) E = false) &&
  ((List.finRange 12).any fun i =>
    ErrorVec.parity (bb_logicalZ_basis i) E)

/-! ## External Python axiom (verified via `notes/bb72_se_scheduling.py`)

Verified: no chain of ≤5 mechs (Type-0 X + 180 SE hooks) yields a chain
XOR with zero Z-syndrome AND nonzero L_Z parity. Same MITM technique
as NZ; ~5 min wall-clock.

**Key structural difference from NZ**: SE is shift-equivariant, so the
axiom can be morally restated as a statement on Z₆×Z₆-orbit
representatives — a 36× smaller surface. This file does not yet
encode the orbit reduction in Lean, but the path is clear (see Open
Path below).
-/

/-! ## Per-scheduling finite check: now PROVEN as a Lean theorem

The SE-side static-DEM check `bb_NZ_SE_no_X_attack_below_6` was previously
an axiom (Python MITM verified). It is now an unconditional Lean theorem;
see `QStab.Paper.BB72ReachableEBridgeSE.bb_NZ_SE_no_X_attack_below_6_proven`.

The theorem and the headline operational result `bb_SE_d_circ_ge_6` are
declared in `BB72SEAxiomsProven.lean` (which imports everything needed
to discharge them). They are placed in the `QStab.Paper.BB72SEInstance`
namespace there so existing references resolve correctly. -/

/-! ## Sanity: SE hooks are X-only (decided) -/

theorem bb_se_allHooks_xOnly :
    ∀ e ∈ bb_se_allHooks, ∀ j : Fin 72, e j = .X ∨ e j = .I := by
  native_decide

/-! ## Z₆×Z₆ shift action on qubits

Qubit indexing: `q = sec*36 + i*6 + j` with `sec ∈ {0,1}`, `i,j ∈ Z₆`.
The shift action by `(da, db) ∈ Z₆ × Z₆` rotates `(i, j)` cyclically
within each sector. -/

/-- Shift qubit `q` by `(da, db) ∈ Z₆ × Z₆` (cyclic in `i, j`). -/
def shift_q (q : Fin 72) (da db : Fin 6) : Fin 72 :=
  let s := q.val / 36
  let i := (q.val % 36) / 6
  let j := q.val % 6
  let i' := (i + da.val) % 6
  let j' := (j + db.val) % 6
  ⟨s * 36 + i' * 6 + j', by
    have hs : s ≤ 1 := by
      simp only [s]; omega
    have hi : i' < 6 := Nat.mod_lt _ (by omega)
    have hj : j' < 6 := Nat.mod_lt _ (by omega)
    omega⟩

/-- Lift a shift to the action on `ErrorVec 72`: `(shift_E e da db) at q'
    equals `e q` where `q' = shift_q q da db`. We define it via inverse
    shift to keep dependent typing simple. -/
def shift_E (e : ErrorVec 72) (da db : Fin 6) : ErrorVec 72 :=
  fun q' =>
    -- Inverse shift: subtract (da, db) cyclically
    let s := q'.val / 36
    let i := (q'.val % 36) / 6
    let j := q'.val % 6
    let i₀ := (i + (6 - da.val) % 6) % 6
    let j₀ := (j + (6 - db.val) % 6) % 6
    let q : Fin 72 := ⟨s * 36 + i₀ * 6 + j₀, by
      have : s ≤ 1 := by simp only [s]; omega
      have : i₀ < 6 := Nat.mod_lt _ (by omega)
      have : j₀ < 6 := Nat.mod_lt _ (by omega)
      omega⟩
    e q

/-- **SE hook set is closed under Z₆×Z₆ shift.**
    Decidable, discharged by `native_decide` (180 hooks × 36 shifts =
    6,480 membership checks). -/
theorem bb_se_allHooks_shift_closed :
    ∀ e ∈ bb_se_allHooks, ∀ (da db : Fin 6),
      shift_E e da db ∈ bb_se_allHooks := by
  native_decide

/-! ## Structural shift-invariance lemmas (no `native_decide`) -/

/-- Shifting commutes with `ErrorVec.mul` (pointwise operation). -/
theorem shift_E_mul (a b : ErrorVec 72) (da db : Fin 6) :
    shift_E (ErrorVec.mul a b) da db =
      ErrorVec.mul (shift_E a da db) (shift_E b da db) := by
  funext q'
  rfl

/-- Shifting the identity is the identity. -/
theorem shift_E_identity (da db : Fin 6) :
    shift_E (ErrorVec.identity 72) da db = ErrorVec.identity 72 := by
  funext q'
  rfl

/-! ## Shift action as a `Fin 72` permutation (bijection) -/

/-- Negation in `Fin 6`: `neg_shift a = (6 - a) mod 6`. -/
def neg_shift (a : Fin 6) : Fin 6 := ⟨(6 - a.val) % 6, Nat.mod_lt _ (by omega)⟩

/-- Forward shift on qubits, derived from the inverse-shift used in `shift_E`. -/
def shift_q_fwd (q : Fin 72) (da db : Fin 6) : Fin 72 :=
  shift_q q (neg_shift da) (neg_shift db)

/-- `shift_q_fwd` is a left-inverse of `shift_q`: shifting forward then back is
    the identity on qubits. Verified by `native_decide` over 2,592 cases. -/
theorem shift_q_fwd_left_inv :
    ∀ (da db : Fin 6) (q : Fin 72),
      shift_q (shift_q_fwd q da db) da db = q := by
  native_decide

/-- `shift_q_fwd` is a right-inverse of `shift_q`: shifting back then forward is
    the identity on qubits. -/
theorem shift_q_fwd_right_inv :
    ∀ (da db : Fin 6) (q : Fin 72),
      shift_q_fwd (shift_q q da db) da db = q := by
  native_decide

/-- The Z₆×Z₆ shift action on qubits is a `Fin 72` permutation
    (Equiv) — combines the left- and right-inverse lemmas into a
    full bijection. This is the structural object that powers the
    orbit-reduction lemma (parity is invariant under simultaneous
    bijective substitution). -/
def shift_q_equiv (da db : Fin 6) : Fin 72 ≃ Fin 72 where
  toFun q := shift_q q da db
  invFun q := shift_q_fwd q da db
  left_inv q := shift_q_fwd_right_inv da db q
  right_inv q := shift_q_fwd_left_inv da db q

/-- `shift_E e` evaluated at `shift_q q` equals `e` at `q`. This is
    the fundamental defining property of the shift action. -/
theorem shift_E_apply_shift_q (e : ErrorVec 72) (da db : Fin 6) (q : Fin 72) :
    shift_E e da db (shift_q q da db) = e q := by
  have h : shift_E e da db (shift_q q da db) =
           e (shift_q_fwd (shift_q q da db) da db) := rfl
  rw [h]
  congr 1
  exact shift_q_fwd_right_inv da db q

/-- **Parity is invariant under simultaneous shift of both arguments.**
    A structural lemma: `parity` counts qubits where two ErrorVecs
    anticommute; under a qubit permutation (here `shift_q_equiv`) the
    cardinality is preserved.

    This is the key building block for `bb_se_isSuccess` shift-invariance
    and hence the orbit-reduction lemma. Discharged structurally, no
    `native_decide` over ErrorVec 72 needed. -/
theorem parity_shift_invariant (s e : ErrorVec 72) (da db : Fin 6) :
    ErrorVec.parity (shift_E s da db) (shift_E e da db) = ErrorVec.parity s e := by
  unfold ErrorVec.parity
  congr 1
  let σ : Fin 72 ≃ Fin 72 := shift_q_equiv da db
  -- LHS filter set = image of RHS filter set under σ
  have h_eq : (Finset.univ.filter fun i : Fin 72 =>
                 ErrorVec.Pauli.anticommutes (shift_E s da db i)
                                              (shift_E e da db i)) =
              (Finset.univ.filter fun j : Fin 72 =>
                 ErrorVec.Pauli.anticommutes (s j) (e j)).image σ := by
    ext i
    simp only [Finset.mem_filter, Finset.mem_univ, true_and, Finset.mem_image]
    constructor
    · intro h
      refine ⟨σ.symm i, ?_, σ.right_inv i⟩
      -- shift_E s da db i = s (σ.symm i) by definition; same for e.
      have hs : shift_E s da db i = s (σ.symm i) := rfl
      have he : shift_E e da db i = e (σ.symm i) := rfl
      rw [hs, he] at h
      exact h
    · rintro ⟨j, hj, rfl⟩
      have hs : shift_E s da db (σ j) = s j := shift_E_apply_shift_q s da db j
      have he : shift_E e da db (σ j) = e j := shift_E_apply_shift_q e da db j
      show ErrorVec.Pauli.anticommutes (shift_E s da db (σ j))
                                        (shift_E e da db (σ j))
      rw [hs, he]; exact hj
  rw [h_eq, Finset.card_image_of_injective _ σ.injective]

/-! ## Stab-parity shift-invariance

For any `E` and any shift `(da, db)`: "all 72 stab parities zero on
`shift_E E`" is equivalent to "all 72 stab parities zero on `E`".

Proof: combine `parity_shift_invariant` with `bb_stabilizers_shift_closed`
(which gives a bijection on stab indices under shift). -/

/-- The "inverse" direction of stab shift-closure: every stab is the
    shift-image of some other stab. Decidable by `native_decide`. -/
theorem bb_stabilizers_shift_closed_inv :
    ∀ (i : Fin 72) (da db : Fin 6),
      ∃ j : Fin 72, shift_E (bb_stabilizers j) da db = bb_stabilizers i := by
  native_decide

/-- **All stab parities zero is preserved under shift.** -/
theorem all_stab_parity_zero_shift_inv (E : ErrorVec 72) (da db : Fin 6) :
    (∀ i : Fin 72, ErrorVec.parity (bb_stabilizers i) E = false) →
    (∀ i : Fin 72, ErrorVec.parity (bb_stabilizers i) (shift_E E da db) = false) := by
  intro h_zero i
  -- Find j such that shift_E (stab j) = stab i.
  obtain ⟨j, hj⟩ := bb_stabilizers_shift_closed_inv i da db
  -- parity(stab i, shift_E E) = parity(shift_E (stab j), shift_E E) = parity(stab j, E) = false
  rw [← hj]
  rw [parity_shift_invariant]
  exact h_zero j

/-! ## Shift-equivariance of the stabiliser set

The X-stabs (and Z-stabs) of BB72 are invariant as a SET under
Z₆×Z₆ shift: shifting any stabiliser by (da, db) yields another
stabiliser in the same set. Decidable, discharged by `native_decide`. -/

/-- **Stabilisers are shift-closed.** For each stab `i` and shift `(da, db)`,
    there exists an index `j` such that `shift_E (bb_stabilizers i) da db
    = bb_stabilizers j`. Decidable: 72 stabs × 36 shifts × 72 candidate
    matches = ~187 k checks. -/
theorem bb_stabilizers_shift_closed :
    ∀ (i : Fin 72) (da db : Fin 6),
      ∃ j : Fin 72, shift_E (bb_stabilizers i) da db = bb_stabilizers j := by
  native_decide

/-! ## Shift-equivariance of L_Z cosets (the right statement)

The L_Z basis vectors are NOT exactly equal under shift (the
exact-equality version is `native_decide`-refuted). Instead, each
shifted L_Z basis vector decomposes as

    `shift_E (LZ_i) = (Σ_j M[i,j] · LZ_j) + (Z-stab combination)`

where `M : Fin 6 × Fin 6 → Matrix (Fin 12) (Fin 12) (Fin 2)` is the
"L_Z coset action" of the shift `(da, db)`.

**Empirically (Python, `notes/check_lz_parity_shift.py`)**: M is
**invertible over F₂ for all 36 shifts**. This is the structural fact
that powers the orbit-reduction lemma:

  * For X-only `E` with zero Z-syndrome (= our chain-XOR success
    candidates), `parity(LZ_j, shift_E E)` decomposes as
    `Σ_i M⁻¹[j,i] · parity(LZ_i, E)` (Z-stab combinations contribute 0
    parity to X-only errors when zero Z-syndrome).
  * Since `M⁻¹` is also invertible (over F₂), the predicate "∃ j,
    parity(LZ_j, _) = 1" is shift-invariant.
  * Combined with the X- and Z-stab shift-closure (above), this gives
    `bb_se_isSuccess (shift_E E da db) = bb_se_isSuccess E` for X-only
    `E` with zero Z-syndrome.

**Formalising in Lean** would require:
  1. Defining the 36 explicit `M` matrices (12×12 F₂, ~5k entries).
  2. Proving each is invertible via `native_decide` over precomputed
     determinants/inverses.
  3. Proving `parity(LZ_j, shift_E E) = Σ_i M⁻¹[j,i] · parity(LZ_i, E)`
     via Z-stab parity decomposition. This needs a parity-bilinearity
     lemma and the structural shift-equivariance of `parity` (proved
     below as `parity_shift_invariant`).

We provide the structural building block `parity_shift_invariant`;
the full L_Z coset orbit-reduction lemma is left as future work
(realistic, ~1 day of Lean engineering). -/

-- Note: the statement
--   ∀ i da db, ∃ j, shift_E (bb_logicalZ_basis i) da db = bb_logicalZ_basis j
-- is FALSE. Empirical Python verification shows the coset-level
-- statement (with invertible 12×12 F₂ action matrix) IS true.

/-! ## Mech indexing (used in both this file and `BB72SEChainCheck.lean`)

Each "X-mech" is either a Type-0 X at one of 72 qubits, or one of 180
SE hooks — total 252 mechs. -/

/-- Index `i : Fin 252`:
    * `i.val < 72`: Type-0 X mech at qubit `i.val`.
    * `i.val ≥ 72`: SE X-hook number `i.val - 72`. -/
def bb_se_xMech (i : Fin 252) : ErrorVec 72 :=
  if h : i.val < 72 then
    ErrorVec.update (ErrorVec.identity 72) ⟨i.val, by omega⟩ .X
  else
    bb_se_allHooks.getD (i.val - 72) (ErrorVec.identity 72)

/-! ## Trust-boundary status

| k | chain count | discharge status | Lean cost |
|---|---|---|---|
| 1 | 252 | ✅ `BB72SEChainCheck.bb_se_chain_1_no_attack` | trivial |
| 2 | 63 k | ✅ `BB72SEChainCheck.bb_se_chain_2_no_attack` | ~15 min `native_decide` |
| 3 | 16 M (or ~73 k orbit-reduced) | 🌐 axiom | needs orbit reduction |
| 4 | 4 G (or ~4.6 M orbit-reduced) | 🌐 axiom | needs orbit reduction |
| 5 | 1 T (or ~226 M orbit-reduced) | 🌐 axiom | needs invariant |

The combined axiom `bb_NZ_SE_no_X_attack_below_6` (below) covers all
k=1..5 simultaneously. The chain-by-chain theorems live in
`BB72SEChainCheck.lean` (split out so the slow `native_decide` doesn't
re-run when this file is edited).

To formally split the axiom (so the Lean theorems literally REPLACE
the k=1, 2 portions) requires a `reachableE → chainXOR` reduction
lemma (proves every reachable E is a chain XOR of mechs) — sketched in
the "Open path" section below.

## Open path

**Already proved structurally in this file:**

  1a. ✅ `shift_q : Fin 72 → Fin 6 → Fin 6 → Fin 72` (Z₆×Z₆ qubit action).
  1b. ✅ `shift_q_fwd_left_inv` and `shift_q_fwd_right_inv` (`shift_q` is
      a bijection — `native_decide`, 2,592 cases).
  1c. ✅ `shift_q_equiv : Fin 72 ≃ Fin 72` (the bijection as `Equiv`).
  1d. ✅ `parity_shift_invariant` (parity invariant under simultaneous
      qubit shift — STRUCTURAL, no `native_decide` over `ErrorVec 72`).
  1e. ✅ `bb_se_allHooks_shift_closed` (hooks closed as a set).
  1f. ✅ `bb_stabilizers_shift_closed` and `bb_stabilizers_shift_closed_inv`
      (stabs closed bijectively as a set).
  1g. ✅ `all_stab_parity_zero_shift_inv` (combining 1d+1f: zero-Z-syndrome
      predicate is shift-invariant).

**Remaining to eliminate `bb_NZ_SE_no_X_attack_below_6`:**

  2. **L_Z coset shift-invariance for the `any-parity-1` predicate.**
     Verified empirically (Python `notes/check_lz_parity_shift.py`): the
     12×12 F₂ matrix `M[da,db]` describing shift action on L_Z cosets
     is invertible for all 36 shifts. To formalise:
       (a) Define the 36 explicit `M[da,db]` matrices.
       (b) Prove invertibility via `native_decide`.
       (c) Prove `parity(LZ_j, shift_E E) = Σ_i M⁻¹[j,i] · parity(LZ_i, E)`
           for X-only `E` with zero Z-syndrome (uses `parity_shift_invariant`
           and the fact that Z-stab combos have zero parity vs X-only `E`
           when E's Z-syndrome is zero).
       (d) Combine (b)+(c): "∃ j, parity(LZ_j, E) = true" is preserved.

  3. **Combine 1g + 2 into `bb_se_isSuccess_shift_inv`** (X-only chain
     XORs).

  4. **Orbit-reduced static-DEM check.** Restate the axiom over
     Z₆×Z₆-orbit chain representatives — gives a 36× reduction in
     verification surface.

  5. **Find an algebraic invariant on the 5 base hooks.** Each base
     hook is a polynomial pair `(α_i, β_i) ∈ R²` where
     `R = F₂[x,y]/(x⁶-1, y⁶-1)`. The 5 base hooks are:

         H_0:  (y² + x³,        y³ + x + x²)    -- length 5
         H_1:  (x³,             y³ + x + x²)    -- length 4
         H_2:  (0,              y³ + x + x²)    -- length 3
         H_3:  (0,              x + x²)         -- length 2
         H_4:  (0,              x²)             -- length 1

     A chain XOR is `Σ x^{a_i} y^{b_i} (α_{m_i}, β_{m_i})`, with at most
     5 terms and shifts `(a_i, b_i) ∈ Z₆ × Z₆`. The "no successful
     attack" condition becomes: this sum never lies in
     `(ker Z-syndrome) \ (HX)-image` for ≤5-fold sums.

     **This is a concrete polynomial-ring statement.** Whether it
     admits a closed-form proof (without enumeration) is open. -/

end QStab.Paper.BB72SEInstance
