import QStab.QHL.CodeDerivation

/-! # Recursive repetition code in the code-level assertion language

This module is a deliberately small recursive-code test for `CodeLang`.

The code family is the usual `Z_i Z_{i+1}` repetition stabilizer code:

* row `0` of distance `d` is `Z Z I ... I`;
* row `k+1` of distance `d+1` is row `k` of distance `d`, shifted right.

As a full quantum stabilizer code this family has distance `1`, because a
single endpoint `Z` is a nontrivial logical operator.  The protected `X`
logical has distance `d`.  We therefore prove the syntactic `X`-distance
statement and also check the weight-one `Z` logical counterexample.
-/

namespace QHL.CodeLang.Repetition

open QHL.CodeLang

set_option maxRecDepth 32768
set_option maxHeartbeats 1200000

/-! ## Recursive code syntax

The code family below is a single AST object.  The familiar equations
`ZZ...`, shift-right, and recursive predecessor are only the fold/unfold
reading of this object; they are not separate definitions.
-/

private def q : Term 3 .nat := C.Entry.q
private def k : Term 3 .nat := C.Entry.k
private def d : Term 3 .nat := C.Entry.d

def isZeroOrOne {arity : Nat} (x : Term arity .nat) : Term arity .bool :=
  .or (.eqNat x (.natLit 0)) (.eqNat x (.natLit 1))

/-- The unique recursive entry AST for the repetition-code family.

In concrete syntax, this is the one program:

```text
fun d k q =>
  if k = 0 then
    if q = 0 or q = 1 then Z else I
  else
    if q = 0 then I
    else rec(d - 1, k - 1)[q - 1]
```

All generated rows are obtained by evaluating this one AST with different
`d`, `k`, and `q`; there are no separate row constructors.
-/
def repEntryAST : Term 3 .pauli :=
  .ite (.eqNat k (.natLit 0))
    (.ite (isZeroOrOne q) (.pauliLit Pauli.Z) (.pauliLit Pauli.I))
    (.ite (.eqNat q (.natLit 0))
      (.pauliLit Pauli.I)
      (.stabAt
        (.recCall (.sub d (.natLit 1)) (.sub k (.natLit 1)))
        (.sub q (.natLit 1))))

/-- The canonical recursive repetition-code AST of type `Nat -> Nat -> Stabilizer`. -/
def repCodeAST : Term 2 .stab :=
  .stabLam repEntryAST

/-- Recursive repetition-code generator.  This structure just names the single
canonical AST above as a `CodeFn`. -/
def code : CodeFn where
  body := repCodeAST

/-! ## Derived syntax for X-errors and generated rows -/

def orList {arity : Nat} : List (Formula arity) -> Formula arity
  | [] => .bot
  | A :: rest => rest.foldl (fun acc B => .or acc B) A

def andList {arity : Nat} : List (Formula arity) -> Formula arity
  | [] => .top
  | A :: rest => rest.foldl (fun acc B => .and acc B) A

def bitAt {arity : Nat} (idx : Term arity .nat) (slot : Nat) : Term arity .nat :=
  .mod (.div idx (.natLit (2 ^ slot))) (.natLit 2)

def xStringOfNatEntry {arity : Nat} (idx : Term arity .nat) :
    Nat -> Term (arity + 1) .pauli
  | 0 => .pauliLit Pauli.I
  | slots + 1 =>
      .ite (.eqNat Formula.qVar (.natLit slots))
        (.ite (.eqNat (bitAt idx.weaken slots) (.natLit 1))
          (.pauliLit Pauli.X)
          (.pauliLit Pauli.I))
        (xStringOfNatEntry idx slots)

def xStringOfNat {arity : Nat} (n : Nat) (idx : Term arity .nat) :
    Term arity .stab :=
  .stabLam (xStringOfNatEntry idx n)

def allXEntry : Nat -> Term 1 .pauli
  | 0 => .pauliLit Pauli.I
  | slots + 1 =>
      .ite (.eqNat Formula.qVar (.natLit slots))
        (.pauliLit Pauli.X)
        (allXEntry slots)

def allX (n : Nat) : Term 0 .stab :=
  .stabLam (allXEntry n)

def endpointZ : Term 0 .stab :=
  .stabLam <|
    .ite (.eqNat Formula.qVar (.natLit 0))
      (.pauliLit Pauli.Z)
      (.pauliLit Pauli.I)

def rowsForMask {arity : Nat} (numRows mask : Nat) : List (Term arity .nat) :=
  (List.range numRows).filterMap fun row =>
    if (mask / (2 ^ row)) % 2 = 1 then
      some (.natLit row)
    else
      none

/-- Membership in the stabilizer group generated by the `d - 1` recursive rows.
This is a finite disjunction of explicit row-product equalities, not a
membership primitive. -/
def generatedBySomeRows {arity : Nat} (dist : Nat) (E : Term arity .stab) :
    Formula arity :=
  orList <|
    (List.range (2 ^ (dist - 1))).map fun mask =>
      Formula.generatedByRowsUpTo (.natLit dist) E (.natLit dist)
        (rowsForMask (dist - 1) mask)

def normalizesCodeAt {arity : Nat}
    (n numStab dist : Term arity .nat) (E : Term arity .stab) : Formula arity :=
  .allNatLt numStab <|
    .commutesUpTo n.weaken
      (Formula.codeRow dist.weaken (.var ⟨0, Nat.succ_pos arity⟩))
      E.weaken

/-! ## Fold/unfold assertion for the recursive AST -/

def repUnfoldedEntryAt {arity : Nat}
    (dist row slot : Term arity .nat) : Term arity .pauli :=
  .ite (.eqNat row (.natLit 0))
    (.ite (isZeroOrOne slot) (.pauliLit Pauli.Z) (.pauliLit Pauli.I))
    (.ite (.eqNat slot (.natLit 0))
      (.pauliLit Pauli.I)
      (.stabAt
        (.recCall (.sub dist (.natLit 1)) (.sub row (.natLit 1)))
        (.sub slot (.natLit 1))))

/-- Object-language fold/unfold law for the unique repetition AST at distance
`dist`: every generated entry agrees with one syntactic unfold of `repEntryAST`.
-/
def repFoldUnfoldF (dist : Nat) : Formula 0 :=
  .allNatLt (.natLit (dist - 1)) <|
    .allNatLt (Term.natLit dist).weaken <|
      let slot : Term 2 .nat := .var ⟨0, by decide⟩
      let row : Term 2 .nat := .var ⟨1, by decide⟩
      .eqPauli
        (.stabAt (Formula.codeRow (.natLit dist) row) slot)
        (repUnfoldedEntryAt (.natLit dist) row slot)

def repEntryAt {arity : Nat}
    (dist row slot : Term arity .nat) : Term arity .pauli :=
  .stabAt (Formula.codeRow dist row) slot

def repBoundaryRowF (dist : Nat) : Formula 0 :=
  .allNatLt (.natLit dist) <|
    let slot : Term 1 .nat := .var ⟨0, by decide⟩
    .eqPauli
      (repEntryAt (.natLit dist) (.natLit 0) slot)
      (.ite (isZeroOrOne slot) (.pauliLit Pauli.Z) (.pauliLit Pauli.I))

/-- Tail-shift equation used by the inductive reading of the recursive AST:
`Rep(d+1,k+1,q+1) = Rep(d,k,q)`. -/
def repTailShiftF (dist : Nat) : Formula 0 :=
  .allNatLt (.natLit (dist - 1)) <|
    .allNatLt (Term.natLit dist).weaken <|
      let slot : Term 2 .nat := .var ⟨0, by decide⟩
      let row : Term 2 .nat := .var ⟨1, by decide⟩
      .eqPauli
        (repEntryAt (.natLit (dist + 1)) (.add row (.natLit 1)) (.add slot (.natLit 1)))
        (repEntryAt (.natLit dist) row slot)

def repSuccFoldFromPrevF (dist : Nat) : Formula 0 :=
  .imp
    (.and (repFoldUnfoldF dist)
      (.and (repBoundaryRowF (dist + 1)) (repTailShiftF dist)))
    (repFoldUnfoldF (dist + 1))

def adjacentBitsEqualAt {arity : Nat} (dist : Nat) (idx : Term arity .nat) :
    Formula arity :=
  andList <|
    (List.range (dist - 1)).map fun slot =>
      .eqNat (bitAt idx slot) (bitAt idx (slot + 1))

def allBitsEqualAt {arity : Nat} (dist : Nat) (idx : Term arity .nat) :
    Formula arity :=
  andList <|
    (List.range dist).map fun slot =>
      .eqNat (bitAt idx slot) (bitAt idx 0)

/-- Commuting with every `Z_i Z_{i+1}` check forces adjacent `X` bits to agree. -/
def xNormalizerAdjacentBitsF (dist : Nat) : Formula 0 :=
  .allNatLt (.natLit (2 ^ dist)) <|
    let idx : Term 1 .nat := .var ⟨0, by decide⟩
    let E : Term 1 .stab := xStringOfNat dist idx
    .imp
      (normalizesCodeAt (.natLit dist) (.natLit (dist - 1)) (.natLit dist) E)
      (adjacentBitsEqualAt dist idx)

/-- Finite-chain induction over adjacent equalities: all `X` bits equal bit zero. -/
def xNormalizerAllBitsEqualF (dist : Nat) : Formula 0 :=
  .allNatLt (.natLit (2 ^ dist)) <|
    let idx : Term 1 .nat := .var ⟨0, by decide⟩
    .imp (adjacentBitsEqualAt dist idx) (allBitsEqualAt dist idx)

/-- If all `X` bits are equal and the weight is below the full string, the
only low-weight normalizer is the identity, witnessed by the empty row product.
-/
def xAllEqualLowWeightGeneratedF (dist : Nat) : Formula 0 :=
  .allNatLt (.natLit (2 ^ dist)) <|
    let idx : Term 1 .nat := .var ⟨0, by decide⟩
    let E : Term 1 .stab := xStringOfNat dist idx
    .imp
      (.and (allBitsEqualAt dist idx)
        (.weightLe (.natLit dist) E (.natLit (dist - 1))))
      (generatedBySomeRows dist E)

def xAdjacentFromFoldF (dist : Nat) : Formula 0 :=
  .imp (repFoldUnfoldF dist) (xNormalizerAdjacentBitsF dist)

def xAllBitsFromAdjacentF (dist : Nat) : Formula 0 :=
  .imp (xNormalizerAdjacentBitsF dist) (xNormalizerAllBitsEqualF dist)

/-! ## Repetition X-distance formulas -/

/-- Lower bound for the protected `X` direction:
every `X`-only string of weight at most `d - 1` that normalizes the recursive
code is generated by stabilizer rows. -/
def xDistanceLowerF (dist : Nat) : Formula 0 :=
  .allNatLt (.natLit (2 ^ dist)) <|
    let idx : Term 1 .nat := .var ⟨0, by decide⟩
    let E : Term 1 .stab := xStringOfNat dist idx
    .imp
      (.and
        (.weightLe (.natLit dist) E (.natLit (dist - 1)))
        (normalizesCodeAt (.natLit dist) (.natLit (dist - 1)) (.natLit dist) E))
      (generatedBySomeRows dist E)

def xLowerFromAllBitsF (dist : Nat) : Formula 0 :=
  .imp
    (.and (xNormalizerAllBitsEqualF dist) (xAllEqualLowWeightGeneratedF dist))
    (xDistanceLowerF dist)

/-- Upper bound: the all-`X` string has weight at most `d`, normalizes the code,
is not generated by stabilizer rows, and anticommutes with endpoint `Z`. -/
def xDistanceUpperF (dist : Nat) : Formula 0 :=
  .and (.weightLe (.natLit dist) (allX dist) (.natLit dist)) <|
    .and (normalizesCodeAt (.natLit dist) (.natLit (dist - 1)) (.natLit dist)
        (allX dist)) <|
      .and (.not (generatedBySomeRows dist (allX dist))) <|
        Formula.anticommutesUpTo (.natLit dist) (allX dist) endpointZ

def xDistanceExactF (dist : Nat) : Formula 0 :=
  .and (xDistanceLowerF dist) (xDistanceUpperF dist)

def xDistanceMotiveF (dist : Nat) : Formula 0 :=
  .and (repFoldUnfoldF dist) (xDistanceExactF dist)

/-- Full quantum-distance caveat: endpoint `Z` is a nontrivial weight-one
logical.  This formula is true, so the usual repetition code does not have
full Pauli stabilizer distance `d` for `d > 1`. -/
def endpointZLogicalF (dist : Nat) : Formula 0 :=
  .and (.weightLe (.natLit dist) endpointZ (.natLit 1)) <|
    .and (normalizesCodeAt (.natLit dist) (.natLit (dist - 1)) (.natLit dist)
        endpointZ) <|
      .not (generatedBySomeRows dist endpointZ)

/-! ## Checked syntactic derivations -/

def derivationOf? (dist : Nat) (A : Formula 0) : Option (Formula.Deriv A true) :=
  Formula.deriveTrue? code.body (dist + 1) Env.empty A

def derivationChecked (dist : Nat) (A : Formula 0) : Bool :=
  match derivationOf? dist A with
  | some D => D.check code.body (dist + 1) Env.empty
  | none => false

def xDistanceLowerDerivationChecked (dist : Nat) : Bool :=
  derivationChecked dist (xDistanceLowerF dist)

def xDistanceUpperDerivationChecked (dist : Nat) : Bool :=
  derivationChecked dist (xDistanceUpperF dist)

def xDistanceExactDerivationChecked (dist : Nat) : Bool :=
  derivationChecked dist (xDistanceExactF dist)

def repFoldUnfoldDerivationChecked (dist : Nat) : Bool :=
  derivationChecked dist (repFoldUnfoldF dist)

def endpointZLogicalDerivationChecked (dist : Nat) : Bool :=
  derivationChecked dist (endpointZLogicalF dist)

/-! ## Inductive proof over distance

This is the object-level induction proof:

```text
  D_base : P(1)
  D_step(d) : D(P(d)) -> D(P(d+1))
----------------------------------- NatInd
  forall d >= 1. P(d)
```

where `P(d)` is `repFoldUnfoldF d /\ xDistanceExactF d`.  The step below is
not a single closed implication.  It is a named derivation package:

* `foldSuccFromPrev` derives the next fold/unfold law from the previous one
  plus the boundary and tail-shift equations;
* `adjacentFromFold` derives adjacent-bit equalities from the next fold/unfold
  law;
* `allBitsFromAdjacent` performs the finite-chain induction over adjacent
  equalities;
* `lowerFromAllBits` assembles the lower-bound formula from all-bits-equal and
  low-weight-generated lemmas;
* `upperSucc` is the explicit all-`X` upper witness.
-/

structure XDistanceStepDerivation (dist : Nat) where
  boundarySucc : Formula.Deriv (repBoundaryRowF (dist + 1)) true
  tailShift : Formula.Deriv (repTailShiftF dist) true
  foldSuccFromPrev : Formula.Deriv (repSuccFoldFromPrevF dist) true
  adjacentFromFold : Formula.Deriv (xAdjacentFromFoldF (dist + 1)) true
  allBitsFromAdjacent : Formula.Deriv (xAllBitsFromAdjacentF (dist + 1)) true
  lowWeightGenerated : Formula.Deriv (xAllEqualLowWeightGeneratedF (dist + 1)) true
  lowerFromAllBits : Formula.Deriv (xLowerFromAllBitsF (dist + 1)) true
  upperSucc : Formula.Deriv (xDistanceUpperF (dist + 1)) true

namespace XDistanceStepDerivation

def foldSucc {dist : Nat} (S : XDistanceStepDerivation dist)
    (prev : Formula.Deriv (xDistanceMotiveF dist) true) :
    Formula.Deriv (repFoldUnfoldF (dist + 1)) true :=
  let prevFold : Formula.Deriv (repFoldUnfoldF dist) true := .andElimLeft prev
  let foldAntecedent :
      Formula.Deriv
        (.and (repFoldUnfoldF dist)
          (.and (repBoundaryRowF (dist + 1)) (repTailShiftF dist))) true :=
    .andTrue prevFold (.andTrue S.boundarySucc S.tailShift)
  .mp S.foldSuccFromPrev foldAntecedent

def lowerSucc {dist : Nat} (S : XDistanceStepDerivation dist)
    (fold : Formula.Deriv (repFoldUnfoldF (dist + 1)) true) :
    Formula.Deriv (xDistanceLowerF (dist + 1)) true :=
  let adjacent : Formula.Deriv (xNormalizerAdjacentBitsF (dist + 1)) true :=
    .mp S.adjacentFromFold fold
  let allBits : Formula.Deriv (xNormalizerAllBitsEqualF (dist + 1)) true :=
    .mp S.allBitsFromAdjacent adjacent
  let lowerAntecedent :
      Formula.Deriv
        (.and (xNormalizerAllBitsEqualF (dist + 1))
          (xAllEqualLowWeightGeneratedF (dist + 1))) true :=
    .andTrue allBits S.lowWeightGenerated
  .mp S.lowerFromAllBits lowerAntecedent

def toMotiveDeriv {dist : Nat} (S : XDistanceStepDerivation dist)
    (prev : Formula.Deriv (xDistanceMotiveF dist) true) :
    Formula.Deriv (xDistanceMotiveF (dist + 1)) true :=
  let fold := S.foldSucc prev
  let lower := S.lowerSucc fold
  .andTrue fold (.andTrue lower S.upperSucc)

def check {dist : Nat} (S : XDistanceStepDerivation dist) : Bool :=
  S.boundarySucc.check code.body (dist + 2) Env.empty &&
    S.tailShift.check code.body (dist + 2) Env.empty &&
    S.foldSuccFromPrev.check code.body (dist + 2) Env.empty &&
    S.adjacentFromFold.check code.body (dist + 2) Env.empty &&
    S.allBitsFromAdjacent.check code.body (dist + 2) Env.empty &&
    S.lowWeightGenerated.check code.body (dist + 2) Env.empty &&
    S.lowerFromAllBits.check code.body (dist + 2) Env.empty &&
    S.upperSucc.check code.body (dist + 2) Env.empty

def size {dist : Nat} (S : XDistanceStepDerivation dist) : Nat :=
  S.boundarySucc.size + S.tailShift.size + S.foldSuccFromPrev.size +
    S.adjacentFromFold.size + S.allBitsFromAdjacent.size +
    S.lowWeightGenerated.size + S.lowerFromAllBits.size + S.upperSucc.size

end XDistanceStepDerivation

def xDistanceStepDerivation? (dist : Nat) :
    Option (XDistanceStepDerivation dist) := do
  let boundarySucc <- derivationOf? (dist + 1) (repBoundaryRowF (dist + 1))
  let tailShift <- derivationOf? (dist + 1) (repTailShiftF dist)
  let foldSuccFromPrev <- derivationOf? (dist + 1) (repSuccFoldFromPrevF dist)
  let adjacentFromFold <- derivationOf? (dist + 1) (xAdjacentFromFoldF (dist + 1))
  let allBitsFromAdjacent <- derivationOf? (dist + 1) (xAllBitsFromAdjacentF (dist + 1))
  let lowWeightGenerated <- derivationOf? (dist + 1) (xAllEqualLowWeightGeneratedF (dist + 1))
  let lowerFromAllBits <- derivationOf? (dist + 1) (xLowerFromAllBitsF (dist + 1))
  let upperSucc <- derivationOf? (dist + 1) (xDistanceUpperF (dist + 1))
  some {
    boundarySucc := boundarySucc
    tailShift := tailShift
    foldSuccFromPrev := foldSuccFromPrev
    adjacentFromFold := adjacentFromFold
    allBitsFromAdjacent := allBitsFromAdjacent
    lowWeightGenerated := lowWeightGenerated
    lowerFromAllBits := lowerFromAllBits
    upperSucc := upperSucc
  }

def xDistanceStepDerivationChecked (dist : Nat) : Bool :=
  match xDistanceStepDerivation? dist with
  | some S => S.check
  | none => false

def xDistanceInductionDerivation? :
    Option (Formula.NatOneInductionDerivation xDistanceMotiveF) := do
  let base <- derivationOf? 1 (xDistanceMotiveF 1)
  some {
    base := base
    step := fun n prev => do
      let S <- xDistanceStepDerivation? n
      some (S.toMotiveDeriv prev)
  }

def xDistanceInductiveAt? (offset : Nat) :
    Option (Formula.Deriv (xDistanceExactF (offset + 1)) true) := do
  let D <- xDistanceInductionDerivation?
  let motiveProof <- D.instantiate? offset
  some (.andElimRight motiveProof)

def xDistanceMotiveInductiveAt? (offset : Nat) :
    Option (Formula.Deriv (xDistanceMotiveF (offset + 1)) true) := do
  let D <- xDistanceInductionDerivation?
  D.instantiate? offset

def xDistanceInductionCheckedAtOffset (offset : Nat) : Bool :=
  match xDistanceInductiveAt? offset with
  | some D => D.check code.body (offset + 2) Env.empty
  | none => false

def xDistanceInductionCheckedAtDist (dist : Nat) : Bool :=
  match dist with
  | 0 => false
  | offset + 1 => xDistanceInductionCheckedAtOffset offset

def xDistanceInductionInstantiatedSize? (offset : Nat) : Option Nat := do
  match xDistanceInductiveAt? offset with
  | some proof => some proof.size
  | none => none

/-! ## Generated views for review -/

def evalRowString (dist row : Nat) : String :=
  let entries := (List.range dist).map fun q => code.evalEntry? (dist + 1) dist row q
  entries.foldr
    (fun p acc =>
      (match p with
      | some Pauli.I => "I"
      | some Pauli.X => "X"
      | some Pauli.Y => "Y"
      | some Pauli.Z => "Z"
      | none => "?") ++ acc)
    ""

def generatedRows (dist : Nat) : List String :=
  (List.range (dist - 1)).map fun row => evalRowString dist row

/-- info: [] -/
#guard_msgs in
#eval generatedRows 1

/-- info: ["ZZI", "IZZ"] -/
#guard_msgs in
#eval generatedRows 3

/-- info: ["ZZIII", "IZZII", "IIZZI", "IIIZZ"] -/
#guard_msgs in
#eval generatedRows 5

/-- info: true -/
#guard_msgs in
#eval xDistanceExactDerivationChecked 1

/-- info: true -/
#guard_msgs in
#eval xDistanceExactDerivationChecked 3

/-- info: true -/
#guard_msgs in
#eval xDistanceExactDerivationChecked 5

/-- info: true -/
#guard_msgs in
#eval xDistanceExactDerivationChecked 7

/-- info: true -/
#guard_msgs in
#eval repFoldUnfoldDerivationChecked 1

/-- info: true -/
#guard_msgs in
#eval repFoldUnfoldDerivationChecked 3

/-- info: true -/
#guard_msgs in
#eval repFoldUnfoldDerivationChecked 5

/-- info: true -/
#guard_msgs in
#eval xDistanceStepDerivationChecked 1

/-- info: true -/
#guard_msgs in
#eval xDistanceStepDerivationChecked 3

/-- info: true -/
#guard_msgs in
#eval xDistanceStepDerivationChecked 5

/-- info: true -/
#guard_msgs in
#eval xDistanceInductionCheckedAtDist 1

/-- info: true -/
#guard_msgs in
#eval xDistanceInductionCheckedAtDist 3

/-- info: true -/
#guard_msgs in
#eval xDistanceInductionCheckedAtDist 5

/-- info: true -/
#guard_msgs in
#eval xDistanceInductionCheckedAtDist 7

/-- info: true -/
#guard_msgs in
#eval endpointZLogicalDerivationChecked 3

/-- info: true -/
#guard_msgs in
#eval endpointZLogicalDerivationChecked 5

#print axioms code
#print axioms xDistanceExactDerivationChecked
#print axioms xDistanceStepDerivationChecked
#print axioms xDistanceInductionDerivation?
#print axioms xDistanceInductionCheckedAtDist
#print axioms endpointZLogicalDerivationChecked

end QHL.CodeLang.Repetition
