import QStab.QHL.CodeAlgebra
import QStab.QHL.CodeDerivation

/-! # Five-qubit code in the code-level assertion language

This module is a fixed-code smoke test for the new `CodeLang` layer.  The code,
logical operators, and distance assertions below are all syntax built from the
small term/formula language.  The proof objects are checked by evaluating those
closed formulas; they do not import the older semantic five-qubit development.
-/

namespace QHL.CodeLang.FiveQubit

open QHL.CodeLang

set_option maxRecDepth 32768
set_option maxHeartbeats 800000

/-! ## Syntax builders -/

private def q : Term 3 .nat := C.Entry.q
private def k : Term 3 .nat := C.Entry.k

def pauliAt5 {arity : Nat} (q : Term arity .nat)
    (p0 p1 p2 p3 p4 : Pauli) : Term arity .pauli :=
  .ite (.eqNat q (.natLit 0)) (.pauliLit p0) <|
  .ite (.eqNat q (.natLit 1)) (.pauliLit p1) <|
  .ite (.eqNat q (.natLit 2)) (.pauliLit p2) <|
  .ite (.eqNat q (.natLit 3)) (.pauliLit p3) <|
  .ite (.eqNat q (.natLit 4)) (.pauliLit p4) <|
  .pauliLit Pauli.I

def row0 : Term 3 .pauli := pauliAt5 q Pauli.X Pauli.Z Pauli.Z Pauli.X Pauli.I
def row1 : Term 3 .pauli := pauliAt5 q Pauli.I Pauli.X Pauli.Z Pauli.Z Pauli.X
def row2 : Term 3 .pauli := pauliAt5 q Pauli.X Pauli.I Pauli.X Pauli.Z Pauli.Z
def row3 : Term 3 .pauli := pauliAt5 q Pauli.Z Pauli.X Pauli.I Pauli.X Pauli.Z

/-- The [[5,1,3]] code as `Nat -> Nat -> Stabilizer` syntax.

The distance argument is ignored because this is the fixed five-qubit base
case.  The row argument selects one of the four generators:
`XZZXI`, `IXZZX`, `XIXZZ`, `ZXIXZ`. -/
def code : CodeFn where
  body := .stabLam <|
    .ite (.eqNat k (.natLit 0)) row0 <|
    .ite (.eqNat k (.natLit 1)) row1 <|
    .ite (.eqNat k (.natLit 2)) row2 <|
    .ite (.eqNat k (.natLit 3)) row3 <|
    .pauliLit Pauli.I

def logicalX : Term 0 .stab :=
  .stabLam (.pauliLit Pauli.X)

def logicalZ : Term 0 .stab :=
  .stabLam (.pauliLit Pauli.Z)

/-! ## Finite Pauli-string enumeration syntax

For the fixed five-qubit code, every Pauli string is represented by a natural
number below `4^5 = 1024`, read as five base-4 digits:

`0 = I`, `1 = X`, `2 = Y`, `3 = Z`.

This is a derived encoding, not a new assertion primitive.
-/

def pauliOfDigit {arity : Nat} (digit : Term arity .nat) : Term arity .pauli :=
  .ite (.eqNat digit (.natLit 0)) (.pauliLit Pauli.I) <|
  .ite (.eqNat digit (.natLit 1)) (.pauliLit Pauli.X) <|
  .ite (.eqNat digit (.natLit 2)) (.pauliLit Pauli.Y) <|
  .pauliLit Pauli.Z

def digitAt {arity : Nat} (idx : Term arity .nat) (slot : Nat) : Term arity .nat :=
  .mod (.div idx (.natLit (4 ^ slot))) (.natLit 4)

def pauliString5OfNat {arity : Nat} (idx : Term arity .nat) : Term arity .stab :=
  .stabLam <|
    .ite (.eqNat Formula.qVar (.natLit 0)) (pauliOfDigit (digitAt idx.weaken 0)) <|
    .ite (.eqNat Formula.qVar (.natLit 1)) (pauliOfDigit (digitAt idx.weaken 1)) <|
    .ite (.eqNat Formula.qVar (.natLit 2)) (pauliOfDigit (digitAt idx.weaken 2)) <|
    .ite (.eqNat Formula.qVar (.natLit 3)) (pauliOfDigit (digitAt idx.weaken 3)) <|
    .ite (.eqNat Formula.qVar (.natLit 4)) (pauliOfDigit (digitAt idx.weaken 4)) <|
    .pauliLit Pauli.I

def normalizesCodeAt {arity : Nat}
    (n numStab d : Term arity .nat) (E : Term arity .stab) : Formula arity :=
  .allNatLt numStab <|
    .commutesUpTo n.weaken
      (Formula.codeRow d.weaken (.var ⟨0, Nat.succ_pos arity⟩))
      E.weaken

def commutesWithLogicalPairAt {arity : Nat}
    (n : Term arity .nat) (E LX LZ : Term arity .stab) : Formula arity :=
  .and (.commutesUpTo n E LX) (.commutesUpTo n E LZ)

def rowsForMask {arity : Nat} (mask : Nat) : List (Term arity .nat) :=
  ([0, 1, 2, 3].filter fun row => (mask / (2 ^ row)) % 2 = 1).map
    (fun row => Term.natLit row)

def orList {arity : Nat} : List (Formula arity) -> Formula arity
  | [] => .bot
  | A :: rest =>
      rest.foldl (fun acc B => .or acc B) A

/-- Membership in the five-qubit stabilizer group, expanded as a finite
disjunction over the sixteen generated row products.  This is derived syntax:
each disjunct is `E = productRows(mask)`, not a primitive membership predicate.
-/
def generatedBySomeRows5 {arity : Nat} (E : Term arity .stab) : Formula arity :=
  orList <|
    (List.range 16).map fun mask =>
      Formula.generatedByRowsUpTo (.natLit 5) E (.natLit 5) (rowsForMask mask)

/-! ## Five-qubit assertions -/

def rowsCommuteF : Formula 0 :=
  Formula.codeRowsCommuteUpTo (.natLit 5) (.natLit 4) (.natLit 5)

def logicalPairF : Formula 0 :=
  Formula.logicalPairCandidateUpTo (.natLit 5) (.natLit 4) (.natLit 5)
    logicalX logicalZ

/-- No Pauli string of weight at most two is a nontrivial logical operator:
    any such normalizer must be generated by the four stabilizer rows. -/
def distanceLowerF : Formula 0 :=
  .allNatLt (.natLit 1024) <|
    let idx : Term 1 .nat := .var ⟨0, by decide⟩
    let E : Term 1 .stab := pauliString5OfNat idx
    .imp
      (.and
        (.weightLe (.natLit 5) E (.natLit 2))
        (normalizesCodeAt (.natLit 5) (.natLit 4) (.natLit 5) E))
      (generatedBySomeRows5 E)

/-- `IIXYX`, encoded as base-4 digits `[I,I,X,Y,X]`, is a weight-three
    nontrivial logical operator. -/
def weightThreeLogical : Term 0 .stab :=
  .stabLam (pauliAt5 Formula.qVar Pauli.I Pauli.I Pauli.X Pauli.Y Pauli.X)

def distanceUpperF : Formula 0 :=
  .and (.weightLe (.natLit 5) weightThreeLogical (.natLit 3)) <|
    .and (normalizesCodeAt (.natLit 5) (.natLit 4) (.natLit 5) weightThreeLogical) <|
      .and
        (.not (generatedBySomeRows5 weightThreeLogical)) <|
        .and
          (Formula.anticommutesUpTo (.natLit 5) weightThreeLogical logicalX)
          (Formula.anticommutesUpTo (.natLit 5) weightThreeLogical logicalZ)

def exactDistanceThreeF : Formula 0 :=
  .and distanceLowerF distanceUpperF

/-! ## Closed syntactic checks

These are formula-level proof targets for the next kernel rule.  They are
already expressed completely in the assertion language and checked by the
executable evaluator below.  Turning the 1024-case distance lower bound into a
theorem requires a finite-enumeration derivation rule rather than raw `simp`
normalization.
-/

structure ClosedCheck where
  name : String
  formula : Formula 0

def ClosedCheck.run (C : ClosedCheck) : Bool :=
  Formula.check code.body 1 C.formula Env.empty

def rowsCommuteCheck : ClosedCheck where
  name := "five.rows_commute"
  formula := rowsCommuteF

def logicalPairCheck : ClosedCheck where
  name := "five.logical_pair"
  formula := logicalPairF

def distanceLowerCheck : ClosedCheck where
  name := "five.distance_lower_3"
  formula := distanceLowerF

def distanceUpperCheck : ClosedCheck where
  name := "five.distance_upper_3"
  formula := distanceUpperF

def exactDistanceThreeCheck : ClosedCheck where
  name := "five.exact_distance_3"
  formula := exactDistanceThreeF

/-! ## Syntactic derivations

The following objects are not extra semantic theorems.  They are derivation
trees in `Formula.Deriv`, built from:

* atomic formula leaves,
* boolean connective rules,
* bounded `allNatLt` rules.

The final `...DerivationChecked` values run the derivation verifier, so the
five-qubit result is now checked as a logical derivation rather than as one
flat formula evaluation.
-/

def derivationOf? (A : Formula 0) : Option (Formula.Deriv A true) :=
  Formula.deriveTrue? code.body 1 Env.empty A

def derivationChecked (A : Formula 0) : Bool :=
  match derivationOf? A with
  | some D => D.check code.body 1 Env.empty
  | none => false

def rowsCommuteDerivation? : Option (Formula.Deriv rowsCommuteF true) :=
  derivationOf? rowsCommuteF

def logicalPairDerivation? : Option (Formula.Deriv logicalPairF true) :=
  derivationOf? logicalPairF

def distanceLowerDerivation? : Option (Formula.Deriv distanceLowerF true) :=
  derivationOf? distanceLowerF

def distanceUpperDerivation? : Option (Formula.Deriv distanceUpperF true) :=
  derivationOf? distanceUpperF

def exactDistanceThreeDerivation? : Option (Formula.Deriv exactDistanceThreeF true) :=
  derivationOf? exactDistanceThreeF

def rowsCommuteDerivationChecked : Bool :=
  derivationChecked rowsCommuteF

def logicalPairDerivationChecked : Bool :=
  derivationChecked logicalPairF

def distanceLowerDerivationChecked : Bool :=
  derivationChecked distanceLowerF

def distanceUpperDerivationChecked : Bool :=
  derivationChecked distanceUpperF

def exactDistanceThreeDerivationChecked : Bool :=
  derivationChecked exactDistanceThreeF

def exactDistanceThreeDerivationSize? : Option Nat :=
  match exactDistanceThreeDerivation? with
  | some D => some D.size
  | none => none

/-! ## Generated views for review -/

def evalRowString (k : Nat) : String :=
  let row := (List.finRange 5).map fun q => code.evalEntry? 1 5 k q.val
  row.foldr
    (fun p acc =>
      (match p with
      | some Pauli.I => "I"
      | some Pauli.X => "X"
      | some Pauli.Y => "Y"
      | some Pauli.Z => "Z"
      | none => "?") ++ acc)
    ""

def generatedRows : List String :=
  (List.finRange 4).map fun k => evalRowString k.val

/-- info: ["XZZXI", "IXZZX", "XIXZZ", "ZXIXZ"] -/
#guard_msgs in
#eval generatedRows

/-- info: true -/
#guard_msgs in
#eval logicalPairCheck.run

/-- info: true -/
#guard_msgs in
#eval rowsCommuteCheck.run

/-- info: true -/
#guard_msgs in
#eval distanceLowerCheck.run

/-- info: true -/
#guard_msgs in
#eval distanceUpperCheck.run

/-- info: true -/
#guard_msgs in
#eval exactDistanceThreeCheck.run

/-- info: true -/
#guard_msgs in
#eval rowsCommuteDerivationChecked

/-- info: true -/
#guard_msgs in
#eval logicalPairDerivationChecked

/-- info: true -/
#guard_msgs in
#eval distanceLowerDerivationChecked

/-- info: true -/
#guard_msgs in
#eval distanceUpperDerivationChecked

/-- info: true -/
#guard_msgs in
#eval exactDistanceThreeDerivationChecked

#print axioms code
#print axioms logicalX
#print axioms logicalZ
#print axioms exactDistanceThreeCheck
#print axioms exactDistanceThreeDerivationChecked

end QHL.CodeLang.FiveQubit
