import QStab.QClifford.Compile.Calculus
import QStab.QClifford.PCC.VCGen

/-!
# Compiler-to-VCGen bridge

This module contains the thin proof adapter from a semantic syndrome theorem to
the concrete `.syn` verification condition generated by the QClifford PCC
VCGen.  The compiler proofs in `Compile.Calculus` establish detector parity for
compiled gadgets; a code/extraction spec instantiation can feed the resulting
semantic equality to `vcgen_syn_of_semantic_syn` below.
-/

namespace QStab.QClifford.PCC

open QStab.QClifford.Compile

theorem vcgen_syn_of_semantic_syn {nq : Nat} (input : VCInput nq)
    (h :
      ∀ i E,
        gadgetMeasFlip input.program input.toCodeSpec i E =
          parity input.toCodeSpec (input.toCodeSpec.stabilizer i) E) :
    (vcgen input).denoteSlot .syn := by
  simpa [vcgen, GeneratedVCs.denoteSlot, VCSlot.denote] using h

/-- Number of time-resolved detector slots generated by one compiled fresh
gadget.  This is not just the number of stabilizer readout bits: Shor also
emits a verifier detector, and Flag emits a separate flag detector. -/
def compiledDetectorCount {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n) : Nat :=
  match scheme with
  | .NZ => 1
  | .Knill => sigma.slots.length
  | .Shor => sigma.slots.length + 1
  | .Flag => 2

/-- Raw detector slots whose XOR is the stabilizer readout for one compiled
gadget.  The order matches `readoutOffsets`, hence the order produced by the
scheme-specific compilation rule. -/
def compiledReadoutFlags {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n) :
    List (Fin (compiledDetectorCount scheme sigma)) :=
  match scheme with
  | .NZ => [⟨0, by simp [compiledDetectorCount]⟩]
  | .Knill => List.finRange sigma.slots.length
  | .Shor =>
      (List.finRange sigma.slots.length).map fun a =>
        ⟨a.val + 1, by
          have := a.isLt
          change a.val + 1 < sigma.slots.length + 1
          omega⟩
  | .Flag => [⟨0, by simp [compiledDetectorCount]⟩]

/-- Postselection detector policy for one compiled gadget.  Shor slot 0 is the
cat-verifier slot; Flag slot 1 is the flag slot. -/
def compiledPostselectFlag {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n) :
    Fin (compiledDetectorCount scheme sigma) → Bool :=
  match scheme with
  | .NZ => fun _ => false
  | .Knill => fun _ => false
  | .Shor => fun f => decide (f.val = 0)
  | .Flag => fun f => decide (f.val = 1)

theorem compiledReadoutFlags_val {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n) :
    (compiledReadoutFlags scheme sigma).map (fun f => f.val) =
      readoutOffsets scheme sigma := by
  cases scheme
  · simp [compiledReadoutFlags, readoutOffsets, compiledDetectorCount]
  · simp [compiledReadoutFlags, readoutOffsets, compiledDetectorCount]
  · calc
      (compiledReadoutFlags Scheme.Shor sigma).map (fun f => f.val)
          = (List.finRange sigma.slots.length).map (fun a => a.val + 1) := by
            simp [compiledReadoutFlags, compiledDetectorCount]
      _ = ((List.finRange sigma.slots.length).map (fun a => a.val)).map Nat.succ := by
            rw [List.map_map]
            apply List.map_congr_left
            intro a
            simp [Nat.succ_eq_add_one]
      _ = (List.range sigma.slots.length).map Nat.succ := by
            rw [List.map_coe_finRange_eq_range]
      _ = readoutOffsets Scheme.Shor sigma := by
            rfl
  · simp [compiledReadoutFlags, readoutOffsets, compiledDetectorCount]

theorem detectorXor_foldl_eq_xorBools {nq : Nat} (slots : List Nat)
    (es : ErrorState nq) (init : Bool) :
    slots.foldl (fun acc slot => xor acc (es.detectors slot)) init =
      xor init (xorBools (slots.map fun slot => es.detectors slot)) := by
  induction slots generalizing init with
  | nil =>
      simp [xorBools]
  | cons slot rest ih =>
      simp [List.foldl, xorBools, ih]

theorem xorBools_map_detectors_eq_detectorXor {nq : Nat} (slots : List Nat)
    (es : ErrorState nq) :
    xorBools (slots.map fun slot => es.detectors slot) = detectorXor slots es := by
  unfold detectorXor
  rw [detectorXor_foldl_eq_xorBools]
  simp

theorem flagMeasZ_detector_cursor {nq : Nat} (anc : Fin nq) (es : ErrorState nq)
    (start : Nat) (hcursor : es.detectorCursor = start) :
    (propagateCircuit (eraseFaults (flagMeasZ anc)) es).detectors start =
      hasXComp (es.paulis anc) := by
  simp [flagMeasZ, eraseFaults, propagateCircuit, propagateGate, hcursor]

/-- One-stabilizer PCC spec generated from one fresh compiled gadget.  The
stabilizer row is supplied by the source-side schedule elaborator; the circuit,
raw detector layout, postselection slots, and expected program are computed
from the compilation rule. -/
def singleGadgetCodeSpec {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli) :
    CodeSpec (n + helperCount scheme sigma) where
  numStab := 1
  numFlags := compiledDetectorCount scheme sigma
  isData := fun q => decide (q.val < n)
  stabilizer := fun _ => stab
  stabilizerReadout := fun _ => compiledReadoutFlags scheme sigma
  postselectFlag := compiledPostselectFlag scheme sigma
  flagSlot := fun i => i.val
  flagSlot_injective := by
    intro a b h
    exact Fin.ext h
  flagSlot_ordered := by
    intro i
    rfl
  readout_disjoint := by
    intro i j hij _ _ _
    exact hij (Subsingleton.elim i j)
  gadgetDetectorStart := fun _ => 0
  gadget := fun _ => compileFreshGadget scheme sigma
  expectedProgram := circuitView (compileFreshGadget scheme sigma)
  d := 1
  d_pos := by decide

/-- VCGen input generated from one fresh compiled gadget. -/
def singleGadgetVCInput {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (hnq : 0 < n + helperCount scheme sigma) :
  VCInput (n + helperCount scheme sigma) :=
  VCInput.ofPCC (compileFreshGadget scheme sigma)
    (singleGadgetCodeSpec scheme sigma stab) .unconditional hnq
    (by simp [singleGadgetCodeSpec])

theorem singleGadget_stateOfData_eq_dataInputState {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (E : Fin (n + helperCount scheme sigma) → Pauli) :
    stateOfDataPauliAtDetector (singleGadgetCodeSpec scheme sigma stab) 0 E =
      dataInputState (k := helperCount scheme sigma)
        (fun q : Fin n => E (freshDataQ n (helperCount scheme sigma) q)) := by
  simp [stateOfDataPauliAtDetector, stateOfPauliAtDetector, singleGadgetCodeSpec,
    dataInputState]
  funext q
  by_cases hq : q.val < n
  · have hqeq :
      freshDataQ n (helperCount scheme sigma) ⟨q.val, hq⟩ = q := by
        exact Fin.ext rfl
    simp [dataOnlyPauli, hq, hqeq]
  · simp [dataOnlyPauli, hq]

theorem singleGadget_syndromeBit_eq_gadgetDetectorBit {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (es : ErrorState (n + helperCount scheme sigma)) :
    syndromeBit (singleGadgetCodeSpec scheme sigma stab) es
        ⟨0, by simp [singleGadgetCodeSpec]⟩ =
      gadgetDetectorBit scheme sigma es := by
  calc
    syndromeBit (singleGadgetCodeSpec scheme sigma stab) es
          ⟨0, by simp [singleGadgetCodeSpec]⟩
        = xorBools
            ((compiledReadoutFlags scheme sigma).map fun f => es.detectors f.val) := by
          rfl
    _ = xorBools ((readoutOffsets scheme sigma).map fun slot => es.detectors slot) := by
          rw [← compiledReadoutFlags_val scheme sigma]
          simp [List.map_map, Function.comp_def]
    _ = detectorXor (readoutOffsets scheme sigma) es := by
          exact xorBools_map_detectors_eq_detectorXor _ _

theorem compileFreshGadget_scheme_correct {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n) :
    GadgetDetectorCorrect scheme sigma := by
  cases scheme
  · exact compileFreshGadget_NZ_correct sigma
  · exact compileFreshGadget_Knill_correct sigma
  · exact compileFreshGadget_Shor_correct sigma
  · exact compileFreshGadget_Flag_correct sigma

/-! ## Schedule-derived stabilizer rows -/

/-- Singleton X/Z row for one scheduled source slot, embedded into a target
space with `k` fresh helper qubits. -/
def scheduleSlotRow {n k : Nat} (slot : ScheduledPauli n) : Fin (n + k) → Pauli :=
  fun q => if q = freshDataQ n k slot.qubit then slot.kind.toPauli else Pauli.I

/-- Stabilizer row denoted by an ordered X/Z source schedule.  Repeated slots
are interpreted by phase-free Pauli multiplication, so the row is well defined
even before imposing a no-duplicate well-formedness side condition. -/
def scheduleRow {n k : Nat} (sigma : RuleSchedule n) : Fin (n + k) → Pauli :=
  sigma.slots.foldl
    (fun acc slot => ErrorVec.mul acc (scheduleSlotRow (k := k) slot))
    (ErrorVec.identity (n + k))

theorem scheduleSlotRow_parity {n k : Nat} (slot : ScheduledPauli n)
    (E : Fin (n + k) → Pauli) :
    ErrorVec.parity (scheduleSlotRow (k := k) slot) E =
      anticommute slot.kind.toPauli (E (freshDataQ n k slot.qubit)) := by
  classical
  unfold ErrorVec.parity scheduleSlotRow
  rw [anticommute_eq_anticommutes]
  by_cases h :
      ErrorVec.Pauli.anticommutes slot.kind.toPauli (E (freshDataQ n k slot.qubit)) = true
  · have hfilter :
        (Finset.univ.filter fun q =>
          ErrorVec.Pauli.anticommutes
            (if q = freshDataQ n k slot.qubit then slot.kind.toPauli else Pauli.I)
            (E q)) =
          {freshDataQ n k slot.qubit} := by
        ext q
        by_cases hq : q = freshDataQ n k slot.qubit
        · subst q
          simp [h]
        · simp [hq]
    rw [hfilter]
    simpa using h
  · have hfalse :
      ErrorVec.Pauli.anticommutes slot.kind.toPauli
          (E (freshDataQ n k slot.qubit)) = false := by
        cases hbit :
          ErrorVec.Pauli.anticommutes slot.kind.toPauli
            (E (freshDataQ n k slot.qubit)) <;> simp_all
    have hfilter :
        (Finset.univ.filter fun q =>
          ErrorVec.Pauli.anticommutes
            (if q = freshDataQ n k slot.qubit then slot.kind.toPauli else Pauli.I)
            (E q)) =
          ∅ := by
        ext q
        by_cases hq : q = freshDataQ n k slot.qubit
        · subst q
          simp [hfalse]
        · simp [hq]
    rw [hfilter]
    simp [hfalse]

theorem scheduleRowList_parity {n k : Nat} (slots : List (ScheduledPauli n))
    (base : Fin (n + k) → Pauli) (E : Fin (n + k) → Pauli) :
    ErrorVec.parity
        (slots.foldl
          (fun acc slot => ErrorVec.mul acc (scheduleSlotRow (k := k) slot))
          base)
        E =
      slots.foldl
        (fun acc slot =>
          xor acc (anticommute slot.kind.toPauli (E (freshDataQ n k slot.qubit))))
        (ErrorVec.parity base E) := by
  induction slots generalizing base with
  | nil =>
      rfl
  | cons slot rest ih =>
      simp [List.foldl, ih, ErrorVec.parity_mul_left, scheduleSlotRow_parity]

theorem scheduleRow_parity {n k : Nat} (spec : CodeSpec (n + k)) (sigma : RuleSchedule n)
    (E : Fin (n + k) → Pauli) :
    parity spec (scheduleRow (k := k) sigma) E =
      scheduleParity sigma (fun q : Fin n => E (freshDataQ n k q)) := by
  cases sigma with
  | mk slots =>
      unfold parity scheduleParity scheduleRow
      rw [vectorParity_eq_parity]
      rw [scheduleRowList_parity]
      rw [ErrorVec.parity_identity_left]

theorem scheduleRow_vectorParity {n k : Nat} (sigma : RuleSchedule n)
    (E : Fin (n + k) → Pauli) :
    vectorParity (scheduleRow (k := k) sigma) E =
      scheduleParity sigma (fun q : Fin n => E (freshDataQ n k q)) := by
  cases sigma with
  | mk slots =>
      unfold scheduleParity scheduleRow
      rw [vectorParity_eq_parity]
      rw [scheduleRowList_parity]
      rw [ErrorVec.parity_identity_left]

/-- Semantic syndrome correctness for the generated one-gadget spec.  This is
the circuit-level part of the generated proof before it is packaged as a VCGen
slot. -/
theorem singleGadget_semantic_syn_of_scheduleParity {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (hParity :
      ∀ E : Fin (n + helperCount scheme sigma) → Pauli,
        parity (singleGadgetCodeSpec scheme sigma stab) stab E =
          scheduleParity sigma
            (fun q : Fin n => E (freshDataQ n (helperCount scheme sigma) q))):
    ∀ i E,
      gadgetMeasFlip (compileFreshGadget scheme sigma)
        (singleGadgetCodeSpec scheme sigma stab) i E =
        parity (singleGadgetCodeSpec scheme sigma stab)
          ((singleGadgetCodeSpec scheme sigma stab).stabilizer i) E := by
  intro i E
  have hval : i.val = 0 := by
    have hlt := i.isLt
    change i.val < 1 at hlt
    omega
  have hi : i = ⟨0, by simp [singleGadgetCodeSpec]⟩ := Fin.ext hval
  subst i
  unfold gadgetMeasFlip
  change
    syndromeBit (singleGadgetCodeSpec scheme sigma stab)
      (propagateCircuit (eraseFaults (compileFreshGadget scheme sigma))
        (stateOfDataPauliAtDetector (singleGadgetCodeSpec scheme sigma stab) 0 E))
      ⟨0, by simp [singleGadgetCodeSpec]⟩ =
        parity (singleGadgetCodeSpec scheme sigma stab) stab E
  rw [singleGadget_stateOfData_eq_dataInputState scheme sigma stab E]
  rw [singleGadget_syndromeBit_eq_gadgetDetectorBit scheme sigma stab]
  rw [compileFreshGadget_scheme_correct scheme sigma]
  exact (hParity E).symm

/-- The concrete generated `.syn` VC for one compiled stabilizer gadget follows
from the scheme correctness theorem and the generated row-parity obligation.
The parity obligation is the source-to-target stabilizer-row check: it states
that the declared QClifford row has exactly the same anticommutation parity as
the ordered QStab schedule on data qubits. -/
theorem singleGadget_vcgen_syn_of_scheduleParity {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (hnq : 0 < n + helperCount scheme sigma)
    (hParity :
      ∀ E : Fin (n + helperCount scheme sigma) → Pauli,
        parity (singleGadgetCodeSpec scheme sigma stab) stab E =
          scheduleParity sigma
            (fun q : Fin n => E (freshDataQ n (helperCount scheme sigma) q))) :
    (vcgen (singleGadgetVCInput scheme sigma stab hnq)).denoteSlot .syn := by
  apply vcgen_syn_of_semantic_syn
  simpa [singleGadgetVCInput, VCInput.toCodeSpec_ofPCC] using
    singleGadget_semantic_syn_of_scheduleParity scheme sigma stab hParity

/-- Fully automatic generated `.syn` VC proof for one compiled stabilizer
instruction: the stabilizer row is computed from the source schedule itself. -/
theorem singleGadget_vcgen_syn {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (hnq : 0 < n + helperCount scheme sigma) :
    (vcgen
      (singleGadgetVCInput scheme sigma
        (scheduleRow (k := helperCount scheme sigma) sigma) hnq)).denoteSlot .syn :=
  singleGadget_vcgen_syn_of_scheduleParity scheme sigma
    (scheduleRow (k := helperCount scheme sigma) sigma) hnq
    (by
      intro E
      exact scheduleRow_parity
        (singleGadgetCodeSpec scheme sigma
          (scheduleRow (k := helperCount scheme sigma) sigma))
        sigma E)

/-! ## XZProgram-level generated syndrome VCs -/

/-- One source stabilizer-measurement instruction after flattening an
`XZProgram`. -/
structure ProgramMeasure (n : Nat) where
  scheme : Scheme
  schedule : RuleSchedule n
  deriving Repr

def programMeasures {n : Nat} : XZProgram n → List (ProgramMeasure n)
  | .skip => []
  | .meas scheme schedule => [⟨scheme, schedule⟩]
  | .seq first second => programMeasures first ++ programMeasures second

def ProgramMeasure.synVCInput {n : Nat} (m : ProgramMeasure n)
    (hnq : 0 < n + helperCount m.scheme m.schedule) :
    VCInput (n + helperCount m.scheme m.schedule) :=
  singleGadgetVCInput m.scheme m.schedule
    (scheduleRow (k := helperCount m.scheme m.schedule) m.schedule) hnq

def ProgramMeasure.synVCDischarged {n : Nat} (m : ProgramMeasure n) : Prop :=
  ∀ hnq : 0 < n + helperCount m.scheme m.schedule,
    (vcgen (m.synVCInput hnq)).denoteSlot .syn

theorem ProgramMeasure.synVCDischarged_auto {n : Nat} (m : ProgramMeasure n) :
    m.synVCDischarged := by
  intro hnq
  cases m with
  | mk scheme schedule =>
      exact singleGadget_vcgen_syn scheme schedule hnq

/-- The generated `.syn` obligations for a source program are exactly the
flattened stabilizer measurements.  This predicate is intentionally phrased over
membership in `programMeasures`, so a producer cannot skip a source
instruction. -/
def programSynVCsDischarged {n : Nat} (program : XZProgram n) : Prop :=
  ∀ m, m ∈ programMeasures program → m.synVCDischarged

theorem programSynVCsDischarged_auto {n : Nat} :
    ∀ program : XZProgram n, programSynVCsDischarged program
  | .skip => by
      intro m hmem
      cases hmem
  | .meas scheme schedule => by
      intro m hmem
      simp [programMeasures] at hmem
      subst m
      exact ProgramMeasure.synVCDischarged_auto ⟨scheme, schedule⟩
  | .seq first second => by
      intro m hmem
      simp [programMeasures] at hmem ⊢
      rcases hmem with hmem | hmem
      · exact programSynVCsDischarged_auto first m hmem
      · exact programSynVCsDischarged_auto second m hmem

structure ProgramSynCertificate {n : Nat} (program : XZProgram n) where
  measures : List (ProgramMeasure n)
  measures_eq : measures = programMeasures program
  syn : ∀ m, m ∈ measures → m.synVCDischarged

/-- Automatically generated local `.syn` certificate package for every
stabilizer-measurement instruction in an `XZProgram`.  The proof is by
structural induction through `XZProgram.synVCsDischarged_auto`; each leaf is the
checked single-gadget VCGen `.syn` proof above. -/
def XZProgram.generatedSynCertificate {n : Nat} (program : XZProgram n) :
    ProgramSynCertificate program where
  measures := programMeasures program
  measures_eq := rfl
  syn := programSynVCsDischarged_auto program

structure ProgramCompilationSynCertificate {n : Nat} (program : XZProgram n) where
  circuit : FCircuit (n + programHelperCount program)
  deriv : ProgramCompileDeriv 0 program circuit
  syn : ProgramSynCertificate program

/-- Compiler-produced package for a full `XZProgram`: the concrete compiled
QClifford circuit, the compilation derivation tree, and the automatically
generated checked `.syn` VC proofs for every source stabilizer instruction. -/
def XZProgram.generatedCompilationSynCertificate {n : Nat} (program : XZProgram n) :
    ProgramCompilationSynCertificate program where
  circuit := compileProgram program
  deriv := compileProgramDeriv program
  syn := XZProgram.generatedSynCertificate program

/-! ## Monolithic full-program VC input skeleton -/

def programDetectorCount {n : Nat} : XZProgram n → Nat
  | .skip => 0
  | .meas scheme schedule => compiledDetectorCount scheme schedule
  | .seq first second => programDetectorCount first + programDetectorCount second

structure ProgramMeasureAt (n totalHelpers totalFlags : Nat) where
  scheme : Scheme
  schedule : RuleSchedule n
  helperStart : Nat
  detectorStart : Nat
  helperFit : helperStart + helperCount scheme schedule ≤ totalHelpers
  detectorFit : detectorStart + compiledDetectorCount scheme schedule ≤ totalFlags

def programMeasuresAtAux {n totalHelpers totalFlags : Nat} :
    (helperStart detectorStart : Nat) → (program : XZProgram n) →
      helperStart + programHelperCount program ≤ totalHelpers →
      detectorStart + programDetectorCount program ≤ totalFlags →
      List (ProgramMeasureAt n totalHelpers totalFlags)
  | _, _, .skip, _, _ => []
  | helperStart, detectorStart, .meas scheme schedule, helperFit, detectorFit =>
      [⟨scheme, schedule, helperStart, detectorStart, helperFit, detectorFit⟩]
  | helperStart, detectorStart, .seq first second, helperFit, detectorFit =>
      programMeasuresAtAux helperStart detectorStart first
        (by simp [programHelperCount] at helperFit ⊢; omega)
        (by simp [programDetectorCount] at detectorFit ⊢; omega) ++
      programMeasuresAtAux
        (helperStart + programHelperCount first)
        (detectorStart + programDetectorCount first)
        second
        (by simp [programHelperCount] at helperFit ⊢; omega)
        (by simp [programDetectorCount] at detectorFit ⊢; omega)

def programMeasuresAt {n : Nat} (program : XZProgram n) :
    List (ProgramMeasureAt n (programHelperCount program) (programDetectorCount program)) :=
  programMeasuresAtAux 0 0 program (by simp) (by simp)

def programNumStab {n : Nat} (program : XZProgram n) : Nat :=
  (programMeasuresAt program).length

def ProgramMeasureAt.shiftFlag {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags)
    (f : Fin (compiledDetectorCount m.scheme m.schedule)) : Fin totalFlags :=
  ⟨m.detectorStart + f.val, by
    have hf := f.isLt
    have hfit := m.detectorFit
    omega⟩

def ProgramMeasureAt.shiftedReadout {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) : List (Fin totalFlags) :=
  (compiledReadoutFlags m.scheme m.schedule).map m.shiftFlag

def ProgramMeasureAt.detectorEnd {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) : Nat :=
  m.detectorStart + compiledDetectorCount m.scheme m.schedule

def ProgramMeasureAt.detectorBefore {n totalHelpers totalFlags : Nat}
    (m₁ m₂ : ProgramMeasureAt n totalHelpers totalFlags) : Prop :=
  m₁.detectorEnd ≤ m₂.detectorStart

theorem ProgramMeasureAt.mem_shiftedReadout_bounds {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) {s : Fin totalFlags}
    (hs : s ∈ m.shiftedReadout) :
    m.detectorStart ≤ s.val ∧ s.val < m.detectorEnd := by
  rw [ProgramMeasureAt.shiftedReadout] at hs
  rcases List.mem_map.mp hs with ⟨localFlag, _hmem, rfl⟩
  constructor
  · simp [ProgramMeasureAt.shiftFlag]
  · simp [ProgramMeasureAt.shiftFlag, ProgramMeasureAt.detectorEnd]

theorem ProgramMeasureAt.shiftedReadout_disjoint_of_before {n totalHelpers totalFlags : Nat}
    (m₁ m₂ : ProgramMeasureAt n totalHelpers totalFlags)
    (hbefore : m₁.detectorBefore m₂) :
    ∀ s, s ∈ m₁.shiftedReadout → s ∈ m₂.shiftedReadout → False := by
  intro s hs₁ hs₂
  have h₁ := m₁.mem_shiftedReadout_bounds hs₁
  have h₂ := m₂.mem_shiftedReadout_bounds hs₂
  dsimp [ProgramMeasureAt.detectorBefore] at hbefore
  omega

theorem programMeasuresAtAux_within_detector {n totalHelpers totalFlags : Nat}
    (helperStart detectorStart : Nat) (program : XZProgram n)
    (helperFit : helperStart + programHelperCount program ≤ totalHelpers)
    (detectorFit : detectorStart + programDetectorCount program ≤ totalFlags) :
    ∀ m, m ∈ programMeasuresAtAux helperStart detectorStart program helperFit detectorFit →
      detectorStart ≤ m.detectorStart ∧
        m.detectorEnd ≤ detectorStart + programDetectorCount program := by
  induction program generalizing helperStart detectorStart with
  | skip =>
      intro m hmem
      simp [programMeasuresAtAux] at hmem
  | meas scheme schedule =>
      intro m hmem
      simp [programMeasuresAtAux] at hmem
      subst m
      constructor <;> simp [ProgramMeasureAt.detectorEnd, programDetectorCount]
  | seq first second ihFirst ihSecond =>
      intro m hmem
      simp [programMeasuresAtAux] at hmem
      rcases hmem with hmem | hmem
      · have hm :=
          ihFirst helperStart detectorStart
            (by simp [programHelperCount] at helperFit ⊢; omega)
            (by simp [programDetectorCount] at detectorFit ⊢; omega)
            m hmem
        constructor
        · exact hm.1
        · simp [programDetectorCount]
          omega
      · have hm :=
          ihSecond (helperStart + programHelperCount first)
            (detectorStart + programDetectorCount first)
            (by simp [programHelperCount] at helperFit ⊢; omega)
            (by simp [programDetectorCount] at detectorFit ⊢; omega)
            m hmem
        constructor
        · omega
        · simp [programDetectorCount]
          omega

theorem programMeasuresAtAux_pairwise_detectorBefore {n totalHelpers totalFlags : Nat}
    (helperStart detectorStart : Nat) (program : XZProgram n)
    (helperFit : helperStart + programHelperCount program ≤ totalHelpers)
    (detectorFit : detectorStart + programDetectorCount program ≤ totalFlags) :
    List.Pairwise ProgramMeasureAt.detectorBefore
      (programMeasuresAtAux helperStart detectorStart program helperFit detectorFit) := by
  induction program generalizing helperStart detectorStart with
  | skip =>
      simp [programMeasuresAtAux]
  | meas scheme schedule =>
      simp [programMeasuresAtAux]
  | seq first second ihFirst ihSecond =>
      simp [programMeasuresAtAux, List.pairwise_append]
      constructor
      · exact ihFirst helperStart detectorStart
          (by simp [programHelperCount] at helperFit ⊢; omega)
          (by simp [programDetectorCount] at detectorFit ⊢; omega)
      constructor
      · exact ihSecond (helperStart + programHelperCount first)
          (detectorStart + programDetectorCount first)
          (by simp [programHelperCount] at helperFit ⊢; omega)
          (by simp [programDetectorCount] at detectorFit ⊢; omega)
      · intro a ha b hb
        have haBounds :=
          programMeasuresAtAux_within_detector helperStart detectorStart first
            (by simp [programHelperCount] at helperFit ⊢; omega)
            (by simp [programDetectorCount] at detectorFit ⊢; omega)
            a ha
        have hbBounds :=
          programMeasuresAtAux_within_detector
            (helperStart + programHelperCount first)
            (detectorStart + programDetectorCount first)
            second
            (by simp [programHelperCount] at helperFit ⊢; omega)
            (by simp [programDetectorCount] at detectorFit ⊢; omega)
            b hb
        dsimp [ProgramMeasureAt.detectorBefore]
        omega

theorem programMeasuresAt_pairwise_detectorBefore {n : Nat} (program : XZProgram n) :
    List.Pairwise ProgramMeasureAt.detectorBefore (programMeasuresAt program) := by
  exact programMeasuresAtAux_pairwise_detectorBefore 0 0 program (by simp) (by simp)

def ProgramMeasureAt.localPostselectedAt {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) (f : Fin totalFlags) : Bool :=
  (List.finRange (compiledDetectorCount m.scheme m.schedule)).any fun localFlag =>
    decide (f = m.shiftFlag localFlag) && compiledPostselectFlag m.scheme m.schedule localFlag

def fullProgramPostselectFlag {n : Nat} (program : XZProgram n)
    (f : Fin (programDetectorCount program)) : Bool :=
  (programMeasuresAt program).any fun m => m.localPostselectedAt f

def fullProgramReadoutDisjoint {n : Nat} (program : XZProgram n) : Prop :=
  ∀ i j : Fin (programNumStab program), i ≠ j → ∀ s,
    s ∈ ((programMeasuresAt program).get i).shiftedReadout →
    s ∈ ((programMeasuresAt program).get j).shiftedReadout →
    False

theorem fullProgramReadoutDisjoint_auto {n : Nat} (program : XZProgram n) :
    fullProgramReadoutDisjoint program := by
  intro i j hij s hsᵢ hsⱼ
  have hpair := programMeasuresAt_pairwise_detectorBefore program
  by_cases hijlt : i < j
  · have hbefore := (List.pairwise_iff_get.mp hpair) i j hijlt
    exact ProgramMeasureAt.shiftedReadout_disjoint_of_before
      ((programMeasuresAt program).get i) ((programMeasuresAt program).get j)
      hbefore s hsᵢ hsⱼ
  · have hjilt : j < i := by
      have hneVal : i.val ≠ j.val := by
        intro hval
        exact hij (Fin.ext hval)
      omega
    have hbefore := (List.pairwise_iff_get.mp hpair) j i hjilt
    exact ProgramMeasureAt.shiftedReadout_disjoint_of_before
      ((programMeasuresAt program).get j) ((programMeasuresAt program).get i)
      hbefore s hsⱼ hsᵢ

def fullProgramCodeSpec {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program) :
    CodeSpec (n + programHelperCount program) where
  numStab := programNumStab program
  numFlags := programDetectorCount program
  isData := fun q => decide (q.val < n)
  stabilizer := fun i =>
    scheduleRow (k := programHelperCount program) ((programMeasuresAt program).get i).schedule
  stabilizerReadout := fun i => ((programMeasuresAt program).get i).shiftedReadout
  postselectFlag := fullProgramPostselectFlag program
  flagSlot := fun i => i.val
  flagSlot_injective := by
    intro a b h
    exact Fin.ext h
  flagSlot_ordered := by
    intro i
    rfl
  readout_disjoint := hdisjoint
  gadgetDetectorStart := fun i => ((programMeasuresAt program).get i).detectorStart
  gadget := fun i =>
    let m := (programMeasuresAt program).get i
    compileGadgetBlock m.scheme m.schedule m.helperStart m.helperFit
  expectedProgram := circuitView (compileProgram program)
  d := 1
  d_pos := by decide

@[simp] theorem dataOnlyPauli_fullProgramCodeSpec {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program)
    (E : Fin (n + programHelperCount program) → Pauli)
    (q : Fin (n + programHelperCount program)) :
    dataOnlyPauli (fullProgramCodeSpec program hdisjoint) E q =
      if decide (q.val < n) then E q else Pauli.I := by
  simp [dataOnlyPauli, fullProgramCodeSpec]

def fullProgramVCInput {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    VCInput (n + programHelperCount program) :=
  VCInput.ofPCC (compileProgram program) (fullProgramCodeSpec program hdisjoint)
    .unconditional hnq hnumStab

def fullProgramEmbeddedSynCorrect {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program) : Prop :=
  ∀ i E,
    gadgetMeasFlip (compileProgram program) (fullProgramCodeSpec program hdisjoint) i E =
      parity (fullProgramCodeSpec program hdisjoint)
        ((fullProgramCodeSpec program hdisjoint).stabilizer i) E

def ProgramMeasureAt.embeddedDetectorBit {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) (es : ErrorState (n + totalHelpers)) :
    Bool :=
  xorBools (m.shiftedReadout.map fun f => es.detectors f.val)

def ProgramMeasureAt.dataOnlyStateAtDetector {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags)
    (E : Fin (n + totalHelpers) → Pauli) : ErrorState (n + totalHelpers) :=
  stateOfPauliAtDetector m.detectorStart
    (fun q => if decide (q.val < n) then E q else Pauli.I)

theorem freshDataQ_ne_blockHelperQ {n total start width : Nat}
    (hfit : start + width ≤ total) (q : Fin n) (a : Fin width) :
    freshDataQ n total q ≠ blockHelperQ n total start width hfit a := by
  intro h
  have hv := congrArg Fin.val h
  simp [freshDataQ, blockHelperQ] at hv
  have hq := q.isLt
  omega

@[simp] theorem ProgramMeasureAt.dataOnlyStateAtDetector_freshDataQ
    {n totalHelpers totalFlags : Nat} (m : ProgramMeasureAt n totalHelpers totalFlags)
    (E : Fin (n + totalHelpers) → Pauli) (q : Fin n) :
    (m.dataOnlyStateAtDetector E).paulis (freshDataQ n totalHelpers q) =
      E (freshDataQ n totalHelpers q) := by
  simp [ProgramMeasureAt.dataOnlyStateAtDetector, stateOfPauliAtDetector,
    freshDataQ]

@[simp] theorem ProgramMeasureAt.dataOnlyStateAtDetector_blockHelperQ
    {n totalHelpers totalFlags start width : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags)
    (E : Fin (n + totalHelpers) → Pauli)
    (hfit : start + width ≤ totalHelpers) (a : Fin width) :
    (m.dataOnlyStateAtDetector E).paulis (blockHelperQ n totalHelpers start width hfit a) =
      Pauli.I := by
  have hnot : ¬ (blockHelperQ n totalHelpers start width hfit a).val < n := by
    simp [blockHelperQ]
    omega
  simp [ProgramMeasureAt.dataOnlyStateAtDetector, stateOfPauliAtDetector,
    hnot]

@[simp] theorem ProgramMeasureAt.dataOnlyStateAtDetector_cursor
    {n totalHelpers totalFlags : Nat} (m : ProgramMeasureAt n totalHelpers totalFlags)
    (E : Fin (n + totalHelpers) → Pauli) :
    (m.dataOnlyStateAtDetector E).detectorCursor = m.detectorStart := by
  simp [ProgramMeasureAt.dataOnlyStateAtDetector, stateOfPauliAtDetector]

def ProgramMeasureAt.embeddedSynCorrect {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) : Prop :=
  ∀ E : Fin (n + totalHelpers) → Pauli,
    m.embeddedDetectorBit
        (propagateCircuit (eraseFaults (compileGadgetBlock m.scheme m.schedule
          m.helperStart m.helperFit)) (m.dataOnlyStateAtDetector E)) =
      vectorParity (scheduleRow (k := totalHelpers) m.schedule) E

theorem ProgramMeasureAt.embeddedSynCorrect_of_detector {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags)
    (hdet :
      ∀ E : Fin (n + totalHelpers) → Pauli,
        m.embeddedDetectorBit
            (propagateCircuit (eraseFaults (compileGadgetBlock m.scheme m.schedule
              m.helperStart m.helperFit)) (m.dataOnlyStateAtDetector E)) =
          scheduleParity m.schedule (fun q : Fin n => E (freshDataQ n totalHelpers q))) :
    m.embeddedSynCorrect := by
  intro E
  rw [hdet E, scheduleRow_vectorParity]

theorem ProgramMeasureAt.embeddedSynCorrect_NZ {n totalHelpers totalFlags : Nat}
    (sigma : RuleSchedule n) (helperStart detectorStart : Nat)
    (helperFit : helperStart + helperCount .NZ sigma ≤ totalHelpers)
    (detectorFit : detectorStart + compiledDetectorCount .NZ sigma ≤ totalFlags) :
    (⟨.NZ, sigma, helperStart, detectorStart, helperFit, detectorFit⟩ :
      ProgramMeasureAt n totalHelpers totalFlags).embeddedSynCorrect := by
  apply ProgramMeasureAt.embeddedSynCorrect_of_detector
  intro E
  let m : ProgramMeasureAt n totalHelpers totalFlags :=
    ⟨.NZ, sigma, helperStart, detectorStart, helperFit, detectorFit⟩
  let anc : Fin (n + totalHelpers) :=
    blockHelperQ n totalHelpers helperStart 1 helperFit ⟨0, by decide⟩
  let slots : List (ScheduledPauli (n + totalHelpers)) := (liftSchedule (k := totalHelpers) sigma).slots
  let es0 : ErrorState (n + totalHelpers) := m.dataOnlyStateAtDetector E
  let globalE : Fin (n + totalHelpers) → Pauli := fun q => es0.paulis q
  let esPrep := propagateCircuit (eraseFaults (prep0 anc)) es0
  let esSlots := propagateCircuit (eraseFaults (zParitySlotsCircuit anc slots)) esPrep
  have hprep := prep0_state_for_chain anc es0
  have hne : ∀ slot, slot ∈ slots → slot.qubit ≠ anc := by
    intro slot hmem
    have hmem' : slot ∈ sigma.slots.map (liftSlot (k := totalHelpers)) := by
      simpa [slots, liftSchedule] using hmem
    rcases List.mem_map.mp hmem' with ⟨src, _hsrc, rfl⟩
    simpa [anc, liftSlot] using
      (freshDataQ_ne_blockHelperQ (n := n) (total := totalHelpers)
        (start := helperStart) (width := 1) helperFit src.qubit ⟨0, by decide⟩)
  have hdata : ∀ q : Fin (n + totalHelpers), q ≠ anc → esPrep.paulis q = globalE q := by
    intro q hq
    simpa [globalE, es0, esPrep] using hprep.2.1 q hq
  have hanc : esPrep.paulis anc = xOfBool false := by
    simpa [esPrep] using hprep.1
  have hchain := zParitySlotsCircuit_chain anc slots globalE false esPrep hne hdata hanc
  have hread := zParitySlotsCircuit_preserves_readout anc slots esPrep
  have hcursorPrep : esPrep.detectorCursor = detectorStart := by
    calc
      esPrep.detectorCursor = es0.detectorCursor := by
        simpa [esPrep] using hprep.2.2.2
      _ = detectorStart := by simp [es0, m]
  have hcursorSlots : esSlots.detectorCursor = detectorStart := by
    calc
      esSlots.detectorCursor = esPrep.detectorCursor := by
        simpa [esSlots] using hread.2
      _ = detectorStart := hcursorPrep
  have hglobal :
      globalE =
        fun q : Fin (n + totalHelpers) =>
          (dataInputState (k := totalHelpers)
            (fun q : Fin n => E (freshDataQ n totalHelpers q))).paulis q := by
    funext q
    by_cases hq : q.val < n
    · have hqeq : freshDataQ n totalHelpers ⟨q.val, hq⟩ = q := Fin.ext rfl
      simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
        stateOfPauliAtDetector, dataInputState, hq, hqeq]
    · simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
        stateOfPauliAtDetector, dataInputState, hq]
  have hparity :
      scheduleParityList slots globalE false =
        scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
    rw [hglobal]
    simpa [slots] using
      scheduleParityList_liftSchedule (k := totalHelpers) sigma
        (fun q : Fin n => E (freshDataQ n totalHelpers q))
  have hancSlots :
      esSlots.paulis anc = xOfBool (scheduleParityList slots globalE false) := by
    simpa [esSlots] using hchain.1
  have hfinal :
      (propagateCircuit (eraseFaults (flagMeasZ anc)) esSlots).detectors detectorStart =
        scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
    calc
      (propagateCircuit (eraseFaults (flagMeasZ anc)) esSlots).detectors detectorStart
          = hasXComp (esSlots.paulis anc) := flagMeasZ_detector_cursor anc esSlots
              detectorStart hcursorSlots
      _ = hasXComp (xOfBool (scheduleParityList slots globalE false)) := by rw [hancSlots]
      _ = scheduleParityList slots globalE false := by simp
      _ = scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := hparity
  have hcompiled :
      propagateCircuit (eraseFaults (compileGadgetBlock .NZ sigma helperStart helperFit)) es0 =
        propagateCircuit (eraseFaults (flagMeasZ anc)) esSlots := by
    simp [compileGadgetBlock, compileGadgetOrdered, compileStandardOrdered,
      blockAncillaConfig, anc, slots, esPrep, esSlots, zParitySlotsCircuit, eraseFaults_append,
      QHL.Target.propagateCircuit_append]
  change
    m.embeddedDetectorBit
        (propagateCircuit (eraseFaults (compileGadgetBlock .NZ sigma helperStart helperFit)) es0) =
      scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q))
  rw [hcompiled]
  simpa [m, ProgramMeasureAt.embeddedDetectorBit, ProgramMeasureAt.shiftedReadout,
    compiledReadoutFlags, compiledDetectorCount, ProgramMeasureAt.shiftFlag, xorBools]
    using hfinal

theorem fullProgramEmbeddedSynCorrect_of_blocks {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program)
    (hblocks :
      ∀ i : Fin (programNumStab program),
        ((programMeasuresAt program).get i).embeddedSynCorrect) :
    fullProgramEmbeddedSynCorrect program hdisjoint := by
  intro i E
  specialize hblocks i E
  have hstate :
      stateOfDataPauliAtDetector (fullProgramCodeSpec program hdisjoint)
          ((programMeasuresAt program).get i).detectorStart E =
        ((programMeasuresAt program).get i).dataOnlyStateAtDetector E := by
    simp [stateOfDataPauliAtDetector, stateOfPauliAtDetector,
      ProgramMeasureAt.dataOnlyStateAtDetector]
    funext q
    simp
  simpa [gadgetMeasFlip, syndromeBit, fullProgramCodeSpec,
    ProgramMeasureAt.embeddedSynCorrect, ProgramMeasureAt.embeddedDetectorBit, parity, hstate]
    using hblocks

theorem fullProgram_vcgen_syn_of_embeddedSynCorrect {n : Nat}
    (program : XZProgram n) (hdisjoint : fullProgramReadoutDisjoint program)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program)
    (hsyn : fullProgramEmbeddedSynCorrect program hdisjoint) :
    (vcgen (fullProgramVCInput program hdisjoint hnq hnumStab)).denoteSlot .syn := by
  apply vcgen_syn_of_semantic_syn
  simpa [fullProgramVCInput, VCInput.toCodeSpec_ofPCC] using hsyn

def generatedFullProgramCodeSpec {n : Nat} (program : XZProgram n) :
    CodeSpec (n + programHelperCount program) :=
  fullProgramCodeSpec program (fullProgramReadoutDisjoint_auto program)

def generatedFullProgramVCInput {n : Nat} (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    VCInput (n + programHelperCount program) :=
  fullProgramVCInput program (fullProgramReadoutDisjoint_auto program) hnq hnumStab

def generatedFullProgramEmbeddedSynCorrect {n : Nat} (program : XZProgram n) : Prop :=
  fullProgramEmbeddedSynCorrect program (fullProgramReadoutDisjoint_auto program)

def generatedFullProgramBlocksSynCorrect {n : Nat} (program : XZProgram n) : Prop :=
  ∀ i : Fin (programNumStab program),
    ((programMeasuresAt program).get i).embeddedSynCorrect

theorem generatedFullProgram_embeddedSynCorrect_of_blocks {n : Nat}
    (program : XZProgram n)
    (hblocks : generatedFullProgramBlocksSynCorrect program) :
    generatedFullProgramEmbeddedSynCorrect program := by
  exact fullProgramEmbeddedSynCorrect_of_blocks program
    (fullProgramReadoutDisjoint_auto program) hblocks

theorem generatedFullProgram_vcgen_syn_of_embeddedSynCorrect {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program)
    (hsyn : generatedFullProgramEmbeddedSynCorrect program) :
    (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .syn := by
  exact fullProgram_vcgen_syn_of_embeddedSynCorrect program
    (fullProgramReadoutDisjoint_auto program) hnq hnumStab hsyn

theorem generatedFullProgram_vcgen_syn_of_blocks {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program)
    (hblocks : generatedFullProgramBlocksSynCorrect program) :
    (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .syn := by
  exact generatedFullProgram_vcgen_syn_of_embeddedSynCorrect program hnq hnumStab
    (generatedFullProgram_embeddedSynCorrect_of_blocks program hblocks)

/-! ## Concrete generated syndrome VC example -/

namespace VCBridgeExamples

def q0 : Fin 1 := ⟨0, by decide⟩

def Z0 : RuleSchedule 1 :=
  ⟨[⟨.Z, q0⟩]⟩

/-- A fully generated `.syn` VC proof for the fixed source instruction
`VCBridgeExamples.Z0`, valid for any of the four compiler schemes.  The four
examples below instantiate this theorem as the concrete checked certificates
that a producer would emit for a fixed QStab instruction. -/
theorem z0_singleGadget_vcgen_syn (scheme : Scheme)
    (hnq : 0 < 1 + helperCount scheme Z0) :
    (vcgen
      (singleGadgetVCInput scheme Z0
        (scheduleRow (k := helperCount scheme Z0) Z0) hnq)).denoteSlot .syn :=
  singleGadget_vcgen_syn scheme Z0 hnq

example :
    (vcgen
      (singleGadgetVCInput .NZ Z0
        (scheduleRow (k := helperCount .NZ Z0) Z0) (by decide))).denoteSlot .syn :=
  z0_singleGadget_vcgen_syn .NZ (by decide)

example :
    (vcgen
      (singleGadgetVCInput .Knill Z0
        (scheduleRow (k := helperCount .Knill Z0) Z0) (by decide))).denoteSlot .syn :=
  z0_singleGadget_vcgen_syn .Knill (by decide)

example :
    (vcgen
      (singleGadgetVCInput .Shor Z0
        (scheduleRow (k := helperCount .Shor Z0) Z0) (by decide))).denoteSlot .syn :=
  z0_singleGadget_vcgen_syn .Shor (by decide)

example :
    (vcgen
      (singleGadgetVCInput .Flag Z0
        (scheduleRow (k := helperCount .Flag Z0) Z0) (by decide))).denoteSlot .syn :=
  z0_singleGadget_vcgen_syn .Flag (by decide)

end VCBridgeExamples

end QStab.QClifford.PCC
