import QStab.QClifford.Compile.Calculus
import QStab.QClifford.PCC.VCGen
import QStab.QHL.Target.Soundness

/-!
# Compiler-to-VCGen bridge

This module contains the thin proof adapter from a semantic syndrome theorem to
the concrete `.syn` verification condition generated by the QClifford PCC
VCGen.  The compiler proofs in `Compile.Calculus` establish detector parity for
compiled gadgets; a code/extraction spec instantiation can feed the resulting
semantic equality to `vcgen_syn_of_semantic_syn` below.
-/

namespace QStab.QClifford.PCC

open QStab.QClifford.Compile

theorem vcgen_syn_of_semantic_syn {nq : Nat} (input : VCInput nq)
    (h :
      ∀ i E,
        gadgetMeasFlip input.program input.toCodeSpec i E =
          parity input.toCodeSpec (input.toCodeSpec.stabilizer i) E) :
    (vcgen input).denoteSlot .syn := by
  simpa [vcgen, GeneratedVCs.denoteSlot, VCSlot.denote] using h

/-- Number of time-resolved detector slots generated by one compiled fresh
gadget.  This is not just the number of stabilizer readout bits: Shor also
emits a verifier detector, and Flag emits a separate flag detector. -/
def compiledDetectorCount {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n) : Nat :=
  match scheme with
  | .NZ => 1
  | .Knill => sigma.slots.length
  | .Shor => sigma.slots.length + 1
  | .Flag => 2

/-- Raw detector slots whose XOR is the stabilizer readout for one compiled
gadget.  The order matches `readoutOffsets`, hence the order produced by the
scheme-specific compilation rule. -/
def compiledReadoutFlags {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n) :
    List (Fin (compiledDetectorCount scheme sigma)) :=
  match scheme with
  | .NZ => [⟨0, by simp [compiledDetectorCount]⟩]
  | .Knill => List.finRange sigma.slots.length
  | .Shor =>
      (List.finRange sigma.slots.length).map fun a =>
        ⟨a.val + 1, by
          have := a.isLt
          change a.val + 1 < sigma.slots.length + 1
          omega⟩
  | .Flag => [⟨0, by simp [compiledDetectorCount]⟩]

/-- Postselection detector policy for one compiled gadget.  Shor slot 0 is the
cat-verifier slot; Flag slot 1 is the flag slot. -/
def compiledPostselectFlag {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n) :
    Fin (compiledDetectorCount scheme sigma) → Bool :=
  match scheme with
  | .NZ => fun _ => false
  | .Knill => fun _ => false
  | .Shor => fun f => decide (f.val = 0)
  | .Flag => fun f => decide (f.val = 1)

theorem compiledReadoutFlags_val {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n) :
    (compiledReadoutFlags scheme sigma).map (fun f => f.val) =
      readoutOffsets scheme sigma := by
  cases scheme
  · simp [compiledReadoutFlags, readoutOffsets, compiledDetectorCount]
  · simp [compiledReadoutFlags, readoutOffsets, compiledDetectorCount]
  · calc
      (compiledReadoutFlags Scheme.Shor sigma).map (fun f => f.val)
          = (List.finRange sigma.slots.length).map (fun a => a.val + 1) := by
            simp [compiledReadoutFlags, compiledDetectorCount]
      _ = ((List.finRange sigma.slots.length).map (fun a => a.val)).map Nat.succ := by
            rw [List.map_map]
            apply List.map_congr_left
            intro a
            simp [Nat.succ_eq_add_one]
      _ = (List.range sigma.slots.length).map Nat.succ := by
            rw [List.map_coe_finRange_eq_range]
      _ = readoutOffsets Scheme.Shor sigma := by
            rfl
  · simp [compiledReadoutFlags, readoutOffsets, compiledDetectorCount]

theorem detectorXor_foldl_eq_xorBools {nq : Nat} (slots : List Nat)
    (es : ErrorState nq) (init : Bool) :
    slots.foldl (fun acc slot => xor acc (es.detectors slot)) init =
      xor init (xorBools (slots.map fun slot => es.detectors slot)) := by
  induction slots generalizing init with
  | nil =>
      simp [xorBools]
  | cons slot rest ih =>
      simp [List.foldl, xorBools, ih]

theorem xorBools_map_detectors_eq_detectorXor {nq : Nat} (slots : List Nat)
    (es : ErrorState nq) :
    xorBools (slots.map fun slot => es.detectors slot) = detectorXor slots es := by
  unfold detectorXor
  rw [detectorXor_foldl_eq_xorBools]
  simp

theorem detectorXor_shifted_range_eq_fromAcc {nq : Nat} (start len : Nat)
    (es : ErrorState nq) :
    detectorXor ((List.range len).map fun i => start + i) es =
      detectorXorFromAcc start len es false := by
  induction len with
  | zero =>
      rfl
  | succ len ih =>
      simpa [detectorXor, List.range_succ, detectorXorFromAcc_succ_end, Nat.add_assoc] using ih

theorem xorBools_finRange_shift_eq_fromAcc {nq : Nat} (start len : Nat)
    (es : ErrorState nq) :
    xorBools ((List.finRange len).map fun f => es.detectors (start + f.val)) =
      detectorXorFromAcc start len es false := by
  calc
    xorBools ((List.finRange len).map fun f => es.detectors (start + f.val))
        = detectorXor ((List.finRange len).map fun f => start + f.val) es := by
          rw [← xorBools_map_detectors_eq_detectorXor]
          simp [List.map_map, Function.comp_def]
    _ = detectorXor ((List.range len).map fun i => start + i) es := by
          congr 1
          change List.map ((fun i : Nat => start + i) ∘ (fun f : Fin len => f.val))
              (List.finRange len) =
            List.map (fun i : Nat => start + i) (List.range len)
          rw [← List.map_map]
          rw [List.map_coe_finRange_eq_range]
    _ = detectorXorFromAcc start len es false :=
          detectorXor_shifted_range_eq_fromAcc start len es

theorem xorBools_finRange_shift_succ_eq_fromAcc {nq : Nat} (start len : Nat)
    (es : ErrorState nq) :
    xorBools ((List.finRange len).map fun f => es.detectors (start + (f.val + 1))) =
      detectorXorFromAcc (start + 1) len es false := by
  simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
    xorBools_finRange_shift_eq_fromAcc (start + 1) len es

theorem flagMeasZ_detector_cursor {nq : Nat} (anc : Fin nq) (es : ErrorState nq)
    (start : Nat) (hcursor : es.detectorCursor = start) :
    (propagateCircuit (eraseFaults (flagMeasZ anc)) es).detectors start =
      hasXComp (es.paulis anc) := by
  simp [flagMeasZ, eraseFaults, propagateCircuit, propagateGate, hcursor]

theorem flagTail_preserves_detector_at {nq : Nat} (flag : Fin nq) (es : ErrorState nq)
    (start : Nat) (hcursor : es.detectorCursor = start + 1) :
    (propagateCircuit (eraseFaults (hadamard flag ++ flagMeasZ flag)) es).detectors start =
      es.detectors start := by
  simp [hadamard, flagMeasZ, eraseFaults, propagateCircuit, propagateGate, hcursor]

/-- One-stabilizer PCC spec generated from one fresh compiled gadget.  The
stabilizer row is supplied by the source-side schedule elaborator; the circuit,
raw detector layout, postselection slots, and expected program are computed
from the compilation rule. -/
def singleGadgetCodeSpec {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli) :
    CodeSpec (n + helperCount scheme sigma) where
  numStab := 1
  numFlags := compiledDetectorCount scheme sigma
  isData := fun q => decide (q.val < n)
  stabilizer := fun _ => stab
  stabilizerReadout := fun _ => compiledReadoutFlags scheme sigma
  postselectFlag := compiledPostselectFlag scheme sigma
  flagSlot := fun i => i.val
  flagSlot_injective := by
    intro a b h
    exact Fin.ext h
  flagSlot_ordered := by
    intro i
    rfl
  readout_disjoint := by
    intro i j hij _ _ _
    exact hij (Subsingleton.elim i j)
  gadgetDetectorStart := fun _ => 0
  gadget := fun _ => compileFreshGadget scheme sigma
  expectedProgram := circuitView (compileFreshGadget scheme sigma)
  d := 1
  d_pos := by decide

/-- VCGen input generated from one fresh compiled gadget. -/
def singleGadgetVCInput {n : Nat} (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (hnq : 0 < n + helperCount scheme sigma) :
  VCInput (n + helperCount scheme sigma) :=
  VCInput.ofPCC (compileFreshGadget scheme sigma)
    (singleGadgetCodeSpec scheme sigma stab) .unconditional hnq
    (by simp [singleGadgetCodeSpec])

theorem singleGadget_stateOfData_eq_dataInputState {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (E : Fin (n + helperCount scheme sigma) → Pauli) :
    stateOfDataPauliAtDetector (singleGadgetCodeSpec scheme sigma stab) 0 E =
      dataInputState (k := helperCount scheme sigma)
        (fun q : Fin n => E (freshDataQ n (helperCount scheme sigma) q)) := by
  simp [stateOfDataPauliAtDetector, stateOfPauliAtDetector, singleGadgetCodeSpec,
    dataInputState]
  funext q
  by_cases hq : q.val < n
  · have hqeq :
      freshDataQ n (helperCount scheme sigma) ⟨q.val, hq⟩ = q := by
        exact Fin.ext rfl
    simp [dataOnlyPauli, hq, hqeq]
  · simp [dataOnlyPauli, hq]

theorem singleGadget_syndromeBit_eq_gadgetDetectorBit {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (es : ErrorState (n + helperCount scheme sigma)) :
    syndromeBit (singleGadgetCodeSpec scheme sigma stab) es
        ⟨0, by simp [singleGadgetCodeSpec]⟩ =
      gadgetDetectorBit scheme sigma es := by
  calc
    syndromeBit (singleGadgetCodeSpec scheme sigma stab) es
          ⟨0, by simp [singleGadgetCodeSpec]⟩
        = xorBools
            ((compiledReadoutFlags scheme sigma).map fun f => es.detectors f.val) := by
          rfl
    _ = xorBools ((readoutOffsets scheme sigma).map fun slot => es.detectors slot) := by
          rw [← compiledReadoutFlags_val scheme sigma]
          simp [List.map_map, Function.comp_def]
    _ = detectorXor (readoutOffsets scheme sigma) es := by
          exact xorBools_map_detectors_eq_detectorXor _ _

theorem compileFreshGadget_scheme_correct {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n) :
    GadgetDetectorCorrect scheme sigma := by
  cases scheme
  · exact compileFreshGadget_NZ_correct sigma
  · exact compileFreshGadget_Knill_correct sigma
  · exact compileFreshGadget_Shor_correct sigma
  · exact compileFreshGadget_Flag_correct sigma

/-! ## Schedule-derived stabilizer rows -/

/-- Singleton X/Z row for one scheduled source slot, embedded into a target
space with `k` fresh helper qubits. -/
def scheduleSlotRow {n k : Nat} (slot : ScheduledPauli n) : Fin (n + k) → Pauli :=
  fun q => if q = freshDataQ n k slot.qubit then slot.kind.toPauli else Pauli.I

/-- Stabilizer row denoted by an ordered X/Z source schedule.  Repeated slots
are interpreted by phase-free Pauli multiplication, so the row is well defined
even before imposing a no-duplicate well-formedness side condition. -/
def scheduleRow {n k : Nat} (sigma : RuleSchedule n) : Fin (n + k) → Pauli :=
  sigma.slots.foldl
    (fun acc slot => ErrorVec.mul acc (scheduleSlotRow (k := k) slot))
    (ErrorVec.identity (n + k))

theorem scheduleSlotRow_parity {n k : Nat} (slot : ScheduledPauli n)
    (E : Fin (n + k) → Pauli) :
    ErrorVec.parity (scheduleSlotRow (k := k) slot) E =
      anticommute slot.kind.toPauli (E (freshDataQ n k slot.qubit)) := by
  classical
  unfold ErrorVec.parity scheduleSlotRow
  rw [anticommute_eq_anticommutes]
  by_cases h :
      ErrorVec.Pauli.anticommutes slot.kind.toPauli (E (freshDataQ n k slot.qubit)) = true
  · have hfilter :
        (Finset.univ.filter fun q =>
          ErrorVec.Pauli.anticommutes
            (if q = freshDataQ n k slot.qubit then slot.kind.toPauli else Pauli.I)
            (E q)) =
          {freshDataQ n k slot.qubit} := by
        ext q
        by_cases hq : q = freshDataQ n k slot.qubit
        · subst q
          simp [h]
        · simp [hq]
    rw [hfilter]
    simpa using h
  · have hfalse :
      ErrorVec.Pauli.anticommutes slot.kind.toPauli
          (E (freshDataQ n k slot.qubit)) = false := by
        cases hbit :
          ErrorVec.Pauli.anticommutes slot.kind.toPauli
            (E (freshDataQ n k slot.qubit)) <;> simp_all
    have hfilter :
        (Finset.univ.filter fun q =>
          ErrorVec.Pauli.anticommutes
            (if q = freshDataQ n k slot.qubit then slot.kind.toPauli else Pauli.I)
            (E q)) =
          ∅ := by
        ext q
        by_cases hq : q = freshDataQ n k slot.qubit
        · subst q
          simp [hfalse]
        · simp [hq]
    rw [hfilter]
    simp [hfalse]

theorem scheduleRowList_parity {n k : Nat} (slots : List (ScheduledPauli n))
    (base : Fin (n + k) → Pauli) (E : Fin (n + k) → Pauli) :
    ErrorVec.parity
        (slots.foldl
          (fun acc slot => ErrorVec.mul acc (scheduleSlotRow (k := k) slot))
          base)
        E =
      slots.foldl
        (fun acc slot =>
          xor acc (anticommute slot.kind.toPauli (E (freshDataQ n k slot.qubit))))
        (ErrorVec.parity base E) := by
  induction slots generalizing base with
  | nil =>
      rfl
  | cons slot rest ih =>
      simp [List.foldl, ih, ErrorVec.parity_mul_left, scheduleSlotRow_parity]

theorem scheduleRow_parity {n k : Nat} (spec : CodeSpec (n + k)) (sigma : RuleSchedule n)
    (E : Fin (n + k) → Pauli) :
    parity spec (scheduleRow (k := k) sigma) E =
      scheduleParity sigma (fun q : Fin n => E (freshDataQ n k q)) := by
  cases sigma with
  | mk slots =>
      unfold parity scheduleParity scheduleRow
      rw [vectorParity_eq_parity]
      rw [scheduleRowList_parity]
      rw [ErrorVec.parity_identity_left]

theorem scheduleRow_vectorParity {n k : Nat} (sigma : RuleSchedule n)
    (E : Fin (n + k) → Pauli) :
    vectorParity (scheduleRow (k := k) sigma) E =
      scheduleParity sigma (fun q : Fin n => E (freshDataQ n k q)) := by
  cases sigma with
  | mk slots =>
      unfold scheduleParity scheduleRow
      rw [vectorParity_eq_parity]
      rw [scheduleRowList_parity]
      rw [ErrorVec.parity_identity_left]

/-- Semantic syndrome correctness for the generated one-gadget spec.  This is
the circuit-level part of the generated proof before it is packaged as a VCGen
slot. -/
theorem singleGadget_semantic_syn_of_scheduleParity {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (hParity :
      ∀ E : Fin (n + helperCount scheme sigma) → Pauli,
        parity (singleGadgetCodeSpec scheme sigma stab) stab E =
          scheduleParity sigma
            (fun q : Fin n => E (freshDataQ n (helperCount scheme sigma) q))):
    ∀ i E,
      gadgetMeasFlip (compileFreshGadget scheme sigma)
        (singleGadgetCodeSpec scheme sigma stab) i E =
        parity (singleGadgetCodeSpec scheme sigma stab)
          ((singleGadgetCodeSpec scheme sigma stab).stabilizer i) E := by
  intro i E
  have hval : i.val = 0 := by
    have hlt := i.isLt
    change i.val < 1 at hlt
    omega
  have hi : i = ⟨0, by simp [singleGadgetCodeSpec]⟩ := Fin.ext hval
  subst i
  unfold gadgetMeasFlip
  change
    syndromeBit (singleGadgetCodeSpec scheme sigma stab)
      (propagateCircuit (eraseFaults (compileFreshGadget scheme sigma))
        (stateOfDataPauliAtDetector (singleGadgetCodeSpec scheme sigma stab) 0 E))
      ⟨0, by simp [singleGadgetCodeSpec]⟩ =
        parity (singleGadgetCodeSpec scheme sigma stab) stab E
  rw [singleGadget_stateOfData_eq_dataInputState scheme sigma stab E]
  rw [singleGadget_syndromeBit_eq_gadgetDetectorBit scheme sigma stab]
  rw [compileFreshGadget_scheme_correct scheme sigma]
  exact (hParity E).symm

/-- The concrete generated `.syn` VC for one compiled stabilizer gadget follows
from the scheme correctness theorem and the generated row-parity obligation.
The parity obligation is the source-to-target stabilizer-row check: it states
that the declared QClifford row has exactly the same anticommutation parity as
the ordered QStab schedule on data qubits. -/
theorem singleGadget_vcgen_syn_of_scheduleParity {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (stab : Fin (n + helperCount scheme sigma) → Pauli)
    (hnq : 0 < n + helperCount scheme sigma)
    (hParity :
      ∀ E : Fin (n + helperCount scheme sigma) → Pauli,
        parity (singleGadgetCodeSpec scheme sigma stab) stab E =
          scheduleParity sigma
            (fun q : Fin n => E (freshDataQ n (helperCount scheme sigma) q))) :
    (vcgen (singleGadgetVCInput scheme sigma stab hnq)).denoteSlot .syn := by
  apply vcgen_syn_of_semantic_syn
  simpa [singleGadgetVCInput, VCInput.toCodeSpec_ofPCC] using
    singleGadget_semantic_syn_of_scheduleParity scheme sigma stab hParity

/-- Fully automatic generated `.syn` VC proof for one compiled stabilizer
instruction: the stabilizer row is computed from the source schedule itself. -/
theorem singleGadget_vcgen_syn {n : Nat}
    (scheme : Scheme) (sigma : RuleSchedule n)
    (hnq : 0 < n + helperCount scheme sigma) :
    (vcgen
      (singleGadgetVCInput scheme sigma
        (scheduleRow (k := helperCount scheme sigma) sigma) hnq)).denoteSlot .syn :=
  singleGadget_vcgen_syn_of_scheduleParity scheme sigma
    (scheduleRow (k := helperCount scheme sigma) sigma) hnq
    (by
      intro E
      exact scheduleRow_parity
        (singleGadgetCodeSpec scheme sigma
          (scheduleRow (k := helperCount scheme sigma) sigma))
        sigma E)

/-! ## XZProgram-level generated syndrome VCs -/

/-- One source stabilizer-measurement instruction after flattening an
`XZProgram`. -/
structure ProgramMeasure (n : Nat) where
  scheme : Scheme
  schedule : RuleSchedule n
  deriving Repr

def programMeasures {n : Nat} : XZProgram n → List (ProgramMeasure n)
  | .skip => []
  | .meas scheme schedule => [⟨scheme, schedule⟩]
  | .seq first second => programMeasures first ++ programMeasures second

def ProgramMeasure.synVCInput {n : Nat} (m : ProgramMeasure n)
    (hnq : 0 < n + helperCount m.scheme m.schedule) :
    VCInput (n + helperCount m.scheme m.schedule) :=
  singleGadgetVCInput m.scheme m.schedule
    (scheduleRow (k := helperCount m.scheme m.schedule) m.schedule) hnq

def ProgramMeasure.synVCDischarged {n : Nat} (m : ProgramMeasure n) : Prop :=
  ∀ hnq : 0 < n + helperCount m.scheme m.schedule,
    (vcgen (m.synVCInput hnq)).denoteSlot .syn

theorem ProgramMeasure.synVCDischarged_auto {n : Nat} (m : ProgramMeasure n) :
    m.synVCDischarged := by
  intro hnq
  cases m with
  | mk scheme schedule =>
      exact singleGadget_vcgen_syn scheme schedule hnq

/-- The generated `.syn` obligations for a source program are exactly the
flattened stabilizer measurements.  This predicate is intentionally phrased over
membership in `programMeasures`, so a producer cannot skip a source
instruction. -/
def programSynVCsDischarged {n : Nat} (program : XZProgram n) : Prop :=
  ∀ m, m ∈ programMeasures program → m.synVCDischarged

theorem programSynVCsDischarged_auto {n : Nat} :
    ∀ program : XZProgram n, programSynVCsDischarged program
  | .skip => by
      intro m hmem
      cases hmem
  | .meas scheme schedule => by
      intro m hmem
      simp [programMeasures] at hmem
      subst m
      exact ProgramMeasure.synVCDischarged_auto ⟨scheme, schedule⟩
  | .seq first second => by
      intro m hmem
      simp [programMeasures] at hmem ⊢
      rcases hmem with hmem | hmem
      · exact programSynVCsDischarged_auto first m hmem
      · exact programSynVCsDischarged_auto second m hmem

structure ProgramSynCertificate {n : Nat} (program : XZProgram n) where
  measures : List (ProgramMeasure n)
  measures_eq : measures = programMeasures program
  syn : ∀ m, m ∈ measures → m.synVCDischarged

/-- Automatically generated local `.syn` certificate package for every
stabilizer-measurement instruction in an `XZProgram`.  The proof is by
structural induction through `XZProgram.synVCsDischarged_auto`; each leaf is the
checked single-gadget VCGen `.syn` proof above. -/
def XZProgram.generatedSynCertificate {n : Nat} (program : XZProgram n) :
    ProgramSynCertificate program where
  measures := programMeasures program
  measures_eq := rfl
  syn := programSynVCsDischarged_auto program

structure ProgramCompilationSynCertificate {n : Nat} (program : XZProgram n) where
  circuit : FCircuit (n + programHelperCount program)
  deriv : ProgramCompileDeriv 0 program circuit
  syn : ProgramSynCertificate program

/-- Compiler-produced package for a full `XZProgram`: the concrete compiled
QClifford circuit, the compilation derivation tree, and the automatically
generated checked `.syn` VC proofs for every source stabilizer instruction. -/
def XZProgram.generatedCompilationSynCertificate {n : Nat} (program : XZProgram n) :
    ProgramCompilationSynCertificate program where
  circuit := compileProgram program
  deriv := compileProgramDeriv program
  syn := XZProgram.generatedSynCertificate program

/-! ## Monolithic full-program VC input skeleton -/

def programDetectorCount {n : Nat} : XZProgram n → Nat
  | .skip => 0
  | .meas scheme schedule => compiledDetectorCount scheme schedule
  | .seq first second => programDetectorCount first + programDetectorCount second

structure ProgramMeasureAt (n totalHelpers totalFlags : Nat) where
  scheme : Scheme
  schedule : RuleSchedule n
  helperStart : Nat
  detectorStart : Nat
  helperFit : helperStart + helperCount scheme schedule ≤ totalHelpers
  detectorFit : detectorStart + compiledDetectorCount scheme schedule ≤ totalFlags

def programMeasuresAtAux {n totalHelpers totalFlags : Nat} :
    (helperStart detectorStart : Nat) → (program : XZProgram n) →
      helperStart + programHelperCount program ≤ totalHelpers →
      detectorStart + programDetectorCount program ≤ totalFlags →
      List (ProgramMeasureAt n totalHelpers totalFlags)
  | _, _, .skip, _, _ => []
  | helperStart, detectorStart, .meas scheme schedule, helperFit, detectorFit =>
      [⟨scheme, schedule, helperStart, detectorStart, helperFit, detectorFit⟩]
  | helperStart, detectorStart, .seq first second, helperFit, detectorFit =>
      programMeasuresAtAux helperStart detectorStart first
        (by simp [programHelperCount] at helperFit ⊢; omega)
        (by simp [programDetectorCount] at detectorFit ⊢; omega) ++
      programMeasuresAtAux
        (helperStart + programHelperCount first)
        (detectorStart + programDetectorCount first)
        second
        (by simp [programHelperCount] at helperFit ⊢; omega)
        (by simp [programDetectorCount] at detectorFit ⊢; omega)

def programMeasuresAt {n : Nat} (program : XZProgram n) :
    List (ProgramMeasureAt n (programHelperCount program) (programDetectorCount program)) :=
  programMeasuresAtAux 0 0 program (by simp) (by simp)

def programNumStab {n : Nat} (program : XZProgram n) : Nat :=
  (programMeasuresAt program).length

def ProgramMeasureAt.shiftFlag {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags)
    (f : Fin (compiledDetectorCount m.scheme m.schedule)) : Fin totalFlags :=
  ⟨m.detectorStart + f.val, by
    have hf := f.isLt
    have hfit := m.detectorFit
    omega⟩

def ProgramMeasureAt.shiftedReadout {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) : List (Fin totalFlags) :=
  (compiledReadoutFlags m.scheme m.schedule).map m.shiftFlag

def ProgramMeasureAt.detectorEnd {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) : Nat :=
  m.detectorStart + compiledDetectorCount m.scheme m.schedule

def ProgramMeasureAt.detectorBefore {n totalHelpers totalFlags : Nat}
    (m₁ m₂ : ProgramMeasureAt n totalHelpers totalFlags) : Prop :=
  m₁.detectorEnd ≤ m₂.detectorStart

theorem ProgramMeasureAt.mem_shiftedReadout_bounds {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) {s : Fin totalFlags}
    (hs : s ∈ m.shiftedReadout) :
    m.detectorStart ≤ s.val ∧ s.val < m.detectorEnd := by
  rw [ProgramMeasureAt.shiftedReadout] at hs
  rcases List.mem_map.mp hs with ⟨localFlag, _hmem, rfl⟩
  constructor
  · simp [ProgramMeasureAt.shiftFlag]
  · simp [ProgramMeasureAt.shiftFlag, ProgramMeasureAt.detectorEnd]

theorem ProgramMeasureAt.shiftedReadout_disjoint_of_before {n totalHelpers totalFlags : Nat}
    (m₁ m₂ : ProgramMeasureAt n totalHelpers totalFlags)
    (hbefore : m₁.detectorBefore m₂) :
    ∀ s, s ∈ m₁.shiftedReadout → s ∈ m₂.shiftedReadout → False := by
  intro s hs₁ hs₂
  have h₁ := m₁.mem_shiftedReadout_bounds hs₁
  have h₂ := m₂.mem_shiftedReadout_bounds hs₂
  dsimp [ProgramMeasureAt.detectorBefore] at hbefore
  omega

theorem programMeasuresAtAux_within_detector {n totalHelpers totalFlags : Nat}
    (helperStart detectorStart : Nat) (program : XZProgram n)
    (helperFit : helperStart + programHelperCount program ≤ totalHelpers)
    (detectorFit : detectorStart + programDetectorCount program ≤ totalFlags) :
    ∀ m, m ∈ programMeasuresAtAux helperStart detectorStart program helperFit detectorFit →
      detectorStart ≤ m.detectorStart ∧
        m.detectorEnd ≤ detectorStart + programDetectorCount program := by
  induction program generalizing helperStart detectorStart with
  | skip =>
      intro m hmem
      simp [programMeasuresAtAux] at hmem
  | meas scheme schedule =>
      intro m hmem
      simp [programMeasuresAtAux] at hmem
      subst m
      constructor <;> simp [ProgramMeasureAt.detectorEnd, programDetectorCount]
  | seq first second ihFirst ihSecond =>
      intro m hmem
      simp [programMeasuresAtAux] at hmem
      rcases hmem with hmem | hmem
      · have hm :=
          ihFirst helperStart detectorStart
            (by simp [programHelperCount] at helperFit ⊢; omega)
            (by simp [programDetectorCount] at detectorFit ⊢; omega)
            m hmem
        constructor
        · exact hm.1
        · simp [programDetectorCount]
          omega
      · have hm :=
          ihSecond (helperStart + programHelperCount first)
            (detectorStart + programDetectorCount first)
            (by simp [programHelperCount] at helperFit ⊢; omega)
            (by simp [programDetectorCount] at detectorFit ⊢; omega)
            m hmem
        constructor
        · omega
        · simp [programDetectorCount]
          omega

theorem programMeasuresAtAux_pairwise_detectorBefore {n totalHelpers totalFlags : Nat}
    (helperStart detectorStart : Nat) (program : XZProgram n)
    (helperFit : helperStart + programHelperCount program ≤ totalHelpers)
    (detectorFit : detectorStart + programDetectorCount program ≤ totalFlags) :
    List.Pairwise ProgramMeasureAt.detectorBefore
      (programMeasuresAtAux helperStart detectorStart program helperFit detectorFit) := by
  induction program generalizing helperStart detectorStart with
  | skip =>
      simp [programMeasuresAtAux]
  | meas scheme schedule =>
      simp [programMeasuresAtAux]
  | seq first second ihFirst ihSecond =>
      simp [programMeasuresAtAux, List.pairwise_append]
      constructor
      · exact ihFirst helperStart detectorStart
          (by simp [programHelperCount] at helperFit ⊢; omega)
          (by simp [programDetectorCount] at detectorFit ⊢; omega)
      constructor
      · exact ihSecond (helperStart + programHelperCount first)
          (detectorStart + programDetectorCount first)
          (by simp [programHelperCount] at helperFit ⊢; omega)
          (by simp [programDetectorCount] at detectorFit ⊢; omega)
      · intro a ha b hb
        have haBounds :=
          programMeasuresAtAux_within_detector helperStart detectorStart first
            (by simp [programHelperCount] at helperFit ⊢; omega)
            (by simp [programDetectorCount] at detectorFit ⊢; omega)
            a ha
        have hbBounds :=
          programMeasuresAtAux_within_detector
            (helperStart + programHelperCount first)
            (detectorStart + programDetectorCount first)
            second
            (by simp [programHelperCount] at helperFit ⊢; omega)
            (by simp [programDetectorCount] at detectorFit ⊢; omega)
            b hb
        dsimp [ProgramMeasureAt.detectorBefore]
        omega

theorem programMeasuresAt_pairwise_detectorBefore {n : Nat} (program : XZProgram n) :
    List.Pairwise ProgramMeasureAt.detectorBefore (programMeasuresAt program) := by
  exact programMeasuresAtAux_pairwise_detectorBefore 0 0 program (by simp) (by simp)

def ProgramMeasureAt.localPostselectedAt {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) (f : Fin totalFlags) : Bool :=
  (List.finRange (compiledDetectorCount m.scheme m.schedule)).any fun localFlag =>
    decide (f = m.shiftFlag localFlag) && compiledPostselectFlag m.scheme m.schedule localFlag

def fullProgramPostselectFlag {n : Nat} (program : XZProgram n)
    (f : Fin (programDetectorCount program)) : Bool :=
  (programMeasuresAt program).any fun m => m.localPostselectedAt f

def fullProgramReadoutDisjoint {n : Nat} (program : XZProgram n) : Prop :=
  ∀ i j : Fin (programNumStab program), i ≠ j → ∀ s,
    s ∈ ((programMeasuresAt program).get i).shiftedReadout →
    s ∈ ((programMeasuresAt program).get j).shiftedReadout →
    False

theorem fullProgramReadoutDisjoint_auto {n : Nat} (program : XZProgram n) :
    fullProgramReadoutDisjoint program := by
  intro i j hij s hsᵢ hsⱼ
  have hpair := programMeasuresAt_pairwise_detectorBefore program
  by_cases hijlt : i < j
  · have hbefore := (List.pairwise_iff_get.mp hpair) i j hijlt
    exact ProgramMeasureAt.shiftedReadout_disjoint_of_before
      ((programMeasuresAt program).get i) ((programMeasuresAt program).get j)
      hbefore s hsᵢ hsⱼ
  · have hjilt : j < i := by
      have hneVal : i.val ≠ j.val := by
        intro hval
        exact hij (Fin.ext hval)
      omega
    have hbefore := (List.pairwise_iff_get.mp hpair) j i hjilt
    exact ProgramMeasureAt.shiftedReadout_disjoint_of_before
      ((programMeasuresAt program).get j) ((programMeasuresAt program).get i)
      hbefore s hsⱼ hsᵢ

def fullProgramCodeSpec {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program) :
    CodeSpec (n + programHelperCount program) where
  numStab := programNumStab program
  numFlags := programDetectorCount program
  isData := fun q => decide (q.val < n)
  stabilizer := fun i =>
    scheduleRow (k := programHelperCount program) ((programMeasuresAt program).get i).schedule
  stabilizerReadout := fun i => ((programMeasuresAt program).get i).shiftedReadout
  postselectFlag := fullProgramPostselectFlag program
  flagSlot := fun i => i.val
  flagSlot_injective := by
    intro a b h
    exact Fin.ext h
  flagSlot_ordered := by
    intro i
    rfl
  readout_disjoint := hdisjoint
  gadgetDetectorStart := fun i => ((programMeasuresAt program).get i).detectorStart
  gadget := fun i =>
    let m := (programMeasuresAt program).get i
    compileGadgetBlock m.scheme m.schedule m.helperStart m.helperFit
  expectedProgram := circuitView (compileProgram program)
  d := 1
  d_pos := by decide

theorem finRange_flatMap_get {α β : Type} (xs : List α) (f : α → List β) :
    (List.finRange xs.length).flatMap (fun i => f (xs.get i)) = xs.flatMap f := by
  rw [← List.flatMap_map]
  rw [← List.ofFn_eq_map]
  rw [List.ofFn_get]

theorem compileProgramAux_eq_flatMap_programMeasuresAtAux
    {n totalHelpers totalFlags : Nat}
    (helperStart detectorStart : Nat) (program : XZProgram n)
    (helperFit : helperStart + programHelperCount program ≤ totalHelpers)
    (detectorFit : detectorStart + programDetectorCount program ≤ totalFlags) :
    compileProgramAux helperStart program helperFit =
      (programMeasuresAtAux helperStart detectorStart program helperFit detectorFit).flatMap
        (fun m => compileGadgetBlock m.scheme m.schedule m.helperStart m.helperFit) := by
  induction program generalizing helperStart detectorStart with
  | skip =>
      simp [compileProgramAux, programMeasuresAtAux]
  | meas scheme schedule =>
      simp [compileProgramAux, programMeasuresAtAux]
  | seq first second ihFirst ihSecond =>
      simp [compileProgramAux, programMeasuresAtAux, List.flatMap_append]
      rw [ihFirst helperStart detectorStart]
      rw [ihSecond (helperStart + programHelperCount first)
        (detectorStart + programDetectorCount first)]

theorem compileProgram_eq_programMeasuresAt_flatMap {n : Nat} (program : XZProgram n) :
    compileProgram program =
      (programMeasuresAt program).flatMap
        (fun m => compileGadgetBlock m.scheme m.schedule m.helperStart m.helperFit) := by
  exact compileProgramAux_eq_flatMap_programMeasuresAtAux 0 0 program (by simp) (by simp)

theorem specCircuit_fullProgramCodeSpec {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program) :
    specCircuit (fullProgramCodeSpec program hdisjoint) = compileProgram program := by
  unfold specCircuit fullProgramCodeSpec programNumStab
  let f : ProgramMeasureAt n (programHelperCount program) (programDetectorCount program) →
      FCircuit (n + programHelperCount program) :=
    fun m => compileGadgetBlock m.scheme m.schedule m.helperStart m.helperFit
  have hget := finRange_flatMap_get (programMeasuresAt program) f
  change (List.finRange (programMeasuresAt program).length).flatMap
      (fun i => f ((programMeasuresAt program).get i)) = compileProgram program
  rw [hget]
  exact (compileProgram_eq_programMeasuresAt_flatMap program).symm

@[simp] theorem dataOnlyPauli_fullProgramCodeSpec {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program)
    (E : Fin (n + programHelperCount program) → Pauli)
    (q : Fin (n + programHelperCount program)) :
    dataOnlyPauli (fullProgramCodeSpec program hdisjoint) E q =
      if decide (q.val < n) then E q else Pauli.I := by
  simp [dataOnlyPauli, fullProgramCodeSpec]

def fullProgramVCInput {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    VCInput (n + programHelperCount program) :=
  VCInput.ofPCC (compileProgram program) (fullProgramCodeSpec program hdisjoint)
    .unconditional hnq hnumStab

theorem fullProgram_vcgen_programEq {n : Nat}
    (program : XZProgram n) (hdisjoint : fullProgramReadoutDisjoint program)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    (vcgen (fullProgramVCInput program hdisjoint hnq hnumStab)).denoteSlot .programEq := by
  simpa [vcgen, GeneratedVCs.denoteSlot, VCSlot.denote, fullProgramVCInput,
    VCInput.toCodeSpec_ofPCC] using
    (specCircuit_fullProgramCodeSpec program hdisjoint).symm

theorem fullProgram_vcgen_wf {n : Nat}
    (program : XZProgram n) (hdisjoint : fullProgramReadoutDisjoint program)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    (vcgen (fullProgramVCInput program hdisjoint hnq hnumStab)).denoteSlot .wf := by
  change WellFormed (compileProgram program) (fullProgramCodeSpec program hdisjoint)
  rfl

def fullProgramEmbeddedSynCorrect {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program) : Prop :=
  ∀ i E,
    gadgetMeasFlip (compileProgram program) (fullProgramCodeSpec program hdisjoint) i E =
      parity (fullProgramCodeSpec program hdisjoint)
        ((fullProgramCodeSpec program hdisjoint).stabilizer i) E

def ProgramMeasureAt.embeddedDetectorBit {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) (es : ErrorState (n + totalHelpers)) :
    Bool :=
  xorBools (m.shiftedReadout.map fun f => es.detectors f.val)

def ProgramMeasureAt.dataOnlyStateAtDetector {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags)
    (E : Fin (n + totalHelpers) → Pauli) : ErrorState (n + totalHelpers) :=
  stateOfPauliAtDetector m.detectorStart
    (fun q => if decide (q.val < n) then E q else Pauli.I)

theorem freshDataQ_ne_blockHelperQ {n total start width : Nat}
    (hfit : start + width ≤ total) (q : Fin n) (a : Fin width) :
    freshDataQ n total q ≠ blockHelperQ n total start width hfit a := by
  intro h
  have hv := congrArg Fin.val h
  simp [freshDataQ, blockHelperQ] at hv
  have hq := q.isLt
  omega

theorem blockShorCat_nodup {n total start w : Nat}
    (hfit : start + (w + 1) ≤ total) :
    (blockShorCat n total start w hfit).Nodup := by
  unfold blockShorCat
  refine List.Nodup.map ?_ (List.nodup_finRange w)
  intro a b h
  apply Fin.ext
  have hv := congrArg Fin.val h
  simp [blockHelperQ] at hv
  omega

theorem mem_blockShorCat_helper {n total start w : Nat}
    (hfit : start + (w + 1) ≤ total) {q : Fin (n + total)}
    (hmem : q ∈ blockShorCat n total start w hfit) :
    ∃ a : Fin w,
      q =
        blockHelperQ n total start (w + 1) hfit
          ⟨a.val, by exact Nat.lt_trans a.isLt (Nat.lt_succ_self w)⟩ := by
  have hmem' :
      q ∈ (List.finRange w).map (fun a =>
        blockHelperQ n total start (w + 1) hfit
          ⟨a.val, by exact Nat.lt_trans a.isLt (Nat.lt_succ_self w)⟩) := by
    simpa [blockShorCat] using hmem
  rcases List.mem_map.mp hmem' with ⟨a, _ha, rfl⟩
  exact ⟨a, rfl⟩

@[simp] theorem ProgramMeasureAt.dataOnlyStateAtDetector_freshDataQ
    {n totalHelpers totalFlags : Nat} (m : ProgramMeasureAt n totalHelpers totalFlags)
    (E : Fin (n + totalHelpers) → Pauli) (q : Fin n) :
    (m.dataOnlyStateAtDetector E).paulis (freshDataQ n totalHelpers q) =
      E (freshDataQ n totalHelpers q) := by
  simp [ProgramMeasureAt.dataOnlyStateAtDetector, stateOfPauliAtDetector,
    freshDataQ]

@[simp] theorem ProgramMeasureAt.dataOnlyStateAtDetector_blockHelperQ
    {n totalHelpers totalFlags start width : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags)
    (E : Fin (n + totalHelpers) → Pauli)
    (hfit : start + width ≤ totalHelpers) (a : Fin width) :
    (m.dataOnlyStateAtDetector E).paulis (blockHelperQ n totalHelpers start width hfit a) =
      Pauli.I := by
  have hnot : ¬ (blockHelperQ n totalHelpers start width hfit a).val < n := by
    simp [blockHelperQ]
    omega
  simp [ProgramMeasureAt.dataOnlyStateAtDetector, stateOfPauliAtDetector,
    hnot]

@[simp] theorem ProgramMeasureAt.dataOnlyStateAtDetector_cursor
    {n totalHelpers totalFlags : Nat} (m : ProgramMeasureAt n totalHelpers totalFlags)
    (E : Fin (n + totalHelpers) → Pauli) :
    (m.dataOnlyStateAtDetector E).detectorCursor = m.detectorStart := by
  simp [ProgramMeasureAt.dataOnlyStateAtDetector, stateOfPauliAtDetector]

def ProgramMeasureAt.embeddedSynCorrect {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) : Prop :=
  ∀ E : Fin (n + totalHelpers) → Pauli,
    m.embeddedDetectorBit
        (propagateCircuit (eraseFaults (compileGadgetBlock m.scheme m.schedule
          m.helperStart m.helperFit)) (m.dataOnlyStateAtDetector E)) =
      vectorParity (scheduleRow (k := totalHelpers) m.schedule) E

def ProgramMeasureAt.embeddedBlockCircuit {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) : Circuit (n + totalHelpers) :=
  eraseFaults (compileGadgetBlock m.scheme m.schedule m.helperStart m.helperFit)

def ProgramMeasureAt.embeddedDetectorPre {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) :
    QHL.Target.AssertionC (n + totalHelpers) :=
  fun es => ∃ E : Fin (n + totalHelpers) → Pauli, es = m.dataOnlyStateAtDetector E

def ProgramMeasureAt.embeddedDetectorPost {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) :
    QHL.Target.AssertionC (n + totalHelpers) :=
  fun es =>
    ∀ E : Fin (n + totalHelpers) → Pauli,
      es = propagateCircuit m.embeddedBlockCircuit (m.dataOnlyStateAtDetector E) →
        m.embeddedDetectorBit es =
          vectorParity (scheduleRow (k := totalHelpers) m.schedule) E

def ProgramMeasureAt.embeddedDetectorWPDeriv {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) :
    QHL.Target.DerivC (n + totalHelpers)
      (fun es => m.embeddedDetectorPost (propagateCircuit m.embeddedBlockCircuit es))
      m.embeddedBlockCircuit
      m.embeddedDetectorPost :=
  circuitWPDeriv m.embeddedBlockCircuit m.embeddedDetectorPost

/-- A real target Hoare derivation certificate for one embedded compiled
stabilizer block.  The derivation itself is produced by the QClifford WP rules;
the only non-syntactic side condition is the standard consequence proof that
the generated precondition implies the generated weakest precondition. -/
structure ProgramMeasureAt.EmbeddedHoareCertificate {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) where
  pre_implies_wp :
    ∀ es,
      m.embeddedDetectorPre es →
        m.embeddedDetectorPost (propagateCircuit m.embeddedBlockCircuit es)
  deriv :
    QHL.Target.DerivC (n + totalHelpers)
      m.embeddedDetectorPre
      m.embeddedBlockCircuit
      m.embeddedDetectorPost :=
    QHL.Target.DerivC.C_Consequence
      m.embeddedDetectorWPDeriv
      pre_implies_wp
      (fun _ h => h)

theorem ProgramMeasureAt.EmbeddedHoareCertificate.to_embeddedSynCorrect
    {n totalHelpers totalFlags : Nat}
    {m : ProgramMeasureAt n totalHelpers totalFlags}
    (cert : m.EmbeddedHoareCertificate) :
    m.embeddedSynCorrect := by
  intro E
  have hHoare := QHL.Target.hoare_sound_c cert.deriv
  have hPost :=
    hHoare
      (m.dataOnlyStateAtDetector E)
      (propagateCircuit m.embeddedBlockCircuit (m.dataOnlyStateAtDetector E))
      (QHL.Target.cevalC_of_propagateCircuit m.embeddedBlockCircuit
        (m.dataOnlyStateAtDetector E))
      ⟨E, rfl⟩
  simpa [ProgramMeasureAt.embeddedSynCorrect,
    ProgramMeasureAt.embeddedDetectorPost, ProgramMeasureAt.embeddedBlockCircuit]
    using hPost E rfl

def ProgramMeasureAt.embeddedHoareCertificateOfCorrect {n totalHelpers totalFlags : Nat}
    {m : ProgramMeasureAt n totalHelpers totalFlags}
    (hcorrect : m.embeddedSynCorrect) :
    m.EmbeddedHoareCertificate where
  pre_implies_wp := by
    intro es hpre
    rcases hpre with ⟨E0, rfl⟩
    intro E hEq
    rw [hEq]
    exact hcorrect E

theorem ProgramMeasureAt.embeddedSynCorrect_of_detector {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags)
    (hdet :
      ∀ E : Fin (n + totalHelpers) → Pauli,
        m.embeddedDetectorBit
            (propagateCircuit (eraseFaults (compileGadgetBlock m.scheme m.schedule
              m.helperStart m.helperFit)) (m.dataOnlyStateAtDetector E)) =
          scheduleParity m.schedule (fun q : Fin n => E (freshDataQ n totalHelpers q))) :
    m.embeddedSynCorrect := by
  intro E
  rw [hdet E, scheduleRow_vectorParity]

theorem ProgramMeasureAt.embeddedSynCorrect_NZ {n totalHelpers totalFlags : Nat}
    (sigma : RuleSchedule n) (helperStart detectorStart : Nat)
    (helperFit : helperStart + helperCount .NZ sigma ≤ totalHelpers)
    (detectorFit : detectorStart + compiledDetectorCount .NZ sigma ≤ totalFlags) :
    (⟨.NZ, sigma, helperStart, detectorStart, helperFit, detectorFit⟩ :
      ProgramMeasureAt n totalHelpers totalFlags).embeddedSynCorrect := by
  apply ProgramMeasureAt.embeddedSynCorrect_of_detector
  intro E
  let m : ProgramMeasureAt n totalHelpers totalFlags :=
    ⟨.NZ, sigma, helperStart, detectorStart, helperFit, detectorFit⟩
  let anc : Fin (n + totalHelpers) :=
    blockHelperQ n totalHelpers helperStart 1 helperFit ⟨0, by decide⟩
  let slots : List (ScheduledPauli (n + totalHelpers)) := (liftSchedule (k := totalHelpers) sigma).slots
  let es0 : ErrorState (n + totalHelpers) := m.dataOnlyStateAtDetector E
  let globalE : Fin (n + totalHelpers) → Pauli := fun q => es0.paulis q
  let esPrep := propagateCircuit (eraseFaults (prep0 anc)) es0
  let esSlots := propagateCircuit (eraseFaults (zParitySlotsCircuit anc slots)) esPrep
  have hprep := prep0_state_for_chain anc es0
  have hne : ∀ slot, slot ∈ slots → slot.qubit ≠ anc := by
    intro slot hmem
    have hmem' : slot ∈ sigma.slots.map (liftSlot (k := totalHelpers)) := by
      simpa [slots, liftSchedule] using hmem
    rcases List.mem_map.mp hmem' with ⟨src, _hsrc, rfl⟩
    simpa [anc, liftSlot] using
      (freshDataQ_ne_blockHelperQ (n := n) (total := totalHelpers)
        (start := helperStart) (width := 1) helperFit src.qubit ⟨0, by decide⟩)
  have hdata : ∀ q : Fin (n + totalHelpers), q ≠ anc → esPrep.paulis q = globalE q := by
    intro q hq
    simpa [globalE, es0, esPrep] using hprep.2.1 q hq
  have hanc : esPrep.paulis anc = xOfBool false := by
    simpa [esPrep] using hprep.1
  have hchain := zParitySlotsCircuit_chain anc slots globalE false esPrep hne hdata hanc
  have hread := zParitySlotsCircuit_preserves_readout anc slots esPrep
  have hcursorPrep : esPrep.detectorCursor = detectorStart := by
    calc
      esPrep.detectorCursor = es0.detectorCursor := by
        simpa [esPrep] using hprep.2.2.2
      _ = detectorStart := by simp [es0, m]
  have hcursorSlots : esSlots.detectorCursor = detectorStart := by
    calc
      esSlots.detectorCursor = esPrep.detectorCursor := by
        simpa [esSlots] using hread.2
      _ = detectorStart := hcursorPrep
  have hglobal :
      globalE =
        fun q : Fin (n + totalHelpers) =>
          (dataInputState (k := totalHelpers)
            (fun q : Fin n => E (freshDataQ n totalHelpers q))).paulis q := by
    funext q
    by_cases hq : q.val < n
    · have hqeq : freshDataQ n totalHelpers ⟨q.val, hq⟩ = q := Fin.ext rfl
      simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
        stateOfPauliAtDetector, dataInputState, hq, hqeq]
    · simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
        stateOfPauliAtDetector, dataInputState, hq]
  have hparity :
      scheduleParityList slots globalE false =
        scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
    rw [hglobal]
    simpa [slots] using
      scheduleParityList_liftSchedule (k := totalHelpers) sigma
        (fun q : Fin n => E (freshDataQ n totalHelpers q))
  have hancSlots :
      esSlots.paulis anc = xOfBool (scheduleParityList slots globalE false) := by
    simpa [esSlots] using hchain.1
  have hfinal :
      (propagateCircuit (eraseFaults (flagMeasZ anc)) esSlots).detectors detectorStart =
        scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
    calc
      (propagateCircuit (eraseFaults (flagMeasZ anc)) esSlots).detectors detectorStart
          = hasXComp (esSlots.paulis anc) := flagMeasZ_detector_cursor anc esSlots
              detectorStart hcursorSlots
      _ = hasXComp (xOfBool (scheduleParityList slots globalE false)) := by rw [hancSlots]
      _ = scheduleParityList slots globalE false := by simp
      _ = scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := hparity
  have hcompiled :
      propagateCircuit (eraseFaults (compileGadgetBlock .NZ sigma helperStart helperFit)) es0 =
        propagateCircuit (eraseFaults (flagMeasZ anc)) esSlots := by
    simp [compileGadgetBlock, compileGadgetOrdered, compileStandardOrdered,
      blockAncillaConfig, anc, slots, esPrep, esSlots, zParitySlotsCircuit, eraseFaults_append,
      QHL.Target.propagateCircuit_append]
  change
    m.embeddedDetectorBit
        (propagateCircuit (eraseFaults (compileGadgetBlock .NZ sigma helperStart helperFit)) es0) =
      scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q))
  rw [hcompiled]
  simpa [m, ProgramMeasureAt.embeddedDetectorBit, ProgramMeasureAt.shiftedReadout,
    compiledReadoutFlags, compiledDetectorCount, ProgramMeasureAt.shiftFlag, xorBools]
    using hfinal

theorem ProgramMeasureAt.embeddedSynCorrect_Knill {n totalHelpers totalFlags : Nat}
    (sigma : RuleSchedule n) (helperStart detectorStart : Nat)
    (helperFit : helperStart + helperCount .Knill sigma ≤ totalHelpers)
    (detectorFit : detectorStart + compiledDetectorCount .Knill sigma ≤ totalFlags) :
    (⟨.Knill, sigma, helperStart, detectorStart, helperFit, detectorFit⟩ :
      ProgramMeasureAt n totalHelpers totalFlags).embeddedSynCorrect := by
  apply ProgramMeasureAt.embeddedSynCorrect_of_detector
  intro E
  let m : ProgramMeasureAt n totalHelpers totalFlags :=
    ⟨.Knill, sigma, helperStart, detectorStart, helperFit, detectorFit⟩
  let w : Nat := sigma.slots.length
  let slots : List (ScheduledPauli (n + totalHelpers)) :=
    (liftSchedule (k := totalHelpers) sigma).slots
  let ancillas : List (Fin (n + totalHelpers)) :=
    blockHelpers n totalHelpers helperStart w helperFit
  let pairs : List (ScheduledPauli (n + totalHelpers) × Fin (n + totalHelpers)) :=
    List.zip slots ancillas
  let es0 : ErrorState (n + totalHelpers) := m.dataOnlyStateAtDetector E
  let globalE : Fin (n + totalHelpers) → Pauli := fun q => es0.paulis q
  have hslot_mem :
      ∀ slot, slot ∈ slots →
        ∃ src, src ∈ sigma.slots ∧ slot = liftSlot (k := totalHelpers) src := by
    intro slot hmem
    have hmem' : slot ∈ sigma.slots.map (liftSlot (k := totalHelpers)) := by
      simpa [slots, liftSchedule] using hmem
    rcases List.mem_map.mp hmem' with ⟨src, hsrc, rfl⟩
    exact ⟨src, hsrc, rfl⟩
  have hanc_mem :
      ∀ anc, anc ∈ ancillas → ∃ a : Fin w, anc = blockHelperQ n totalHelpers helperStart w helperFit a := by
    intro anc hmem
    have hmem' :
        anc ∈ (List.finRange w).map (blockHelperQ n totalHelpers helperStart w helperFit) := by
      simpa [ancillas, blockHelpers] using hmem
    rcases List.mem_map.mp hmem' with ⟨a, _ha, rfl⟩
    exact ⟨a, rfl⟩
  have hslot_ne_anc :
      ∀ slotPair, slotPair ∈ pairs →
        ∀ ancPair, ancPair ∈ pairs → slotPair.1.qubit ≠ ancPair.2 := by
    intro slotPair hslotPair ancPair hancPair
    have hs_mem : slotPair.1 ∈ slots := (List.of_mem_zip hslotPair).1
    have ha_mem : ancPair.2 ∈ ancillas := (List.of_mem_zip hancPair).2
    rcases hslot_mem slotPair.1 hs_mem with ⟨src, _hsrc, hsrcEq⟩
    rcases hanc_mem ancPair.2 ha_mem with ⟨a, haEq⟩
    rw [hsrcEq, haEq]
    simpa [liftSlot] using
      (freshDataQ_ne_blockHelperQ (n := n) (total := totalHelpers)
        (start := helperStart) (width := w) helperFit src.qubit a)
  have hself : ∀ pair, pair ∈ pairs → pair.1.qubit ≠ pair.2 := by
    intro pair hmem
    exact hslot_ne_anc pair hmem pair hmem
  have hdata : ∀ pair, pair ∈ pairs → es0.paulis pair.1.qubit = globalE pair.1.qubit := by
    intro pair _hmem
    rfl
  have hcursor : es0.detectorCursor = detectorStart := by
    simp [es0, m]
  have hchain :=
    knillPairsCircuit_chain pairs globalE false es0 detectorStart hcursor hdata hself hslot_ne_anc
  have hpairs_len : pairs.length = w := by
    simp [pairs, slots, ancillas, blockHelpers, liftSchedule, w]
  have hslots_le_ancillas : slots.length ≤ ancillas.length := by
    simp [slots, ancillas, blockHelpers, liftSchedule, w]
  have hmapPairs : pairs.map Prod.fst = slots := by
    simpa [pairs] using List.map_fst_zip hslots_le_ancillas
  have hglobal :
      globalE =
        fun q : Fin (n + totalHelpers) =>
          (dataInputState (k := totalHelpers)
            (fun q : Fin n => E (freshDataQ n totalHelpers q))).paulis q := by
    funext q
    by_cases hq : q.val < n
    · have hqeq : freshDataQ n totalHelpers ⟨q.val, hq⟩ = q := Fin.ext rfl
      simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
        stateOfPauliAtDetector, dataInputState, hq, hqeq]
    · simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
        stateOfPauliAtDetector, dataInputState, hq]
  have hparity :
      scheduleParityList (pairs.map Prod.fst) globalE false =
        scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
    rw [hmapPairs, hglobal]
    simpa [slots] using
      scheduleParityList_liftSchedule (k := totalHelpers) sigma
        (fun q : Fin n => E (freshDataQ n totalHelpers q))
  have hcompiled :
      propagateCircuit (eraseFaults (compileGadgetBlock .Knill sigma helperStart helperFit)) es0 =
        propagateCircuit (eraseFaults (knillPairsCircuit pairs)) es0 := by
    simp [compileGadgetBlock, compileGadgetOrdered, compileKnillOrdered,
      blockAncillaConfig, blockHelpers, knillPairsCircuit, pairs, slots, ancillas, w]
  change
    m.embeddedDetectorBit
        (propagateCircuit (eraseFaults (compileGadgetBlock .Knill sigma helperStart helperFit)) es0) =
      scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q))
  rw [hcompiled]
  calc
    m.embeddedDetectorBit (propagateCircuit (eraseFaults (knillPairsCircuit pairs)) es0)
        = detectorXorFromAcc detectorStart w
            (propagateCircuit (eraseFaults (knillPairsCircuit pairs)) es0) false := by
          simp [m, ProgramMeasureAt.embeddedDetectorBit, ProgramMeasureAt.shiftedReadout,
            compiledReadoutFlags, compiledDetectorCount, ProgramMeasureAt.shiftFlag,
            xorBools_finRange_shift_eq_fromAcc, Function.comp_def, w]
    _ = detectorXorFromAcc detectorStart pairs.length
            (propagateCircuit (eraseFaults (knillPairsCircuit pairs)) es0) false := by
          rw [hpairs_len]
    _ = scheduleParityList (pairs.map Prod.fst) globalE false := hchain.1
    _ = scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := hparity

theorem ProgramMeasureAt.embeddedSynCorrect_Flag {n totalHelpers totalFlags : Nat}
    (sigma : RuleSchedule n) (helperStart detectorStart : Nat)
    (helperFit : helperStart + helperCount .Flag sigma ≤ totalHelpers)
    (detectorFit : detectorStart + compiledDetectorCount .Flag sigma ≤ totalFlags) :
    (⟨.Flag, sigma, helperStart, detectorStart, helperFit, detectorFit⟩ :
      ProgramMeasureAt n totalHelpers totalFlags).embeddedSynCorrect := by
  apply ProgramMeasureAt.embeddedSynCorrect_of_detector
  intro E
  let m : ProgramMeasureAt n totalHelpers totalFlags :=
    ⟨.Flag, sigma, helperStart, detectorStart, helperFit, detectorFit⟩
  let anc : Fin (n + totalHelpers) :=
    blockHelperQ n totalHelpers helperStart 2 helperFit ⟨0, by decide⟩
  let flg : Fin (n + totalHelpers) :=
    blockHelperQ n totalHelpers helperStart 2 helperFit ⟨1, by decide⟩
  let slots : List (ScheduledPauli (n + totalHelpers)) :=
    (liftSchedule (k := totalHelpers) sigma).slots
  let half : Nat := slots.length / 2
  let first := slots.take half
  let second := slots.drop half
  let es0 : ErrorState (n + totalHelpers) := m.dataOnlyStateAtDetector E
  let globalE : Fin (n + totalHelpers) → Pauli := fun q => es0.paulis q
  let esPrepA := propagateCircuit (eraseFaults (prep0 anc)) es0
  let esPrepF := propagateCircuit (eraseFaults (prepP flg)) esPrepA
  let esFirst := propagateCircuit (eraseFaults (zParitySlotsCircuit anc first)) esPrepF
  let esFlag1 := propagateCircuit (eraseFaults (cnot flg anc)) esFirst
  let esSecond := propagateCircuit (eraseFaults (zParitySlotsCircuit anc second)) esFlag1
  let esFlag2 := propagateCircuit (eraseFaults (cnot flg anc)) esSecond
  let esSynd := propagateCircuit (eraseFaults (flagMeasZ anc)) esFlag2
  have hprepA := prep0_state_for_chain anc es0
  have hprepF := prepP_state_for_chain flg esPrepA
  have hanc_ne_flg : anc ≠ flg := by
    intro h
    have hv := congrArg Fin.val h
    simp [anc, flg, blockHelperQ] at hv
  have hflg_ne_anc : flg ≠ anc := fun h => hanc_ne_flg h.symm
  have hslots_ne_anc : ∀ slot, slot ∈ slots → slot.qubit ≠ anc := by
    intro slot hmem
    have hmem' : slot ∈ sigma.slots.map (liftSlot (k := totalHelpers)) := by
      simpa [slots, liftSchedule] using hmem
    rcases List.mem_map.mp hmem' with ⟨src, _hsrc, rfl⟩
    simpa [anc, liftSlot] using
      (freshDataQ_ne_blockHelperQ (n := n) (total := totalHelpers)
        (start := helperStart) (width := 2) helperFit src.qubit ⟨0, by decide⟩)
  have hslots_ne_flg : ∀ slot, slot ∈ slots → slot.qubit ≠ flg := by
    intro slot hmem
    have hmem' : slot ∈ sigma.slots.map (liftSlot (k := totalHelpers)) := by
      simpa [slots, liftSchedule] using hmem
    rcases List.mem_map.mp hmem' with ⟨src, _hsrc, rfl⟩
    simpa [flg, liftSlot] using
      (freshDataQ_ne_blockHelperQ (n := n) (total := totalHelpers)
        (start := helperStart) (width := 2) helperFit src.qubit ⟨1, by decide⟩)
  have hfirst_ne_anc : ∀ slot, slot ∈ first → slot.qubit ≠ anc := by
    intro slot hmem
    exact hslots_ne_anc slot (by simpa [first] using List.mem_of_mem_take hmem)
  have hsecond_ne_anc : ∀ slot, slot ∈ second → slot.qubit ≠ anc := by
    intro slot hmem
    exact hslots_ne_anc slot (by simpa [second] using List.mem_of_mem_drop hmem)
  have hdataPrepF : ∀ q : Fin (n + totalHelpers), q ≠ anc → esPrepF.paulis q = globalE q := by
    intro q hqAnc
    by_cases hqFlg : q = flg
    · subst q
      have hclean : esPrepF.paulis flg = xOfBool false := by
        simpa [esPrepF] using hprepF.1
      simpa [globalE, es0, m, flg] using hclean
    · have hF : esPrepF.paulis q = esPrepA.paulis q := by
        simpa [esPrepF] using hprepF.2.1 q hqFlg
      have hA : esPrepA.paulis q = es0.paulis q := by
        simpa [esPrepA] using hprepA.2.1 q hqAnc
      simpa [globalE] using hF.trans hA
  have hancPrepF : esPrepF.paulis anc = xOfBool false := by
    have hF : esPrepF.paulis anc = esPrepA.paulis anc := by
      simpa [esPrepF] using hprepF.2.1 anc hanc_ne_flg
    have hA : esPrepA.paulis anc = xOfBool false := by
      simpa [esPrepA] using hprepA.1
    exact hF.trans hA
  have hfirst :=
    zParitySlotsCircuit_chain anc first globalE false esPrepF
      hfirst_ne_anc hdataPrepF hancPrepF
  have hreadFirst := zParitySlotsCircuit_preserves_readout anc first esPrepF
  have hflagFirst : esFirst.paulis flg = xOfBool false := by
    have h := hfirst.2 flg hflg_ne_anc
    simpa [esFirst, globalE, es0, m, flg] using h
  have hancFirst :
      esFirst.paulis anc = xOfBool (scheduleParityList first globalE false) := by
    simpa [esFirst] using hfirst.1
  have hflag1 :=
    cleanFlagCnot_preserves_anc flg anc esFirst
      (scheduleParityList first globalE false) hflg_ne_anc hflagFirst hancFirst
  have hdataFlag1 : ∀ q : Fin (n + totalHelpers), q ≠ anc → esFlag1.paulis q = globalE q := by
    intro q hqAnc
    by_cases hqFlg : q = flg
    · subst q
      have h := hflag1.2.1
      simpa [esFlag1, globalE, es0, m, flg] using h
    · have hC : esFlag1.paulis q = esFirst.paulis q := by
        simpa [esFlag1] using hflag1.2.2.1 q hqAnc hqFlg
      have hF : esFirst.paulis q = globalE q := hfirst.2 q hqAnc
      exact hC.trans hF
  have hancFlag1 :
      esFlag1.paulis anc = xOfBool (scheduleParityList first globalE false) := by
    simpa [esFlag1] using hflag1.1
  have hsecond :=
    zParitySlotsCircuit_chain anc second globalE
      (scheduleParityList first globalE false) esFlag1
      hsecond_ne_anc hdataFlag1 hancFlag1
  have hreadSecond := zParitySlotsCircuit_preserves_readout anc second esFlag1
  have hflagSecond : esSecond.paulis flg = xOfBool false := by
    have h := hsecond.2 flg hflg_ne_anc
    simpa [esSecond, globalE, es0, m, flg] using h
  have hancSecond :
      esSecond.paulis anc =
        xOfBool (scheduleParityList second globalE
          (scheduleParityList first globalE false)) := by
    simpa [esSecond] using hsecond.1
  have hflag2 :=
    cleanFlagCnot_preserves_anc flg anc esSecond
      (scheduleParityList second globalE (scheduleParityList first globalE false))
      hflg_ne_anc hflagSecond hancSecond
  have hancFlag2 :
      esFlag2.paulis anc =
        xOfBool (scheduleParityList second globalE
          (scheduleParityList first globalE false)) := by
    simpa [esFlag2] using hflag2.1
  have hcursorPrepF : esPrepF.detectorCursor = detectorStart := by
    have hpa : esPrepA.detectorCursor = detectorStart := by
      calc
        esPrepA.detectorCursor = es0.detectorCursor := by
          simpa [esPrepA] using hprepA.2.2.2
        _ = detectorStart := by simp [es0, m]
    calc
      esPrepF.detectorCursor = esPrepA.detectorCursor := by
        simpa [esPrepF] using hprepF.2.2.2
      _ = detectorStart := hpa
  have hcursorFirst : esFirst.detectorCursor = detectorStart := by
    calc
      esFirst.detectorCursor = esPrepF.detectorCursor := by
        simpa [esFirst] using hreadFirst.2
      _ = detectorStart := hcursorPrepF
  have hcursorFlag1 : esFlag1.detectorCursor = detectorStart := by
    calc
      esFlag1.detectorCursor = esFirst.detectorCursor := by
        simpa [esFlag1] using hflag1.2.2.2.2
      _ = detectorStart := hcursorFirst
  have hcursorSecond : esSecond.detectorCursor = detectorStart := by
    calc
      esSecond.detectorCursor = esFlag1.detectorCursor := by
        simpa [esSecond] using hreadSecond.2
      _ = detectorStart := hcursorFlag1
  have hcursorFlag2 : esFlag2.detectorCursor = detectorStart := by
    calc
      esFlag2.detectorCursor = esSecond.detectorCursor := by
        simpa [esFlag2] using hflag2.2.2.2.2
      _ = detectorStart := hcursorSecond
  have hsplit :
      scheduleParityList second globalE (scheduleParityList first globalE false) =
        scheduleParityList slots globalE false := by
    simpa [first, second] using scheduleParityList_take_drop slots half globalE false
  have hglobal :
      globalE =
        fun q : Fin (n + totalHelpers) =>
          (dataInputState (k := totalHelpers)
            (fun q : Fin n => E (freshDataQ n totalHelpers q))).paulis q := by
    funext q
    by_cases hq : q.val < n
    · have hqeq : freshDataQ n totalHelpers ⟨q.val, hq⟩ = q := Fin.ext rfl
      simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
        stateOfPauliAtDetector, dataInputState, hq, hqeq]
    · simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
        stateOfPauliAtDetector, dataInputState, hq]
  have hparity :
      scheduleParityList slots globalE false =
        scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
    rw [hglobal]
    simpa [slots] using
      scheduleParityList_liftSchedule (k := totalHelpers) sigma
        (fun q : Fin n => E (freshDataQ n totalHelpers q))
  have hsynd :
      esSynd.detectors detectorStart =
        scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
    calc
      esSynd.detectors detectorStart = hasXComp (esFlag2.paulis anc) := by
        simpa [esSynd] using flagMeasZ_detector_cursor anc esFlag2 detectorStart hcursorFlag2
      _ = hasXComp
            (xOfBool (scheduleParityList second globalE
              (scheduleParityList first globalE false))) := by
            rw [hancFlag2]
      _ = scheduleParityList second globalE (scheduleParityList first globalE false) := by
            simp
      _ = scheduleParityList slots globalE false := hsplit
      _ = scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := hparity
  have hcursorSynd : esSynd.detectorCursor = detectorStart + 1 := by
    simp [esSynd, flagMeasZ, eraseFaults, propagateCircuit, propagateGate, hcursorFlag2]
  have htail :
      (propagateCircuit (eraseFaults (hadamard flg ++ flagMeasZ flg)) esSynd).detectors
          detectorStart =
        scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
    rw [flagTail_preserves_detector_at flg esSynd detectorStart hcursorSynd]
    exact hsynd
  have hcompiled :
      propagateCircuit
          (eraseFaults
            (prep0 anc ++ prepP flg ++ zParitySlotsCircuit anc first ++ cnot flg anc ++
              zParitySlotsCircuit anc second ++ cnot flg anc ++ flagMeasZ anc ++
              hadamard flg ++ flagMeasZ flg))
          es0 =
        propagateCircuit (eraseFaults (hadamard flg ++ flagMeasZ flg)) esSynd := by
    simp [zParitySlotsCircuit, esPrepA, esPrepF, esFirst, esFlag1, esSecond,
      esFlag2, esSynd, eraseFaults_append, QHL.Target.propagateCircuit_append]
  have hblock :
      propagateCircuit (eraseFaults (compileGadgetBlock .Flag sigma helperStart helperFit)) es0 =
        propagateCircuit
          (eraseFaults
            (prep0 anc ++ prepP flg ++ zParitySlotsCircuit anc first ++ cnot flg anc ++
              zParitySlotsCircuit anc second ++ cnot flg anc ++ flagMeasZ anc ++
              hadamard flg ++ flagMeasZ flg))
          es0 := by
    simp [compileGadgetBlock, compileGadgetOrdered, compileFlagOrdered, blockAncillaConfig,
      anc, flg, slots, half, first, second, zParitySlotsCircuit]
  change
    m.embeddedDetectorBit
        (propagateCircuit (eraseFaults (compileGadgetBlock .Flag sigma helperStart helperFit)) es0) =
      scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q))
  rw [hblock, hcompiled]
  simpa [m, ProgramMeasureAt.embeddedDetectorBit, ProgramMeasureAt.shiftedReadout,
    compiledReadoutFlags, compiledDetectorCount, ProgramMeasureAt.shiftFlag, xorBools]
    using htail

theorem ProgramMeasureAt.embeddedSynCorrect_Shor {n totalHelpers totalFlags : Nat}
    (sigma0 : RuleSchedule n) (helperStart detectorStart : Nat)
    (helperFit : helperStart + helperCount .Shor sigma0 ≤ totalHelpers)
    (detectorFit : detectorStart + compiledDetectorCount .Shor sigma0 ≤ totalFlags) :
    (⟨.Shor, sigma0, helperStart, detectorStart, helperFit, detectorFit⟩ :
      ProgramMeasureAt n totalHelpers totalFlags).embeddedSynCorrect := by
  apply ProgramMeasureAt.embeddedSynCorrect_of_detector
  intro E
  cases sigma0 with
  | mk sourceSlots0 =>
    cases sourceSlots0 with
    | nil =>
        simp [ProgramMeasureAt.embeddedDetectorBit, ProgramMeasureAt.shiftedReadout, xorBools,
          compiledReadoutFlags, compiledDetectorCount, compileGadgetBlock, compileGadgetOrdered,
          compileShorOrdered, blockAncillaConfig, blockShorCat, scheduleParity]
    | cons first rest =>
        let sourceSlots := first :: rest
        let sigma : RuleSchedule n := ⟨sourceSlots⟩
        let m : ProgramMeasureAt n totalHelpers totalFlags :=
          ⟨.Shor, sigma, helperStart, detectorStart, helperFit, detectorFit⟩
        let w : Nat := sourceSlots.length
        let slots : List (ScheduledPauli (n + totalHelpers)) :=
          (liftSchedule (k := totalHelpers) sigma).slots
        let cat : List (Fin (n + totalHelpers)) :=
          blockShorCat n totalHelpers helperStart w helperFit
        let verifier : Fin (n + totalHelpers) :=
          blockHelperQ n totalHelpers helperStart (w + 1) helperFit
            ⟨w, Nat.lt_succ_self w⟩
        let pairs : List (ScheduledPauli (n + totalHelpers) × Fin (n + totalHelpers)) :=
          List.zip slots cat
        let es0 : ErrorState (n + totalHelpers) := m.dataOnlyStateAtDetector E
        let globalE : Fin (n + totalHelpers) → Pauli := fun q => es0.paulis q
        have hw_pos : 0 < w := by simp [w, sourceSlots]
        have hcat_len : cat.length = w := by simp [cat, blockShorCat]
        cases hcatShape : cat with
        | nil =>
            have : w = 0 := by
              simpa [hcatShape] using hcat_len.symm
            omega
        | cons c0 catRest =>
            let cat' : List (Fin (n + totalHelpers)) := c0 :: catRest
            let last : Fin (n + totalHelpers) := cat'.getLast (by simp [cat'])
            let esCat := propagateCircuit (eraseFaults (orderedCatPrepZ cat')) es0
            let esPrepV := propagateCircuit (eraseFaults (prepP verifier)) esCat
            let esCnot1 := propagateCircuit (eraseFaults (cnot verifier c0)) esPrepV
            let esCnot2 := propagateCircuit (eraseFaults (cnot verifier last)) esCnot1
            let esHad := propagateCircuit (eraseFaults (hadamard verifier)) esCnot2
            let esPrefix := propagateCircuit (eraseFaults (flagMeasZ verifier)) esHad
            let esCoupled := propagateCircuit (eraseFaults (shorCouplingPairsCircuit pairs)) esPrefix
            have hcat_eq : cat = cat' := by simp [cat', hcatShape]
            have hcatClean0 : ∀ q, q ∈ cat → es0.paulis q = Pauli.I := by
              intro q hmem
              rcases mem_blockShorCat_helper (n := n) (total := totalHelpers)
                  (start := helperStart) (w := w) helperFit hmem with ⟨a, rfl⟩
              simp [es0, m]
            have hverClean0 : es0.paulis verifier = Pauli.I := by
              simp [es0, m, verifier]
            have hcatPrep :=
              orderedCatPrepZ_clean_preserves_all cat' es0 (by
                intro q hmem
                exact hcatClean0 q (by simpa [hcat_eq] using hmem))
            have hesCatPaulis : esCat.paulis = es0.paulis := by
              simpa [esCat] using hcatPrep.1
            have hesCatCursor : esCat.detectorCursor = detectorStart := by
              calc
                esCat.detectorCursor = es0.detectorCursor := by
                  simpa [esCat] using hcatPrep.2.2
                _ = detectorStart := by simp [es0, m]
            have hprepV := prepP_state_for_chain verifier esCat
            have hesPrepVPaulis : esPrepV.paulis = es0.paulis := by
              funext q
              by_cases hq : q = verifier
              · subst q
                simpa [esPrepV, hesCatPaulis, hverClean0, xOfBool] using hprepV.1
              · have hpres := hprepV.2.1 q hq
                rw [hpres, hesCatPaulis]
            have hesPrepVCursor : esPrepV.detectorCursor = detectorStart := by
              calc
                esPrepV.detectorCursor = esCat.detectorCursor := by
                  simpa [esPrepV] using hprepV.2.2.2
                _ = detectorStart := hesCatCursor
            have hc0CleanPrep : esPrepV.paulis c0 = Pauli.I := by
              rw [hesPrepVPaulis]
              exact hcatClean0 c0 (by simp [hcat_eq, cat'])
            have hverCleanPrep : esPrepV.paulis verifier = Pauli.I := by
              rw [hesPrepVPaulis]
              exact hverClean0
            have hcnot1 :=
              cleanCnot_preserves_all verifier c0 esPrepV hverCleanPrep hc0CleanPrep
            have hesCnot1Paulis : esCnot1.paulis = es0.paulis := by
              calc
                esCnot1.paulis = esPrepV.paulis := by simpa [esCnot1] using hcnot1.1
                _ = es0.paulis := hesPrepVPaulis
            have hesCnot1Cursor : esCnot1.detectorCursor = detectorStart := by
              calc
                esCnot1.detectorCursor = esPrepV.detectorCursor := by
                  simpa [esCnot1] using hcnot1.2.2
                _ = detectorStart := hesPrepVCursor
            have hlast_mem_cat : last ∈ cat := by
              have hlast : last ∈ cat' := by
                simp [last, cat']
              simpa [hcat_eq] using hlast
            have hlastClean : esCnot1.paulis last = Pauli.I := by
              rw [hesCnot1Paulis]
              exact hcatClean0 last hlast_mem_cat
            have hverCleanCnot1 : esCnot1.paulis verifier = Pauli.I := by
              rw [hesCnot1Paulis]
              exact hverClean0
            have hcnot2 :=
              cleanCnot_preserves_all verifier last esCnot1 hverCleanCnot1 hlastClean
            have hesCnot2Paulis : esCnot2.paulis = es0.paulis := by
              calc
                esCnot2.paulis = esCnot1.paulis := by simpa [esCnot2] using hcnot2.1
                _ = es0.paulis := hesCnot1Paulis
            have hesCnot2Cursor : esCnot2.detectorCursor = detectorStart := by
              calc
                esCnot2.detectorCursor = esCnot1.detectorCursor := by
                  simpa [esCnot2] using hcnot2.2.2
                _ = detectorStart := hesCnot1Cursor
            have hverCleanCnot2 : esCnot2.paulis verifier = Pauli.I := by
              rw [hesCnot2Paulis]
              exact hverClean0
            have hhad := hadamard_clean_preserves_all verifier esCnot2 hverCleanCnot2
            have hesHadPaulis : esHad.paulis = es0.paulis := by
              calc
                esHad.paulis = esCnot2.paulis := by simpa [esHad] using hhad.1
                _ = es0.paulis := hesCnot2Paulis
            have hesHadCursor : esHad.detectorCursor = detectorStart := by
              calc
                esHad.detectorCursor = esCnot2.detectorCursor := by
                  simpa [esHad] using hhad.2.2
                _ = detectorStart := hesCnot2Cursor
            have hverCleanHad : esHad.paulis verifier = Pauli.I := by
              rw [hesHadPaulis]
              exact hverClean0
            have hflag := flagMeasZ_clean_cursor verifier esHad detectorStart
              hverCleanHad hesHadCursor
            have hesPrefixPaulis : esPrefix.paulis = es0.paulis := by
              calc
                esPrefix.paulis = esHad.paulis := by simpa [esPrefix] using hflag.2.2
                _ = es0.paulis := hesHadPaulis
            have hesPrefixCursor : esPrefix.detectorCursor = detectorStart + 1 := by
              simpa [esPrefix] using hflag.2.1
            have hslot_mem :
                ∀ slot, slot ∈ slots →
                  ∃ src, src ∈ sourceSlots ∧ slot = liftSlot (k := totalHelpers) src := by
              intro slot hmem
              have hmem' : slot ∈ sourceSlots.map (liftSlot (k := totalHelpers)) := by
                simpa [slots, sigma, liftSchedule] using hmem
              rcases List.mem_map.mp hmem' with ⟨src, hsrc, rfl⟩
              exact ⟨src, hsrc, rfl⟩
            have hslot_ne_cat :
                ∀ slotPair, slotPair ∈ pairs →
                  ∀ catPair, catPair ∈ pairs → slotPair.1.qubit ≠ catPair.2 := by
              intro slotPair hslotPair catPair hcatPair
              have hs_mem : slotPair.1 ∈ slots := (List.of_mem_zip hslotPair).1
              have hc_mem : catPair.2 ∈ cat := (List.of_mem_zip hcatPair).2
              rcases hslot_mem slotPair.1 hs_mem with ⟨src, _hsrc, hsrcEq⟩
              rcases mem_blockShorCat_helper (n := n) (total := totalHelpers)
                  (start := helperStart) (w := w) helperFit hc_mem with ⟨a, haEq⟩
              rw [hsrcEq, haEq]
              simpa [liftSlot] using
                (freshDataQ_ne_blockHelperQ (n := n) (total := totalHelpers)
                  (start := helperStart) (width := w + 1) helperFit src.qubit
                  ⟨a.val, by exact Nat.lt_trans a.isLt (Nat.lt_succ_self w)⟩)
            have hcat_nodup : cat.Nodup := by
              simpa [cat] using
                blockShorCat_nodup (n := n) (total := totalHelpers)
                  (start := helperStart) (w := w) helperFit
            have hpairs_nodup : pairs.Nodup := by
              exact zip_nodup_of_right_nodup slots cat hcat_nodup
            have hcat_ne :
                ∀ pairA, pairA ∈ pairs →
                  ∀ pairB, pairB ∈ pairs → pairA ≠ pairB → pairA.2 ≠ pairB.2 := by
              exact zip_right_ne_of_right_nodup slots cat hcat_nodup
            have hcouple :=
              shorCouplingPairsCircuit_chain pairs globalE esPrefix hpairs_nodup
                (by
                  intro pair hmem
                  simpa [globalE] using congrFun hesPrefixPaulis pair.1.qubit)
                (by
                  intro pair hmem
                  have hc_mem : pair.2 ∈ cat := (List.of_mem_zip hmem).2
                  rw [hesPrefixPaulis]
                  simpa [xOfBool] using hcatClean0 pair.2 hc_mem)
                (by
                  intro pair hmem
                  exact hslot_ne_cat pair hmem pair hmem)
                hslot_ne_cat hcat_ne
            have hcoupledCursor : esCoupled.detectorCursor = detectorStart + 1 := by
              calc
                esCoupled.detectorCursor = esPrefix.detectorCursor := by
                  simpa [esCoupled] using hcouple.2.2.2
                _ = detectorStart + 1 := hesPrefixCursor
            have hraw :=
              rawMeasZPairsCircuit_chain pairs globalE false esCoupled (detectorStart + 1)
                hcoupledCursor (by
                  intro pair hmem
                  simpa [esCoupled] using hcouple.1 pair hmem)
            have hslots_le_cat : slots.length ≤ cat.length := by
              simp [slots, cat, sigma, liftSchedule, blockShorCat, w, sourceSlots]
            have hcat_le_slots : cat.length ≤ slots.length := by
              simp [slots, cat, sigma, liftSchedule, blockShorCat, w, sourceSlots]
            have hmapPairs : pairs.map Prod.fst = slots := by
              simpa [pairs] using List.map_fst_zip hslots_le_cat
            have hrawPairs : rawMeasZPairsCircuit pairs = (cat.map rawMeasZ).flatten := by
              have hsnd : pairs.map Prod.snd = cat := by
                simpa [pairs] using List.map_snd_zip hcat_le_slots
              unfold rawMeasZPairsCircuit
              rw [← hsnd]
              simp [List.map_map, Function.comp_def]
            have hrawPairsCat : rawMeasZPairsCircuit pairs = (cat'.map rawMeasZ).flatten := by
              rw [hrawPairs, hcat_eq]
            have hpairs_len : pairs.length = w := by
              simp [pairs, slots, cat, sigma, liftSchedule, blockShorCat, w, sourceSlots]
            have hglobal :
                globalE =
                  fun q : Fin (n + totalHelpers) =>
                    (dataInputState (k := totalHelpers)
                      (fun q : Fin n => E (freshDataQ n totalHelpers q))).paulis q := by
              funext q
              by_cases hq : q.val < n
              · have hqeq : freshDataQ n totalHelpers ⟨q.val, hq⟩ = q := Fin.ext rfl
                simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
                  stateOfPauliAtDetector, dataInputState, hq, hqeq]
              · simp [globalE, es0, m, ProgramMeasureAt.dataOnlyStateAtDetector,
                  stateOfPauliAtDetector, dataInputState, hq]
            have hparity :
                scheduleParityList (pairs.map Prod.fst) globalE false =
                  scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := by
              rw [hmapPairs, hglobal]
              simpa [slots, sigma, w] using
                scheduleParityList_liftSchedule (k := totalHelpers) sigma
                  (fun q : Fin n => E (freshDataQ n totalHelpers q))
            have hcompiledCircuit :
                eraseFaults (compileGadgetBlock .Shor sigma helperStart helperFit) =
                  eraseFaults (orderedCatPrepZ cat') ++
                    eraseFaults (prepP verifier) ++
                    eraseFaults (cnot verifier c0) ++
                    eraseFaults (cnot verifier last) ++
                    eraseFaults (hadamard verifier) ++
                    eraseFaults (flagMeasZ verifier) ++
                    eraseFaults (shorCouplingPairsCircuit pairs) ++
                    eraseFaults ((cat'.map rawMeasZ).flatten) := by
              simp only [compileGadgetBlock, compileGadgetOrdered, compileShorOrdered,
                blockAncillaConfig, sigma, sourceSlots, w, cat, hcatShape, cat', last,
                verifier, pairs, slots, shorCouplingPairsCircuit]
              exact eraseFaults_append8 (orderedCatPrepZ (c0 :: catRest)) (prepP verifier)
                (cnot verifier c0) (cnot verifier ((c0 :: catRest).getLast (by simp)))
                (hadamard verifier) (flagMeasZ verifier)
                ((List.map (fun pair => shorCouplingSlot pair.1 pair.2)
                  ((liftSchedule { slots := first :: rest }).slots.zip (c0 :: catRest))).flatten)
                ((List.map rawMeasZ (c0 :: catRest)).flatten)
            have hcompiled :
                propagateCircuit (eraseFaults (compileGadgetBlock .Shor sigma helperStart helperFit)) es0 =
                  propagateCircuit (eraseFaults (rawMeasZPairsCircuit pairs)) esCoupled := by
              rw [hrawPairsCat, hcompiledCircuit]
              simpa [esCat, esPrepV, esCnot1, esCnot2, esHad, esPrefix, esCoupled] using
                (propagateCircuit_append8 (eraseFaults (orderedCatPrepZ cat'))
                  (eraseFaults (prepP verifier)) (eraseFaults (cnot verifier c0))
                  (eraseFaults (cnot verifier last)) (eraseFaults (hadamard verifier))
                  (eraseFaults (flagMeasZ verifier))
                  (eraseFaults (shorCouplingPairsCircuit pairs))
                  (eraseFaults ((cat'.map rawMeasZ).flatten)) es0)
            change
              m.embeddedDetectorBit
                (propagateCircuit (eraseFaults (compileGadgetBlock .Shor sigma helperStart helperFit)) es0) =
                scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q))
            rw [hcompiled]
            calc
              m.embeddedDetectorBit
                  (propagateCircuit (eraseFaults (rawMeasZPairsCircuit pairs)) esCoupled)
                  = detectorXorFromAcc (detectorStart + 1) w
                      (propagateCircuit (eraseFaults (rawMeasZPairsCircuit pairs)) esCoupled)
                      false := by
                    simp [m, ProgramMeasureAt.embeddedDetectorBit,
                      ProgramMeasureAt.shiftedReadout, compiledReadoutFlags,
                      compiledDetectorCount, ProgramMeasureAt.shiftFlag,
                      xorBools_finRange_shift_succ_eq_fromAcc, Function.comp_def,
                      sigma, sourceSlots, w]
              _ = detectorXorFromAcc (detectorStart + 1) pairs.length
                      (propagateCircuit (eraseFaults (rawMeasZPairsCircuit pairs)) esCoupled)
                      false := by
                    rw [hpairs_len]
              _ = scheduleParityList (pairs.map Prod.fst) globalE false := hraw.1
              _ = scheduleParity sigma (fun q : Fin n => E (freshDataQ n totalHelpers q)) := hparity

theorem ProgramMeasureAt.embeddedSynCorrect_auto {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) :
    m.embeddedSynCorrect := by
  cases m with
  | mk scheme schedule helperStart detectorStart helperFit detectorFit =>
      cases scheme
      · exact ProgramMeasureAt.embeddedSynCorrect_NZ schedule helperStart detectorStart
          helperFit detectorFit
      · exact ProgramMeasureAt.embeddedSynCorrect_Knill schedule helperStart detectorStart
          helperFit detectorFit
      · exact ProgramMeasureAt.embeddedSynCorrect_Shor schedule helperStart detectorStart
          helperFit detectorFit
      · exact ProgramMeasureAt.embeddedSynCorrect_Flag schedule helperStart detectorStart
          helperFit detectorFit

def ProgramMeasureAt.embeddedHoareCertificate_auto {n totalHelpers totalFlags : Nat}
    (m : ProgramMeasureAt n totalHelpers totalFlags) :
    m.EmbeddedHoareCertificate :=
  ProgramMeasureAt.embeddedHoareCertificateOfCorrect
    (ProgramMeasureAt.embeddedSynCorrect_auto m)

theorem fullProgramEmbeddedSynCorrect_of_blocks {n : Nat} (program : XZProgram n)
    (hdisjoint : fullProgramReadoutDisjoint program)
    (hblocks :
      ∀ i : Fin (programNumStab program),
        ((programMeasuresAt program).get i).embeddedSynCorrect) :
    fullProgramEmbeddedSynCorrect program hdisjoint := by
  intro i E
  specialize hblocks i E
  have hstate :
      stateOfDataPauliAtDetector (fullProgramCodeSpec program hdisjoint)
          ((programMeasuresAt program).get i).detectorStart E =
        ((programMeasuresAt program).get i).dataOnlyStateAtDetector E := by
    simp [stateOfDataPauliAtDetector, stateOfPauliAtDetector,
      ProgramMeasureAt.dataOnlyStateAtDetector]
    funext q
    simp
  simpa [gadgetMeasFlip, syndromeBit, fullProgramCodeSpec,
    ProgramMeasureAt.embeddedSynCorrect, ProgramMeasureAt.embeddedDetectorBit, parity, hstate]
    using hblocks

theorem fullProgram_vcgen_syn_of_embeddedSynCorrect {n : Nat}
    (program : XZProgram n) (hdisjoint : fullProgramReadoutDisjoint program)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program)
    (hsyn : fullProgramEmbeddedSynCorrect program hdisjoint) :
    (vcgen (fullProgramVCInput program hdisjoint hnq hnumStab)).denoteSlot .syn := by
  apply vcgen_syn_of_semantic_syn
  simpa [fullProgramVCInput, VCInput.toCodeSpec_ofPCC] using hsyn

def fullProgramBlockHoareCertificates {n : Nat} (program : XZProgram n) :
    ∀ i : Fin (programNumStab program),
      ((programMeasuresAt program).get i).EmbeddedHoareCertificate :=
  fun i => ProgramMeasureAt.embeddedHoareCertificate_auto ((programMeasuresAt program).get i)

theorem fullProgramEmbeddedSynCorrect_of_hoareBlocks {n : Nat}
    (program : XZProgram n) (hdisjoint : fullProgramReadoutDisjoint program)
    (hblocks :
      ∀ i : Fin (programNumStab program),
        ((programMeasuresAt program).get i).EmbeddedHoareCertificate) :
    fullProgramEmbeddedSynCorrect program hdisjoint :=
  fullProgramEmbeddedSynCorrect_of_blocks program hdisjoint
    (fun i => (hblocks i).to_embeddedSynCorrect)

/-- Full-program generated syndrome certificate: `programEq` and `wf` are
closed for the compiler-generated spec, and each `.syn` leaf is backed by a real
QClifford `DerivC` derivation for the corresponding embedded stabilizer block. -/
def fullProgramSyndromeHoareCertificate {n : Nat}
    (program : XZProgram n) (hdisjoint : fullProgramReadoutDisjoint program)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    SyndromeHoareCertificate (fullProgramVCInput program hdisjoint hnq hnumStab) where
  programEq := fullProgram_vcgen_programEq program hdisjoint hnq hnumStab
  wf := fullProgram_vcgen_wf program hdisjoint hnq hnumStab
  deriv := by
    intro i
    refine QHL.Target.DerivC.C_Consequence
      (circuitWPDeriv
        (eraseFaults ((fullProgramCodeSpec program hdisjoint).gadget i))
        (syndromeHoarePost (fullProgramVCInput program hdisjoint hnq hnumStab) i))
      ?_ ?_
    · intro es hpre
      rcases hpre with ⟨E0, rfl⟩
      intro E hEq
      rw [hEq]
      have hsyn :
          fullProgramEmbeddedSynCorrect program hdisjoint :=
        fullProgramEmbeddedSynCorrect_of_hoareBlocks program hdisjoint
          (fullProgramBlockHoareCertificates program)
      have hlocal := hsyn i E
      simpa [fullProgramVCInput, VCInput.toCodeSpec_ofPCC, gadgetMeasFlip]
        using hlocal
    · intro es h
      exact h

theorem fullProgram_vcgen_syn_of_hoareCertificate {n : Nat}
    (program : XZProgram n) (hdisjoint : fullProgramReadoutDisjoint program)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    (vcgen (fullProgramVCInput program hdisjoint hnq hnumStab)).denoteSlot .syn :=
  (fullProgramSyndromeHoareCertificate program hdisjoint hnq hnumStab).syn

def generatedFullProgramCodeSpec {n : Nat} (program : XZProgram n) :
    CodeSpec (n + programHelperCount program) :=
  fullProgramCodeSpec program (fullProgramReadoutDisjoint_auto program)

def generatedFullProgramVCInput {n : Nat} (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    VCInput (n + programHelperCount program) :=
  fullProgramVCInput program (fullProgramReadoutDisjoint_auto program) hnq hnumStab

theorem generatedFullProgram_vcgen_programEq {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .programEq :=
  fullProgram_vcgen_programEq program (fullProgramReadoutDisjoint_auto program) hnq hnumStab

theorem generatedFullProgram_vcgen_wf {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .wf :=
  fullProgram_vcgen_wf program (fullProgramReadoutDisjoint_auto program) hnq hnumStab

def generatedFullProgramSyndromeHoareCertificate {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    SyndromeHoareCertificate (generatedFullProgramVCInput program hnq hnumStab) :=
  fullProgramSyndromeHoareCertificate program (fullProgramReadoutDisjoint_auto program)
    hnq hnumStab

structure ProgramCompilationHoareSynCertificate {n : Nat} (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) where
  circuit : FCircuit (n + programHelperCount program)
  compileDeriv : ProgramCompileDeriv 0 program circuit
  programEq : (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .programEq
  wf : (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .wf
  hoareSyn : SyndromeHoareCertificate (generatedFullProgramVCInput program hnq hnumStab)
  syn : (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .syn :=
    hoareSyn.syn

def XZProgram.generatedCompilationHoareSynCertificate {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    ProgramCompilationHoareSynCertificate program hnq hnumStab where
  circuit := compileProgram program
  compileDeriv := compileProgramDeriv program
  programEq := generatedFullProgram_vcgen_programEq program hnq hnumStab
  wf := generatedFullProgram_vcgen_wf program hnq hnumStab
  hoareSyn := generatedFullProgramSyndromeHoareCertificate program hnq hnumStab

def generatedFullProgramEmbeddedSynCorrect {n : Nat} (program : XZProgram n) : Prop :=
  fullProgramEmbeddedSynCorrect program (fullProgramReadoutDisjoint_auto program)

def generatedFullProgramBlocksSynCorrect {n : Nat} (program : XZProgram n) : Prop :=
  ∀ i : Fin (programNumStab program),
    ((programMeasuresAt program).get i).embeddedSynCorrect

theorem generatedFullProgramBlocksSynCorrect_auto {n : Nat} (program : XZProgram n) :
    generatedFullProgramBlocksSynCorrect program := by
  intro i
  exact ProgramMeasureAt.embeddedSynCorrect_auto ((programMeasuresAt program).get i)

theorem generatedFullProgram_embeddedSynCorrect_of_blocks {n : Nat}
    (program : XZProgram n)
    (hblocks : generatedFullProgramBlocksSynCorrect program) :
    generatedFullProgramEmbeddedSynCorrect program := by
  exact fullProgramEmbeddedSynCorrect_of_blocks program
    (fullProgramReadoutDisjoint_auto program) hblocks

theorem generatedFullProgramEmbeddedSynCorrect_auto {n : Nat} (program : XZProgram n) :
    generatedFullProgramEmbeddedSynCorrect program := by
  exact generatedFullProgram_embeddedSynCorrect_of_blocks program
    (generatedFullProgramBlocksSynCorrect_auto program)

theorem generatedFullProgram_vcgen_syn_of_embeddedSynCorrect {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program)
    (hsyn : generatedFullProgramEmbeddedSynCorrect program) :
    (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .syn := by
  exact fullProgram_vcgen_syn_of_embeddedSynCorrect program
    (fullProgramReadoutDisjoint_auto program) hnq hnumStab hsyn

theorem generatedFullProgram_vcgen_syn_of_blocks {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program)
    (hblocks : generatedFullProgramBlocksSynCorrect program) :
    (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .syn := by
  exact generatedFullProgram_vcgen_syn_of_embeddedSynCorrect program hnq hnumStab
    (generatedFullProgram_embeddedSynCorrect_of_blocks program hblocks)

theorem generatedFullProgram_vcgen_syn {n : Nat}
    (program : XZProgram n)
    (hnq : 0 < n + programHelperCount program)
    (hnumStab : 0 < programNumStab program) :
    (vcgen (generatedFullProgramVCInput program hnq hnumStab)).denoteSlot .syn := by
  exact (generatedFullProgramSyndromeHoareCertificate program hnq hnumStab).syn

/-! ## Concrete generated syndrome VC example -/

namespace VCBridgeExamples

def q0 : Fin 1 := ⟨0, by decide⟩

def Z0 : RuleSchedule 1 :=
  ⟨[⟨.Z, q0⟩]⟩

/-- A fully generated `.syn` VC proof for the fixed source instruction
`VCBridgeExamples.Z0`, valid for any of the four compiler schemes.  The four
examples below instantiate this theorem as the concrete checked certificates
that a producer would emit for a fixed QStab instruction. -/
theorem z0_singleGadget_vcgen_syn (scheme : Scheme)
    (hnq : 0 < 1 + helperCount scheme Z0) :
    (vcgen
      (singleGadgetVCInput scheme Z0
        (scheduleRow (k := helperCount scheme Z0) Z0) hnq)).denoteSlot .syn :=
  singleGadget_vcgen_syn scheme Z0 hnq

example :
    (vcgen
      (singleGadgetVCInput .NZ Z0
        (scheduleRow (k := helperCount .NZ Z0) Z0) (by decide))).denoteSlot .syn :=
  z0_singleGadget_vcgen_syn .NZ (by decide)

example :
    (vcgen
      (singleGadgetVCInput .Knill Z0
        (scheduleRow (k := helperCount .Knill Z0) Z0) (by decide))).denoteSlot .syn :=
  z0_singleGadget_vcgen_syn .Knill (by decide)

example :
    (vcgen
      (singleGadgetVCInput .Shor Z0
        (scheduleRow (k := helperCount .Shor Z0) Z0) (by decide))).denoteSlot .syn :=
  z0_singleGadget_vcgen_syn .Shor (by decide)

example :
    (vcgen
      (singleGadgetVCInput .Flag Z0
        (scheduleRow (k := helperCount .Flag Z0) Z0) (by decide))).denoteSlot .syn :=
  z0_singleGadget_vcgen_syn .Flag (by decide)

end VCBridgeExamples

end QStab.QClifford.PCC
